// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: bank_server.proto

package bank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bank_PayinCallBank_FullMethodName    = "/protobuf.bank/PayinCallBank"
	Bank_PayinCheckOrder_FullMethodName  = "/protobuf.bank/PayinCheckOrder"
	Bank_PayoutCallBank_FullMethodName   = "/protobuf.bank/PayoutCallBank"
	Bank_PayoutCheckOrder_FullMethodName = "/protobuf.bank/PayoutCheckOrder"
	Bank_CheckBalance_FullMethodName     = "/protobuf.bank/CheckBalance"
)

// BankClient is the client API for Bank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankClient interface {
	PayinCallBank(ctx context.Context, in *PayinRequest, opts ...grpc.CallOption) (*PayinResponse, error)
	PayinCheckOrder(ctx context.Context, in *CheckOrderRequest, opts ...grpc.CallOption) (*CheckOrderResponse, error)
	PayoutCallBank(ctx context.Context, in *PayoutRequest, opts ...grpc.CallOption) (*PayoutResponse, error)
	PayoutCheckOrder(ctx context.Context, in *CheckOrderRequest, opts ...grpc.CallOption) (*CheckOrderResponse, error)
	CheckBalance(ctx context.Context, in *CheckBalanceReq, opts ...grpc.CallOption) (*CheckBalanceResp, error)
}

type bankClient struct {
	cc grpc.ClientConnInterface
}

func NewBankClient(cc grpc.ClientConnInterface) BankClient {
	return &bankClient{cc}
}

func (c *bankClient) PayinCallBank(ctx context.Context, in *PayinRequest, opts ...grpc.CallOption) (*PayinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinResponse)
	err := c.cc.Invoke(ctx, Bank_PayinCallBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) PayinCheckOrder(ctx context.Context, in *CheckOrderRequest, opts ...grpc.CallOption) (*CheckOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOrderResponse)
	err := c.cc.Invoke(ctx, Bank_PayinCheckOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) PayoutCallBank(ctx context.Context, in *PayoutRequest, opts ...grpc.CallOption) (*PayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutResponse)
	err := c.cc.Invoke(ctx, Bank_PayoutCallBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) PayoutCheckOrder(ctx context.Context, in *CheckOrderRequest, opts ...grpc.CallOption) (*CheckOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOrderResponse)
	err := c.cc.Invoke(ctx, Bank_PayoutCheckOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) CheckBalance(ctx context.Context, in *CheckBalanceReq, opts ...grpc.CallOption) (*CheckBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBalanceResp)
	err := c.cc.Invoke(ctx, Bank_CheckBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServer is the server API for Bank service.
// All implementations must embed UnimplementedBankServer
// for forward compatibility.
type BankServer interface {
	PayinCallBank(context.Context, *PayinRequest) (*PayinResponse, error)
	PayinCheckOrder(context.Context, *CheckOrderRequest) (*CheckOrderResponse, error)
	PayoutCallBank(context.Context, *PayoutRequest) (*PayoutResponse, error)
	PayoutCheckOrder(context.Context, *CheckOrderRequest) (*CheckOrderResponse, error)
	CheckBalance(context.Context, *CheckBalanceReq) (*CheckBalanceResp, error)
	mustEmbedUnimplementedBankServer()
}

// UnimplementedBankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankServer struct{}

func (UnimplementedBankServer) PayinCallBank(context.Context, *PayinRequest) (*PayinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayinCallBank not implemented")
}
func (UnimplementedBankServer) PayinCheckOrder(context.Context, *CheckOrderRequest) (*CheckOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayinCheckOrder not implemented")
}
func (UnimplementedBankServer) PayoutCallBank(context.Context, *PayoutRequest) (*PayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayoutCallBank not implemented")
}
func (UnimplementedBankServer) PayoutCheckOrder(context.Context, *CheckOrderRequest) (*CheckOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayoutCheckOrder not implemented")
}
func (UnimplementedBankServer) CheckBalance(context.Context, *CheckBalanceReq) (*CheckBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBalance not implemented")
}
func (UnimplementedBankServer) mustEmbedUnimplementedBankServer() {}
func (UnimplementedBankServer) testEmbeddedByValue()              {}

// UnsafeBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankServer will
// result in compilation errors.
type UnsafeBankServer interface {
	mustEmbedUnimplementedBankServer()
}

func RegisterBankServer(s grpc.ServiceRegistrar, srv BankServer) {
	// If the following call pancis, it indicates UnimplementedBankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bank_ServiceDesc, srv)
}

func _Bank_PayinCallBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).PayinCallBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bank_PayinCallBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).PayinCallBank(ctx, req.(*PayinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_PayinCheckOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).PayinCheckOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bank_PayinCheckOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).PayinCheckOrder(ctx, req.(*CheckOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_PayoutCallBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).PayoutCallBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bank_PayoutCallBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).PayoutCallBank(ctx, req.(*PayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_PayoutCheckOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).PayoutCheckOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bank_PayoutCheckOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).PayoutCheckOrder(ctx, req.(*CheckOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_CheckBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).CheckBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bank_CheckBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).CheckBalance(ctx, req.(*CheckBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Bank_ServiceDesc is the grpc.ServiceDesc for Bank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.bank",
	HandlerType: (*BankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayinCallBank",
			Handler:    _Bank_PayinCallBank_Handler,
		},
		{
			MethodName: "PayinCheckOrder",
			Handler:    _Bank_PayinCheckOrder_Handler,
		},
		{
			MethodName: "PayoutCallBank",
			Handler:    _Bank_PayoutCallBank_Handler,
		},
		{
			MethodName: "PayoutCheckOrder",
			Handler:    _Bank_PayoutCheckOrder_Handler,
		},
		{
			MethodName: "CheckBalance",
			Handler:    _Bank_CheckBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank_server.proto",
}
