// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: sys_config/sys_config.proto

package sys_config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysConfig_GetSysConfig_FullMethodName  = "/pb.SysConfig/GetSysConfig"
	SysConfig_SaveSysConfig_FullMethodName = "/pb.SysConfig/SaveSysConfig"
)

// SysConfigClient is the client API for SysConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysConfigClient interface {
	GetSysConfig(ctx context.Context, in *GetSysCofnigReq, opts ...grpc.CallOption) (*GetSysCofnigResp, error)
	SaveSysConfig(ctx context.Context, in *SaveSysCofnigReq, opts ...grpc.CallOption) (*SaveSysCofnigResp, error)
}

type sysConfigClient struct {
	cc grpc.ClientConnInterface
}

func NewSysConfigClient(cc grpc.ClientConnInterface) SysConfigClient {
	return &sysConfigClient{cc}
}

func (c *sysConfigClient) GetSysConfig(ctx context.Context, in *GetSysCofnigReq, opts ...grpc.CallOption) (*GetSysCofnigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSysCofnigResp)
	err := c.cc.Invoke(ctx, SysConfig_GetSysConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) SaveSysConfig(ctx context.Context, in *SaveSysCofnigReq, opts ...grpc.CallOption) (*SaveSysCofnigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSysCofnigResp)
	err := c.cc.Invoke(ctx, SysConfig_SaveSysConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysConfigServer is the server API for SysConfig service.
// All implementations must embed UnimplementedSysConfigServer
// for forward compatibility.
type SysConfigServer interface {
	GetSysConfig(context.Context, *GetSysCofnigReq) (*GetSysCofnigResp, error)
	SaveSysConfig(context.Context, *SaveSysCofnigReq) (*SaveSysCofnigResp, error)
	mustEmbedUnimplementedSysConfigServer()
}

// UnimplementedSysConfigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysConfigServer struct{}

func (UnimplementedSysConfigServer) GetSysConfig(context.Context, *GetSysCofnigReq) (*GetSysCofnigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSysConfig not implemented")
}
func (UnimplementedSysConfigServer) SaveSysConfig(context.Context, *SaveSysCofnigReq) (*SaveSysCofnigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSysConfig not implemented")
}
func (UnimplementedSysConfigServer) mustEmbedUnimplementedSysConfigServer() {}
func (UnimplementedSysConfigServer) testEmbeddedByValue()                   {}

// UnsafeSysConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysConfigServer will
// result in compilation errors.
type UnsafeSysConfigServer interface {
	mustEmbedUnimplementedSysConfigServer()
}

func RegisterSysConfigServer(s grpc.ServiceRegistrar, srv SysConfigServer) {
	// If the following call pancis, it indicates UnimplementedSysConfigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysConfig_ServiceDesc, srv)
}

func _SysConfig_GetSysConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSysCofnigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).GetSysConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysConfig_GetSysConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).GetSysConfig(ctx, req.(*GetSysCofnigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_SaveSysConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSysCofnigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).SaveSysConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysConfig_SaveSysConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).SaveSysConfig(ctx, req.(*SaveSysCofnigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SysConfig_ServiceDesc is the grpc.ServiceDesc for SysConfig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysConfig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SysConfig",
	HandlerType: (*SysConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSysConfig",
			Handler:    _SysConfig_GetSysConfig_Handler,
		},
		{
			MethodName: "SaveSysConfig",
			Handler:    _SysConfig_SaveSysConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_config/sys_config.proto",
}
