// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: payout.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payout_Create_FullMethodName                              = "/pb.Payout/Create"
	Payout_GetList_FullMethodName                             = "/pb.Payout/GetList"
	Payout_Callback_FullMethodName                            = "/pb.Payout/Callback"
	Payout_GetMerchantOrderInfo_FullMethodName                = "/pb.Payout/GetMerchantOrderInfo"
	Payout_NotifySuccess_FullMethodName                       = "/pb.Payout/NotifySuccess"
	Payout_GetPayoutOrderListCumulativeSummary_FullMethodName = "/pb.Payout/GetPayoutOrderListCumulativeSummary"
	Payout_BatchUpdateRefundPayoutOrder_FullMethodName        = "/pb.Payout/BatchUpdateRefundPayoutOrder"
	Payout_GetPayoutOrderStatisticsData_FullMethodName        = "/pb.Payout/GetPayoutOrderStatisticsData"
	Payout_QueryOrderInfo_FullMethodName                      = "/pb.Payout/QueryOrderInfo"
	Payout_QueryMerchantBalance_FullMethodName                = "/pb.Payout/QueryMerchantBalance"
	Payout_QueryOrderLog_FullMethodName                       = "/pb.Payout/QueryOrderLog"
	Payout_ManualPayoutOrder_FullMethodName                   = "/pb.Payout/ManualPayoutOrder"
	Payout_DispatchOrder_FullMethodName                       = "/pb.Payout/DispatchOrder"
	Payout_ResetReleaseCount_FullMethodName                   = "/pb.Payout/ResetReleaseCount"
	Payout_GetMerchantByOrder_FullMethodName                  = "/pb.Payout/GetMerchantByOrder"
	Payout_GetPayoutDispatchTask_FullMethodName               = "/pb.Payout/GetPayoutDispatchTask"
	Payout_GetRiskControlRule_FullMethodName                  = "/pb.Payout/GetRiskControlRule"
	Payout_UpdateRiskControlRule_FullMethodName               = "/pb.Payout/UpdateRiskControlRule"
	Payout_GetPayoutAccountSummary_FullMethodName             = "/pb.Payout/GetPayoutAccountSummary"
	Payout_GetPayoutAlarmOrder_FullMethodName                 = "/pb.Payout/GetPayoutAlarmOrder"
	Payout_PayoutAlarmOrderRelease_FullMethodName             = "/pb.Payout/PayoutAlarmOrderRelease"
	Payout_SubmitPayout_FullMethodName                        = "/pb.Payout/SubmitPayout"
	Payout_GetPayoutStatus_FullMethodName                     = "/pb.Payout/GetPayoutStatus"
	Payout_GetPayoutBalance_FullMethodName                    = "/pb.Payout/GetPayoutBalance"
)

// PayoutClient is the client API for Payout service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayoutClient interface {
	// create payout order
	Create(ctx context.Context, in *CreatePayoutOrderReq, opts ...grpc.CallOption) (*CreatePayoutOrderResp, error)
	// get payout order list
	GetList(ctx context.Context, in *GetPayoutOrderListReq, opts ...grpc.CallOption) (*GetPayoutOrderListResp, error)
	// payuot order callback
	Callback(ctx context.Context, in *CallbackPayoutOrderReq, opts ...grpc.CallOption) (*CallbackPayoutOrderResp, error)
	// get order info detail
	GetMerchantOrderInfo(ctx context.Context, in *GetPayoutOrderInfoReq, opts ...grpc.CallOption) (*GetPayoutOrderInfoResp, error)
	// notify merchant success
	NotifySuccess(ctx context.Context, in *PayoutNotifySuccessReq, opts ...grpc.CallOption) (*PayoutNotifySuccessResp, error)
	GetPayoutOrderListCumulativeSummary(ctx context.Context, in *GetPayoutOrderListReq, opts ...grpc.CallOption) (*PayoutOrderListCumulativeSummaryResponse, error)
	BatchUpdateRefundPayoutOrder(ctx context.Context, in *BatchUpdateRefundPayoutOrderParam, opts ...grpc.CallOption) (*BatchUpdatePayoutOrderResponse, error)
	GetPayoutOrderStatisticsData(ctx context.Context, in *GetPayoutOrderStatisticsDataReq, opts ...grpc.CallOption) (*GetPayoutOrderStatisticsDataResp, error)
	// query payout order info
	QueryOrderInfo(ctx context.Context, in *QueryOrderInfoReq, opts ...grpc.CallOption) (*QueryOrderInfoResp, error)
	QueryMerchantBalance(ctx context.Context, in *QueryMerchantBalanceReq, opts ...grpc.CallOption) (*QueryMerchantBalanceResp, error)
	QueryOrderLog(ctx context.Context, in *QueryPayoutOrderLogReq, opts ...grpc.CallOption) (*QueryPayoutOrderLogResp, error)
	ManualPayoutOrder(ctx context.Context, in *ManualPayoutOrderReq, opts ...grpc.CallOption) (*ManualPayoutOrderResp, error)
	DispatchOrder(ctx context.Context, in *DispatchOrderReq, opts ...grpc.CallOption) (*DispatchOrderResp, error)
	ResetReleaseCount(ctx context.Context, in *ResetReleaseCountReq, opts ...grpc.CallOption) (*ManualPayoutOrderResp, error)
	GetMerchantByOrder(ctx context.Context, in *GetMerchantByOrderReq, opts ...grpc.CallOption) (*GetMerchantByOrderResp, error)
	GetPayoutDispatchTask(ctx context.Context, in *GetPayoutDispatchTaskReq, opts ...grpc.CallOption) (*GetPayoutDispatchTaskResp, error)
	// risk control
	GetRiskControlRule(ctx context.Context, in *GetRiskControlRuleReq, opts ...grpc.CallOption) (*GetRiskControlRuleResp, error)
	UpdateRiskControlRule(ctx context.Context, in *UpdateRiskControlRuleReq, opts ...grpc.CallOption) (*UpdateRiskControlRuleResp, error)
	GetPayoutAccountSummary(ctx context.Context, in *GetPayoutAccountSummaryReq, opts ...grpc.CallOption) (*GetPayoutAccountSummaryResp, error)
	GetPayoutAlarmOrder(ctx context.Context, in *GetPayoutAlarmOrderReq, opts ...grpc.CallOption) (*GetPayoutAlarmOrderResp, error)
	PayoutAlarmOrderRelease(ctx context.Context, in *PayoutAlarmOrderReleaseReq, opts ...grpc.CallOption) (*PayoutAlarmOrderReleaseResp, error)
	// 出金提交 - 对应 /payment/payout/submit
	SubmitPayout(ctx context.Context, in *PayoutSubmitRequest, opts ...grpc.CallOption) (*PayoutSubmitResponse, error)
	// 查询出金状态 - 对应 /payment/payout/status
	GetPayoutStatus(ctx context.Context, in *PayoutStatusRequest, opts ...grpc.CallOption) (*PayoutStatusResponse, error)
	// 查询出金余额 - 对应 /payment/payout/balance
	GetPayoutBalance(ctx context.Context, in *PayoutBalanceRequest, opts ...grpc.CallOption) (*PayoutBalanceResponse, error)
}

type payoutClient struct {
	cc grpc.ClientConnInterface
}

func NewPayoutClient(cc grpc.ClientConnInterface) PayoutClient {
	return &payoutClient{cc}
}

func (c *payoutClient) Create(ctx context.Context, in *CreatePayoutOrderReq, opts ...grpc.CallOption) (*CreatePayoutOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePayoutOrderResp)
	err := c.cc.Invoke(ctx, Payout_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetList(ctx context.Context, in *GetPayoutOrderListReq, opts ...grpc.CallOption) (*GetPayoutOrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutOrderListResp)
	err := c.cc.Invoke(ctx, Payout_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) Callback(ctx context.Context, in *CallbackPayoutOrderReq, opts ...grpc.CallOption) (*CallbackPayoutOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackPayoutOrderResp)
	err := c.cc.Invoke(ctx, Payout_Callback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetMerchantOrderInfo(ctx context.Context, in *GetPayoutOrderInfoReq, opts ...grpc.CallOption) (*GetPayoutOrderInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutOrderInfoResp)
	err := c.cc.Invoke(ctx, Payout_GetMerchantOrderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) NotifySuccess(ctx context.Context, in *PayoutNotifySuccessReq, opts ...grpc.CallOption) (*PayoutNotifySuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutNotifySuccessResp)
	err := c.cc.Invoke(ctx, Payout_NotifySuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutOrderListCumulativeSummary(ctx context.Context, in *GetPayoutOrderListReq, opts ...grpc.CallOption) (*PayoutOrderListCumulativeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutOrderListCumulativeSummaryResponse)
	err := c.cc.Invoke(ctx, Payout_GetPayoutOrderListCumulativeSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) BatchUpdateRefundPayoutOrder(ctx context.Context, in *BatchUpdateRefundPayoutOrderParam, opts ...grpc.CallOption) (*BatchUpdatePayoutOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdatePayoutOrderResponse)
	err := c.cc.Invoke(ctx, Payout_BatchUpdateRefundPayoutOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutOrderStatisticsData(ctx context.Context, in *GetPayoutOrderStatisticsDataReq, opts ...grpc.CallOption) (*GetPayoutOrderStatisticsDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutOrderStatisticsDataResp)
	err := c.cc.Invoke(ctx, Payout_GetPayoutOrderStatisticsData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) QueryOrderInfo(ctx context.Context, in *QueryOrderInfoReq, opts ...grpc.CallOption) (*QueryOrderInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryOrderInfoResp)
	err := c.cc.Invoke(ctx, Payout_QueryOrderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) QueryMerchantBalance(ctx context.Context, in *QueryMerchantBalanceReq, opts ...grpc.CallOption) (*QueryMerchantBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMerchantBalanceResp)
	err := c.cc.Invoke(ctx, Payout_QueryMerchantBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) QueryOrderLog(ctx context.Context, in *QueryPayoutOrderLogReq, opts ...grpc.CallOption) (*QueryPayoutOrderLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPayoutOrderLogResp)
	err := c.cc.Invoke(ctx, Payout_QueryOrderLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) ManualPayoutOrder(ctx context.Context, in *ManualPayoutOrderReq, opts ...grpc.CallOption) (*ManualPayoutOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualPayoutOrderResp)
	err := c.cc.Invoke(ctx, Payout_ManualPayoutOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) DispatchOrder(ctx context.Context, in *DispatchOrderReq, opts ...grpc.CallOption) (*DispatchOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchOrderResp)
	err := c.cc.Invoke(ctx, Payout_DispatchOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) ResetReleaseCount(ctx context.Context, in *ResetReleaseCountReq, opts ...grpc.CallOption) (*ManualPayoutOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualPayoutOrderResp)
	err := c.cc.Invoke(ctx, Payout_ResetReleaseCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetMerchantByOrder(ctx context.Context, in *GetMerchantByOrderReq, opts ...grpc.CallOption) (*GetMerchantByOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantByOrderResp)
	err := c.cc.Invoke(ctx, Payout_GetMerchantByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutDispatchTask(ctx context.Context, in *GetPayoutDispatchTaskReq, opts ...grpc.CallOption) (*GetPayoutDispatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutDispatchTaskResp)
	err := c.cc.Invoke(ctx, Payout_GetPayoutDispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetRiskControlRule(ctx context.Context, in *GetRiskControlRuleReq, opts ...grpc.CallOption) (*GetRiskControlRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiskControlRuleResp)
	err := c.cc.Invoke(ctx, Payout_GetRiskControlRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) UpdateRiskControlRule(ctx context.Context, in *UpdateRiskControlRuleReq, opts ...grpc.CallOption) (*UpdateRiskControlRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRiskControlRuleResp)
	err := c.cc.Invoke(ctx, Payout_UpdateRiskControlRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutAccountSummary(ctx context.Context, in *GetPayoutAccountSummaryReq, opts ...grpc.CallOption) (*GetPayoutAccountSummaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutAccountSummaryResp)
	err := c.cc.Invoke(ctx, Payout_GetPayoutAccountSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutAlarmOrder(ctx context.Context, in *GetPayoutAlarmOrderReq, opts ...grpc.CallOption) (*GetPayoutAlarmOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutAlarmOrderResp)
	err := c.cc.Invoke(ctx, Payout_GetPayoutAlarmOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) PayoutAlarmOrderRelease(ctx context.Context, in *PayoutAlarmOrderReleaseReq, opts ...grpc.CallOption) (*PayoutAlarmOrderReleaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutAlarmOrderReleaseResp)
	err := c.cc.Invoke(ctx, Payout_PayoutAlarmOrderRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) SubmitPayout(ctx context.Context, in *PayoutSubmitRequest, opts ...grpc.CallOption) (*PayoutSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutSubmitResponse)
	err := c.cc.Invoke(ctx, Payout_SubmitPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutStatus(ctx context.Context, in *PayoutStatusRequest, opts ...grpc.CallOption) (*PayoutStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutStatusResponse)
	err := c.cc.Invoke(ctx, Payout_GetPayoutStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutClient) GetPayoutBalance(ctx context.Context, in *PayoutBalanceRequest, opts ...grpc.CallOption) (*PayoutBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutBalanceResponse)
	err := c.cc.Invoke(ctx, Payout_GetPayoutBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayoutServer is the server API for Payout service.
// All implementations must embed UnimplementedPayoutServer
// for forward compatibility.
type PayoutServer interface {
	// create payout order
	Create(context.Context, *CreatePayoutOrderReq) (*CreatePayoutOrderResp, error)
	// get payout order list
	GetList(context.Context, *GetPayoutOrderListReq) (*GetPayoutOrderListResp, error)
	// payuot order callback
	Callback(context.Context, *CallbackPayoutOrderReq) (*CallbackPayoutOrderResp, error)
	// get order info detail
	GetMerchantOrderInfo(context.Context, *GetPayoutOrderInfoReq) (*GetPayoutOrderInfoResp, error)
	// notify merchant success
	NotifySuccess(context.Context, *PayoutNotifySuccessReq) (*PayoutNotifySuccessResp, error)
	GetPayoutOrderListCumulativeSummary(context.Context, *GetPayoutOrderListReq) (*PayoutOrderListCumulativeSummaryResponse, error)
	BatchUpdateRefundPayoutOrder(context.Context, *BatchUpdateRefundPayoutOrderParam) (*BatchUpdatePayoutOrderResponse, error)
	GetPayoutOrderStatisticsData(context.Context, *GetPayoutOrderStatisticsDataReq) (*GetPayoutOrderStatisticsDataResp, error)
	// query payout order info
	QueryOrderInfo(context.Context, *QueryOrderInfoReq) (*QueryOrderInfoResp, error)
	QueryMerchantBalance(context.Context, *QueryMerchantBalanceReq) (*QueryMerchantBalanceResp, error)
	QueryOrderLog(context.Context, *QueryPayoutOrderLogReq) (*QueryPayoutOrderLogResp, error)
	ManualPayoutOrder(context.Context, *ManualPayoutOrderReq) (*ManualPayoutOrderResp, error)
	DispatchOrder(context.Context, *DispatchOrderReq) (*DispatchOrderResp, error)
	ResetReleaseCount(context.Context, *ResetReleaseCountReq) (*ManualPayoutOrderResp, error)
	GetMerchantByOrder(context.Context, *GetMerchantByOrderReq) (*GetMerchantByOrderResp, error)
	GetPayoutDispatchTask(context.Context, *GetPayoutDispatchTaskReq) (*GetPayoutDispatchTaskResp, error)
	// risk control
	GetRiskControlRule(context.Context, *GetRiskControlRuleReq) (*GetRiskControlRuleResp, error)
	UpdateRiskControlRule(context.Context, *UpdateRiskControlRuleReq) (*UpdateRiskControlRuleResp, error)
	GetPayoutAccountSummary(context.Context, *GetPayoutAccountSummaryReq) (*GetPayoutAccountSummaryResp, error)
	GetPayoutAlarmOrder(context.Context, *GetPayoutAlarmOrderReq) (*GetPayoutAlarmOrderResp, error)
	PayoutAlarmOrderRelease(context.Context, *PayoutAlarmOrderReleaseReq) (*PayoutAlarmOrderReleaseResp, error)
	// 出金提交 - 对应 /payment/payout/submit
	SubmitPayout(context.Context, *PayoutSubmitRequest) (*PayoutSubmitResponse, error)
	// 查询出金状态 - 对应 /payment/payout/status
	GetPayoutStatus(context.Context, *PayoutStatusRequest) (*PayoutStatusResponse, error)
	// 查询出金余额 - 对应 /payment/payout/balance
	GetPayoutBalance(context.Context, *PayoutBalanceRequest) (*PayoutBalanceResponse, error)
	mustEmbedUnimplementedPayoutServer()
}

// UnimplementedPayoutServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayoutServer struct{}

func (UnimplementedPayoutServer) Create(context.Context, *CreatePayoutOrderReq) (*CreatePayoutOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPayoutServer) GetList(context.Context, *GetPayoutOrderListReq) (*GetPayoutOrderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedPayoutServer) Callback(context.Context, *CallbackPayoutOrderReq) (*CallbackPayoutOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callback not implemented")
}
func (UnimplementedPayoutServer) GetMerchantOrderInfo(context.Context, *GetPayoutOrderInfoReq) (*GetPayoutOrderInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantOrderInfo not implemented")
}
func (UnimplementedPayoutServer) NotifySuccess(context.Context, *PayoutNotifySuccessReq) (*PayoutNotifySuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifySuccess not implemented")
}
func (UnimplementedPayoutServer) GetPayoutOrderListCumulativeSummary(context.Context, *GetPayoutOrderListReq) (*PayoutOrderListCumulativeSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutOrderListCumulativeSummary not implemented")
}
func (UnimplementedPayoutServer) BatchUpdateRefundPayoutOrder(context.Context, *BatchUpdateRefundPayoutOrderParam) (*BatchUpdatePayoutOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateRefundPayoutOrder not implemented")
}
func (UnimplementedPayoutServer) GetPayoutOrderStatisticsData(context.Context, *GetPayoutOrderStatisticsDataReq) (*GetPayoutOrderStatisticsDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutOrderStatisticsData not implemented")
}
func (UnimplementedPayoutServer) QueryOrderInfo(context.Context, *QueryOrderInfoReq) (*QueryOrderInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrderInfo not implemented")
}
func (UnimplementedPayoutServer) QueryMerchantBalance(context.Context, *QueryMerchantBalanceReq) (*QueryMerchantBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMerchantBalance not implemented")
}
func (UnimplementedPayoutServer) QueryOrderLog(context.Context, *QueryPayoutOrderLogReq) (*QueryPayoutOrderLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrderLog not implemented")
}
func (UnimplementedPayoutServer) ManualPayoutOrder(context.Context, *ManualPayoutOrderReq) (*ManualPayoutOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManualPayoutOrder not implemented")
}
func (UnimplementedPayoutServer) DispatchOrder(context.Context, *DispatchOrderReq) (*DispatchOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchOrder not implemented")
}
func (UnimplementedPayoutServer) ResetReleaseCount(context.Context, *ResetReleaseCountReq) (*ManualPayoutOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetReleaseCount not implemented")
}
func (UnimplementedPayoutServer) GetMerchantByOrder(context.Context, *GetMerchantByOrderReq) (*GetMerchantByOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantByOrder not implemented")
}
func (UnimplementedPayoutServer) GetPayoutDispatchTask(context.Context, *GetPayoutDispatchTaskReq) (*GetPayoutDispatchTaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutDispatchTask not implemented")
}
func (UnimplementedPayoutServer) GetRiskControlRule(context.Context, *GetRiskControlRuleReq) (*GetRiskControlRuleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiskControlRule not implemented")
}
func (UnimplementedPayoutServer) UpdateRiskControlRule(context.Context, *UpdateRiskControlRuleReq) (*UpdateRiskControlRuleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRiskControlRule not implemented")
}
func (UnimplementedPayoutServer) GetPayoutAccountSummary(context.Context, *GetPayoutAccountSummaryReq) (*GetPayoutAccountSummaryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutAccountSummary not implemented")
}
func (UnimplementedPayoutServer) GetPayoutAlarmOrder(context.Context, *GetPayoutAlarmOrderReq) (*GetPayoutAlarmOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutAlarmOrder not implemented")
}
func (UnimplementedPayoutServer) PayoutAlarmOrderRelease(context.Context, *PayoutAlarmOrderReleaseReq) (*PayoutAlarmOrderReleaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayoutAlarmOrderRelease not implemented")
}
func (UnimplementedPayoutServer) SubmitPayout(context.Context, *PayoutSubmitRequest) (*PayoutSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPayout not implemented")
}
func (UnimplementedPayoutServer) GetPayoutStatus(context.Context, *PayoutStatusRequest) (*PayoutStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutStatus not implemented")
}
func (UnimplementedPayoutServer) GetPayoutBalance(context.Context, *PayoutBalanceRequest) (*PayoutBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutBalance not implemented")
}
func (UnimplementedPayoutServer) mustEmbedUnimplementedPayoutServer() {}
func (UnimplementedPayoutServer) testEmbeddedByValue()                {}

// UnsafePayoutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayoutServer will
// result in compilation errors.
type UnsafePayoutServer interface {
	mustEmbedUnimplementedPayoutServer()
}

func RegisterPayoutServer(s grpc.ServiceRegistrar, srv PayoutServer) {
	// If the following call pancis, it indicates UnimplementedPayoutServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payout_ServiceDesc, srv)
}

func _Payout_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePayoutOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).Create(ctx, req.(*CreatePayoutOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetList(ctx, req.(*GetPayoutOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackPayoutOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_Callback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).Callback(ctx, req.(*CallbackPayoutOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetMerchantOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutOrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetMerchantOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetMerchantOrderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetMerchantOrderInfo(ctx, req.(*GetPayoutOrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_NotifySuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutNotifySuccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).NotifySuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_NotifySuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).NotifySuccess(ctx, req.(*PayoutNotifySuccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutOrderListCumulativeSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutOrderListCumulativeSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutOrderListCumulativeSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutOrderListCumulativeSummary(ctx, req.(*GetPayoutOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_BatchUpdateRefundPayoutOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateRefundPayoutOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).BatchUpdateRefundPayoutOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_BatchUpdateRefundPayoutOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).BatchUpdateRefundPayoutOrder(ctx, req.(*BatchUpdateRefundPayoutOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutOrderStatisticsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutOrderStatisticsDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutOrderStatisticsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutOrderStatisticsData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutOrderStatisticsData(ctx, req.(*GetPayoutOrderStatisticsDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_QueryOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).QueryOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_QueryOrderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).QueryOrderInfo(ctx, req.(*QueryOrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_QueryMerchantBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerchantBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).QueryMerchantBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_QueryMerchantBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).QueryMerchantBalance(ctx, req.(*QueryMerchantBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_QueryOrderLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPayoutOrderLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).QueryOrderLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_QueryOrderLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).QueryOrderLog(ctx, req.(*QueryPayoutOrderLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_ManualPayoutOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualPayoutOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).ManualPayoutOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_ManualPayoutOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).ManualPayoutOrder(ctx, req.(*ManualPayoutOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_DispatchOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).DispatchOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_DispatchOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).DispatchOrder(ctx, req.(*DispatchOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_ResetReleaseCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetReleaseCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).ResetReleaseCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_ResetReleaseCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).ResetReleaseCount(ctx, req.(*ResetReleaseCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetMerchantByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantByOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetMerchantByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetMerchantByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetMerchantByOrder(ctx, req.(*GetMerchantByOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutDispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutDispatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutDispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutDispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutDispatchTask(ctx, req.(*GetPayoutDispatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetRiskControlRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskControlRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetRiskControlRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetRiskControlRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetRiskControlRule(ctx, req.(*GetRiskControlRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_UpdateRiskControlRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRiskControlRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).UpdateRiskControlRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_UpdateRiskControlRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).UpdateRiskControlRule(ctx, req.(*UpdateRiskControlRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutAccountSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutAccountSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutAccountSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutAccountSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutAccountSummary(ctx, req.(*GetPayoutAccountSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutAlarmOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutAlarmOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutAlarmOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutAlarmOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutAlarmOrder(ctx, req.(*GetPayoutAlarmOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_PayoutAlarmOrderRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutAlarmOrderReleaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).PayoutAlarmOrderRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_PayoutAlarmOrderRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).PayoutAlarmOrderRelease(ctx, req.(*PayoutAlarmOrderReleaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_SubmitPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).SubmitPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_SubmitPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).SubmitPayout(ctx, req.(*PayoutSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutStatus(ctx, req.(*PayoutStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payout_GetPayoutBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServer).GetPayoutBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payout_GetPayoutBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServer).GetPayoutBalance(ctx, req.(*PayoutBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payout_ServiceDesc is the grpc.ServiceDesc for Payout service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payout_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Payout",
	HandlerType: (*PayoutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Payout_Create_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _Payout_GetList_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Payout_Callback_Handler,
		},
		{
			MethodName: "GetMerchantOrderInfo",
			Handler:    _Payout_GetMerchantOrderInfo_Handler,
		},
		{
			MethodName: "NotifySuccess",
			Handler:    _Payout_NotifySuccess_Handler,
		},
		{
			MethodName: "GetPayoutOrderListCumulativeSummary",
			Handler:    _Payout_GetPayoutOrderListCumulativeSummary_Handler,
		},
		{
			MethodName: "BatchUpdateRefundPayoutOrder",
			Handler:    _Payout_BatchUpdateRefundPayoutOrder_Handler,
		},
		{
			MethodName: "GetPayoutOrderStatisticsData",
			Handler:    _Payout_GetPayoutOrderStatisticsData_Handler,
		},
		{
			MethodName: "QueryOrderInfo",
			Handler:    _Payout_QueryOrderInfo_Handler,
		},
		{
			MethodName: "QueryMerchantBalance",
			Handler:    _Payout_QueryMerchantBalance_Handler,
		},
		{
			MethodName: "QueryOrderLog",
			Handler:    _Payout_QueryOrderLog_Handler,
		},
		{
			MethodName: "ManualPayoutOrder",
			Handler:    _Payout_ManualPayoutOrder_Handler,
		},
		{
			MethodName: "DispatchOrder",
			Handler:    _Payout_DispatchOrder_Handler,
		},
		{
			MethodName: "ResetReleaseCount",
			Handler:    _Payout_ResetReleaseCount_Handler,
		},
		{
			MethodName: "GetMerchantByOrder",
			Handler:    _Payout_GetMerchantByOrder_Handler,
		},
		{
			MethodName: "GetPayoutDispatchTask",
			Handler:    _Payout_GetPayoutDispatchTask_Handler,
		},
		{
			MethodName: "GetRiskControlRule",
			Handler:    _Payout_GetRiskControlRule_Handler,
		},
		{
			MethodName: "UpdateRiskControlRule",
			Handler:    _Payout_UpdateRiskControlRule_Handler,
		},
		{
			MethodName: "GetPayoutAccountSummary",
			Handler:    _Payout_GetPayoutAccountSummary_Handler,
		},
		{
			MethodName: "GetPayoutAlarmOrder",
			Handler:    _Payout_GetPayoutAlarmOrder_Handler,
		},
		{
			MethodName: "PayoutAlarmOrderRelease",
			Handler:    _Payout_PayoutAlarmOrderRelease_Handler,
		},
		{
			MethodName: "SubmitPayout",
			Handler:    _Payout_SubmitPayout_Handler,
		},
		{
			MethodName: "GetPayoutStatus",
			Handler:    _Payout_GetPayoutStatus_Handler,
		},
		{
			MethodName: "GetPayoutBalance",
			Handler:    _Payout_GetPayoutBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payout.proto",
}
