// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: country.proto

package country

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Country_CreateCountry_FullMethodName  = "/pb.Country/CreateCountry"
	Country_GetCountryList_FullMethodName = "/pb.Country/GetCountryList"
	Country_DeleteCountry_FullMethodName  = "/pb.Country/DeleteCountry"
)

// CountryClient is the client API for Country service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CountryClient interface {
	// create Country
	CreateCountry(ctx context.Context, in *CreateCountryInfoReq, opts ...grpc.CallOption) (*CountryInfoResp, error)
	// get Country list
	GetCountryList(ctx context.Context, in *GetCountryListReq, opts ...grpc.CallOption) (*GetCountryListResp, error)
	// delete Country
	DeleteCountry(ctx context.Context, in *DeleteCountryReq, opts ...grpc.CallOption) (*DeleteCountryResp, error)
}

type countryClient struct {
	cc grpc.ClientConnInterface
}

func NewCountryClient(cc grpc.ClientConnInterface) CountryClient {
	return &countryClient{cc}
}

func (c *countryClient) CreateCountry(ctx context.Context, in *CreateCountryInfoReq, opts ...grpc.CallOption) (*CountryInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountryInfoResp)
	err := c.cc.Invoke(ctx, Country_CreateCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countryClient) GetCountryList(ctx context.Context, in *GetCountryListReq, opts ...grpc.CallOption) (*GetCountryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCountryListResp)
	err := c.cc.Invoke(ctx, Country_GetCountryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countryClient) DeleteCountry(ctx context.Context, in *DeleteCountryReq, opts ...grpc.CallOption) (*DeleteCountryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCountryResp)
	err := c.cc.Invoke(ctx, Country_DeleteCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountryServer is the server API for Country service.
// All implementations must embed UnimplementedCountryServer
// for forward compatibility.
type CountryServer interface {
	// create Country
	CreateCountry(context.Context, *CreateCountryInfoReq) (*CountryInfoResp, error)
	// get Country list
	GetCountryList(context.Context, *GetCountryListReq) (*GetCountryListResp, error)
	// delete Country
	DeleteCountry(context.Context, *DeleteCountryReq) (*DeleteCountryResp, error)
	mustEmbedUnimplementedCountryServer()
}

// UnimplementedCountryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCountryServer struct{}

func (UnimplementedCountryServer) CreateCountry(context.Context, *CreateCountryInfoReq) (*CountryInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCountry not implemented")
}
func (UnimplementedCountryServer) GetCountryList(context.Context, *GetCountryListReq) (*GetCountryListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountryList not implemented")
}
func (UnimplementedCountryServer) DeleteCountry(context.Context, *DeleteCountryReq) (*DeleteCountryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCountry not implemented")
}
func (UnimplementedCountryServer) mustEmbedUnimplementedCountryServer() {}
func (UnimplementedCountryServer) testEmbeddedByValue()                 {}

// UnsafeCountryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CountryServer will
// result in compilation errors.
type UnsafeCountryServer interface {
	mustEmbedUnimplementedCountryServer()
}

func RegisterCountryServer(s grpc.ServiceRegistrar, srv CountryServer) {
	// If the following call pancis, it indicates UnimplementedCountryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Country_ServiceDesc, srv)
}

func _Country_CreateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCountryInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).CreateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_CreateCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).CreateCountry(ctx, req.(*CreateCountryInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Country_GetCountryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).GetCountryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_GetCountryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).GetCountryList(ctx, req.(*GetCountryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Country_DeleteCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCountryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).DeleteCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_DeleteCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).DeleteCountry(ctx, req.(*DeleteCountryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Country_ServiceDesc is the grpc.ServiceDesc for Country service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Country_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Country",
	HandlerType: (*CountryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCountry",
			Handler:    _Country_CreateCountry_Handler,
		},
		{
			MethodName: "GetCountryList",
			Handler:    _Country_GetCountryList_Handler,
		},
		{
			MethodName: "DeleteCountry",
			Handler:    _Country_DeleteCountry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "country.proto",
}
