// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: msg_temp/msg_temp.proto

package msg_temp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MsgTemp_CreateMessageTemplate_FullMethodName = "/pb.MsgTemp/CreateMessageTemplate"
	MsgTemp_UpdateMessageTemplate_FullMethodName = "/pb.MsgTemp/UpdateMessageTemplate"
	MsgTemp_DeleteMessageTemplate_FullMethodName = "/pb.MsgTemp/DeleteMessageTemplate"
	MsgTemp_GetMessageTemplate_FullMethodName    = "/pb.MsgTemp/GetMessageTemplate"
)

// MsgTempClient is the client API for MsgTemp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgTempClient interface {
	CreateMessageTemplate(ctx context.Context, in *MessageTemplateInfo, opts ...grpc.CallOption) (*MessageTemplateCommResp, error)
	UpdateMessageTemplate(ctx context.Context, in *MessageTemplateInfo, opts ...grpc.CallOption) (*MessageTemplateCommResp, error)
	DeleteMessageTemplate(ctx context.Context, in *MessageTemplateInfo, opts ...grpc.CallOption) (*MessageTemplateCommResp, error)
	GetMessageTemplate(ctx context.Context, in *GetMsgTempReq, opts ...grpc.CallOption) (*GetMsgTempResp, error)
}

type msgTempClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgTempClient(cc grpc.ClientConnInterface) MsgTempClient {
	return &msgTempClient{cc}
}

func (c *msgTempClient) CreateMessageTemplate(ctx context.Context, in *MessageTemplateInfo, opts ...grpc.CallOption) (*MessageTemplateCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageTemplateCommResp)
	err := c.cc.Invoke(ctx, MsgTemp_CreateMessageTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgTempClient) UpdateMessageTemplate(ctx context.Context, in *MessageTemplateInfo, opts ...grpc.CallOption) (*MessageTemplateCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageTemplateCommResp)
	err := c.cc.Invoke(ctx, MsgTemp_UpdateMessageTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgTempClient) DeleteMessageTemplate(ctx context.Context, in *MessageTemplateInfo, opts ...grpc.CallOption) (*MessageTemplateCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageTemplateCommResp)
	err := c.cc.Invoke(ctx, MsgTemp_DeleteMessageTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgTempClient) GetMessageTemplate(ctx context.Context, in *GetMsgTempReq, opts ...grpc.CallOption) (*GetMsgTempResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMsgTempResp)
	err := c.cc.Invoke(ctx, MsgTemp_GetMessageTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgTempServer is the server API for MsgTemp service.
// All implementations must embed UnimplementedMsgTempServer
// for forward compatibility.
type MsgTempServer interface {
	CreateMessageTemplate(context.Context, *MessageTemplateInfo) (*MessageTemplateCommResp, error)
	UpdateMessageTemplate(context.Context, *MessageTemplateInfo) (*MessageTemplateCommResp, error)
	DeleteMessageTemplate(context.Context, *MessageTemplateInfo) (*MessageTemplateCommResp, error)
	GetMessageTemplate(context.Context, *GetMsgTempReq) (*GetMsgTempResp, error)
	mustEmbedUnimplementedMsgTempServer()
}

// UnimplementedMsgTempServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgTempServer struct{}

func (UnimplementedMsgTempServer) CreateMessageTemplate(context.Context, *MessageTemplateInfo) (*MessageTemplateCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessageTemplate not implemented")
}
func (UnimplementedMsgTempServer) UpdateMessageTemplate(context.Context, *MessageTemplateInfo) (*MessageTemplateCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessageTemplate not implemented")
}
func (UnimplementedMsgTempServer) DeleteMessageTemplate(context.Context, *MessageTemplateInfo) (*MessageTemplateCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessageTemplate not implemented")
}
func (UnimplementedMsgTempServer) GetMessageTemplate(context.Context, *GetMsgTempReq) (*GetMsgTempResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageTemplate not implemented")
}
func (UnimplementedMsgTempServer) mustEmbedUnimplementedMsgTempServer() {}
func (UnimplementedMsgTempServer) testEmbeddedByValue()                 {}

// UnsafeMsgTempServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgTempServer will
// result in compilation errors.
type UnsafeMsgTempServer interface {
	mustEmbedUnimplementedMsgTempServer()
}

func RegisterMsgTempServer(s grpc.ServiceRegistrar, srv MsgTempServer) {
	// If the following call pancis, it indicates UnimplementedMsgTempServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MsgTemp_ServiceDesc, srv)
}

func _MsgTemp_CreateMessageTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageTemplateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgTempServer).CreateMessageTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgTemp_CreateMessageTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgTempServer).CreateMessageTemplate(ctx, req.(*MessageTemplateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgTemp_UpdateMessageTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageTemplateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgTempServer).UpdateMessageTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgTemp_UpdateMessageTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgTempServer).UpdateMessageTemplate(ctx, req.(*MessageTemplateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgTemp_DeleteMessageTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageTemplateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgTempServer).DeleteMessageTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgTemp_DeleteMessageTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgTempServer).DeleteMessageTemplate(ctx, req.(*MessageTemplateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgTemp_GetMessageTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMsgTempReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgTempServer).GetMessageTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgTemp_GetMessageTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgTempServer).GetMessageTemplate(ctx, req.(*GetMsgTempReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgTemp_ServiceDesc is the grpc.ServiceDesc for MsgTemp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgTemp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MsgTemp",
	HandlerType: (*MsgTempServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessageTemplate",
			Handler:    _MsgTemp_CreateMessageTemplate_Handler,
		},
		{
			MethodName: "UpdateMessageTemplate",
			Handler:    _MsgTemp_UpdateMessageTemplate_Handler,
		},
		{
			MethodName: "DeleteMessageTemplate",
			Handler:    _MsgTemp_DeleteMessageTemplate_Handler,
		},
		{
			MethodName: "GetMessageTemplate",
			Handler:    _MsgTemp_GetMessageTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_temp/msg_temp.proto",
}
