// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: deposit_order.proto

package deposit_order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositOrderModel struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CreateTime         string                 `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateUnix         int64                  `protobuf:"varint,2,opt,name=create_unix,json=createUnix,proto3" json:"create_unix,omitempty"`
	UpdateTime         string                 `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Id                 uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	MerchantAppid      string                 `protobuf:"bytes,5,opt,name=merchant_appid,json=merchantAppid,proto3" json:"merchant_appid,omitempty"`
	MerchantId         uint64                 `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName       string                 `protobuf:"bytes,7,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	OrderNo            string                 `protobuf:"bytes,8,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	RemittanceName     string                 `protobuf:"bytes,9,opt,name=remittance_name,json=remittanceName,proto3" json:"remittance_name,omitempty"`
	RemittanceAccount  string                 `protobuf:"bytes,10,opt,name=remittance_account,json=remittanceAccount,proto3" json:"remittance_account,omitempty"`
	RemittanceUsername string                 `protobuf:"bytes,11,opt,name=remittance_username,json=remittanceUsername,proto3" json:"remittance_username,omitempty"`
	RemittancePhone    string                 `protobuf:"bytes,12,opt,name=remittance_phone,json=remittancePhone,proto3" json:"remittance_phone,omitempty"`
	CollectionAccount  string                 `protobuf:"bytes,13,opt,name=collection_account,json=collectionAccount,proto3" json:"collection_account,omitempty"`
	CollectionName     string                 `protobuf:"bytes,14,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CollectionUsername string                 `protobuf:"bytes,15,opt,name=collection_username,json=collectionUsername,proto3" json:"collection_username,omitempty"`
	CollectionPhone    string                 `protobuf:"bytes,16,opt,name=collection_phone,json=collectionPhone,proto3" json:"collection_phone,omitempty"`
	Currency           string                 `protobuf:"bytes,17,opt,name=currency,proto3" json:"currency,omitempty"`
	TargetCurrency     string                 `protobuf:"bytes,18,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	TransferAmount     int64                  `protobuf:"varint,19,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	TransferOrderNo    string                 `protobuf:"bytes,20,opt,name=transfer_order_no,json=transferOrderNo,proto3" json:"transfer_order_no,omitempty"`
	ExchangeRate       int64                  `protobuf:"varint,21,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	ActualAmount       int64                  `protobuf:"varint,23,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	Utr                string                 `protobuf:"bytes,25,opt,name=utr,proto3" json:"utr,omitempty"`
	Remark             string                 `protobuf:"bytes,26,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderStatus        int64                  `protobuf:"varint,27,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DepositType        int64                  `protobuf:"varint,28,opt,name=deposit_type,json=depositType,proto3" json:"deposit_type,omitempty"`
	AuditTime          string                 `protobuf:"bytes,29,opt,name=audit_time,json=auditTime,proto3" json:"audit_time,omitempty"`
	TransferStatus     int64                  `protobuf:"varint,30,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	NotifyTime         string                 `protobuf:"bytes,31,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`
	CompleteTime       string                 `protobuf:"bytes,32,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`
	AdjustAmount       int64                  `protobuf:"varint,33,opt,name=adjust_amount,json=adjustAmount,proto3" json:"adjust_amount,omitempty"`
	ReversalTime       string                 `protobuf:"bytes,34,opt,name=reversal_time,json=reversalTime,proto3" json:"reversal_time,omitempty"`
	AdjustExchangeRate int64                  `protobuf:"varint,35,opt,name=adjust_exchange_rate,json=adjustExchangeRate,proto3" json:"adjust_exchange_rate,omitempty"`
	AdminRemark        string                 `protobuf:"bytes,36,opt,name=admin_remark,json=adminRemark,proto3" json:"admin_remark,omitempty"`
	Attachment         string                 `protobuf:"bytes,37,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DepositOrderModel) Reset() {
	*x = DepositOrderModel{}
	mi := &file_deposit_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositOrderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOrderModel) ProtoMessage() {}

func (x *DepositOrderModel) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOrderModel.ProtoReflect.Descriptor instead.
func (*DepositOrderModel) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{0}
}

func (x *DepositOrderModel) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *DepositOrderModel) GetCreateUnix() int64 {
	if x != nil {
		return x.CreateUnix
	}
	return 0
}

func (x *DepositOrderModel) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *DepositOrderModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepositOrderModel) GetMerchantAppid() string {
	if x != nil {
		return x.MerchantAppid
	}
	return ""
}

func (x *DepositOrderModel) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *DepositOrderModel) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *DepositOrderModel) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *DepositOrderModel) GetRemittanceName() string {
	if x != nil {
		return x.RemittanceName
	}
	return ""
}

func (x *DepositOrderModel) GetRemittanceAccount() string {
	if x != nil {
		return x.RemittanceAccount
	}
	return ""
}

func (x *DepositOrderModel) GetRemittanceUsername() string {
	if x != nil {
		return x.RemittanceUsername
	}
	return ""
}

func (x *DepositOrderModel) GetRemittancePhone() string {
	if x != nil {
		return x.RemittancePhone
	}
	return ""
}

func (x *DepositOrderModel) GetCollectionAccount() string {
	if x != nil {
		return x.CollectionAccount
	}
	return ""
}

func (x *DepositOrderModel) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *DepositOrderModel) GetCollectionUsername() string {
	if x != nil {
		return x.CollectionUsername
	}
	return ""
}

func (x *DepositOrderModel) GetCollectionPhone() string {
	if x != nil {
		return x.CollectionPhone
	}
	return ""
}

func (x *DepositOrderModel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DepositOrderModel) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *DepositOrderModel) GetTransferAmount() int64 {
	if x != nil {
		return x.TransferAmount
	}
	return 0
}

func (x *DepositOrderModel) GetTransferOrderNo() string {
	if x != nil {
		return x.TransferOrderNo
	}
	return ""
}

func (x *DepositOrderModel) GetExchangeRate() int64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *DepositOrderModel) GetActualAmount() int64 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *DepositOrderModel) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *DepositOrderModel) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DepositOrderModel) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *DepositOrderModel) GetDepositType() int64 {
	if x != nil {
		return x.DepositType
	}
	return 0
}

func (x *DepositOrderModel) GetAuditTime() string {
	if x != nil {
		return x.AuditTime
	}
	return ""
}

func (x *DepositOrderModel) GetTransferStatus() int64 {
	if x != nil {
		return x.TransferStatus
	}
	return 0
}

func (x *DepositOrderModel) GetNotifyTime() string {
	if x != nil {
		return x.NotifyTime
	}
	return ""
}

func (x *DepositOrderModel) GetCompleteTime() string {
	if x != nil {
		return x.CompleteTime
	}
	return ""
}

func (x *DepositOrderModel) GetAdjustAmount() int64 {
	if x != nil {
		return x.AdjustAmount
	}
	return 0
}

func (x *DepositOrderModel) GetReversalTime() string {
	if x != nil {
		return x.ReversalTime
	}
	return ""
}

func (x *DepositOrderModel) GetAdjustExchangeRate() int64 {
	if x != nil {
		return x.AdjustExchangeRate
	}
	return 0
}

func (x *DepositOrderModel) GetAdminRemark() string {
	if x != nil {
		return x.AdminRemark
	}
	return ""
}

func (x *DepositOrderModel) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

type QueryDepositOrderParam struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	MerchantAppId      string                 `protobuf:"bytes,5,opt,name=merchant_app_id,json=merchantAppId,proto3" json:"merchant_app_id,omitempty"`
	MerchantId         uint64                 `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Utr                string                 `protobuf:"bytes,7,opt,name=utr,proto3" json:"utr,omitempty"`
	OrderNo            string                 `protobuf:"bytes,8,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	RemittanceAccount  string                 `protobuf:"bytes,10,opt,name=remittance_account,json=remittanceAccount,proto3" json:"remittance_account,omitempty"`
	TransferStatus     int64                  `protobuf:"varint,11,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	Currency           string                 `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	CollectionAccount  string                 `protobuf:"bytes,13,opt,name=collection_account,json=collectionAccount,proto3" json:"collection_account,omitempty"`
	TransactionAmount  int64                  `protobuf:"varint,14,opt,name=transaction_amount,json=transactionAmount,proto3" json:"transaction_amount,omitempty"`
	ActualAmount       int64                  `protobuf:"varint,15,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	CollectionUsername string                 `protobuf:"bytes,16,opt,name=collection_username,json=collectionUsername,proto3" json:"collection_username,omitempty"`
	TransferOrderNo    string                 `protobuf:"bytes,20,opt,name=transfer_order_no,json=transferOrderNo,proto3" json:"transfer_order_no,omitempty"`
	TargetCurrency     string                 `protobuf:"bytes,21,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	DepositType        int64                  `protobuf:"varint,22,opt,name=deposit_type,json=depositType,proto3" json:"deposit_type,omitempty"`
	MerchantName       string                 `protobuf:"bytes,23,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	RemittanceName     string                 `protobuf:"bytes,24,opt,name=remittance_name,json=remittanceName,proto3" json:"remittance_name,omitempty"`
	CollectionName     string                 `protobuf:"bytes,25,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	OrderStatus        int64                  `protobuf:"varint,27,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	StartTime          string                 `protobuf:"bytes,28,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            string                 `protobuf:"bytes,29,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TimeType           int64                  `protobuf:"varint,30,opt,name=time_type,json=timeType,proto3" json:"time_type,omitempty"`
	Offset             int64                  `protobuf:"varint,31,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit              int64                  `protobuf:"varint,32,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryDepositOrderParam) Reset() {
	*x = QueryDepositOrderParam{}
	mi := &file_deposit_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDepositOrderParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDepositOrderParam) ProtoMessage() {}

func (x *QueryDepositOrderParam) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDepositOrderParam.ProtoReflect.Descriptor instead.
func (*QueryDepositOrderParam) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{1}
}

func (x *QueryDepositOrderParam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryDepositOrderParam) GetMerchantAppId() string {
	if x != nil {
		return x.MerchantAppId
	}
	return ""
}

func (x *QueryDepositOrderParam) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *QueryDepositOrderParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *QueryDepositOrderParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *QueryDepositOrderParam) GetRemittanceAccount() string {
	if x != nil {
		return x.RemittanceAccount
	}
	return ""
}

func (x *QueryDepositOrderParam) GetTransferStatus() int64 {
	if x != nil {
		return x.TransferStatus
	}
	return 0
}

func (x *QueryDepositOrderParam) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QueryDepositOrderParam) GetCollectionAccount() string {
	if x != nil {
		return x.CollectionAccount
	}
	return ""
}

func (x *QueryDepositOrderParam) GetTransactionAmount() int64 {
	if x != nil {
		return x.TransactionAmount
	}
	return 0
}

func (x *QueryDepositOrderParam) GetActualAmount() int64 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *QueryDepositOrderParam) GetCollectionUsername() string {
	if x != nil {
		return x.CollectionUsername
	}
	return ""
}

func (x *QueryDepositOrderParam) GetTransferOrderNo() string {
	if x != nil {
		return x.TransferOrderNo
	}
	return ""
}

func (x *QueryDepositOrderParam) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *QueryDepositOrderParam) GetDepositType() int64 {
	if x != nil {
		return x.DepositType
	}
	return 0
}

func (x *QueryDepositOrderParam) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *QueryDepositOrderParam) GetRemittanceName() string {
	if x != nil {
		return x.RemittanceName
	}
	return ""
}

func (x *QueryDepositOrderParam) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *QueryDepositOrderParam) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *QueryDepositOrderParam) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryDepositOrderParam) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *QueryDepositOrderParam) GetTimeType() int64 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *QueryDepositOrderParam) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryDepositOrderParam) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryDepositOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*DepositOrderModel   `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDepositOrderListResponse) Reset() {
	*x = QueryDepositOrderListResponse{}
	mi := &file_deposit_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDepositOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDepositOrderListResponse) ProtoMessage() {}

func (x *QueryDepositOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDepositOrderListResponse.ProtoReflect.Descriptor instead.
func (*QueryDepositOrderListResponse) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{2}
}

func (x *QueryDepositOrderListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryDepositOrderListResponse) GetList() []*DepositOrderModel {
	if x != nil {
		return x.List
	}
	return nil
}

type AddOrUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateResponse) Reset() {
	*x = AddOrUpdateResponse{}
	mi := &file_deposit_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateResponse) ProtoMessage() {}

func (x *AddOrUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdateResponse) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{3}
}

func (x *AddOrUpdateResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddDepositOrderParam struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RemittanceName     string                 `protobuf:"bytes,9,opt,name=remittance_name,json=remittanceName,proto3" json:"remittance_name,omitempty"`
	RemittanceAccount  string                 `protobuf:"bytes,10,opt,name=remittance_account,json=remittanceAccount,proto3" json:"remittance_account,omitempty"`
	RemittanceUsername string                 `protobuf:"bytes,11,opt,name=remittance_username,json=remittanceUsername,proto3" json:"remittance_username,omitempty"`
	RemittancePhone    string                 `protobuf:"bytes,12,opt,name=remittance_phone,json=remittancePhone,proto3" json:"remittance_phone,omitempty"`
	CollectionAccount  string                 `protobuf:"bytes,13,opt,name=collection_account,json=collectionAccount,proto3" json:"collection_account,omitempty"`
	CollectionName     string                 `protobuf:"bytes,14,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CollectionUsername string                 `protobuf:"bytes,15,opt,name=collection_username,json=collectionUsername,proto3" json:"collection_username,omitempty"`
	CollectionPhone    string                 `protobuf:"bytes,16,opt,name=collection_phone,json=collectionPhone,proto3" json:"collection_phone,omitempty"`
	TargetCurrency     string                 `protobuf:"bytes,18,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	TransferAmount     int64                  `protobuf:"varint,19,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	TransferOrderNo    string                 `protobuf:"bytes,20,opt,name=transfer_order_no,json=transferOrderNo,proto3" json:"transfer_order_no,omitempty"`
	ExchangeRate       int64                  `protobuf:"varint,21,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	ActualAmount       int64                  `protobuf:"varint,23,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	Utr                string                 `protobuf:"bytes,25,opt,name=utr,proto3" json:"utr,omitempty"`
	Remark             string                 `protobuf:"bytes,26,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderStatus        int64                  `protobuf:"varint,27,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DepositType        int64                  `protobuf:"varint,28,opt,name=deposit_type,json=depositType,proto3" json:"deposit_type,omitempty"`
	TransferStatus     int64                  `protobuf:"varint,29,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	Attachment         string                 `protobuf:"bytes,30,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddDepositOrderParam) Reset() {
	*x = AddDepositOrderParam{}
	mi := &file_deposit_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDepositOrderParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDepositOrderParam) ProtoMessage() {}

func (x *AddDepositOrderParam) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDepositOrderParam.ProtoReflect.Descriptor instead.
func (*AddDepositOrderParam) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{4}
}

func (x *AddDepositOrderParam) GetRemittanceName() string {
	if x != nil {
		return x.RemittanceName
	}
	return ""
}

func (x *AddDepositOrderParam) GetRemittanceAccount() string {
	if x != nil {
		return x.RemittanceAccount
	}
	return ""
}

func (x *AddDepositOrderParam) GetRemittanceUsername() string {
	if x != nil {
		return x.RemittanceUsername
	}
	return ""
}

func (x *AddDepositOrderParam) GetRemittancePhone() string {
	if x != nil {
		return x.RemittancePhone
	}
	return ""
}

func (x *AddDepositOrderParam) GetCollectionAccount() string {
	if x != nil {
		return x.CollectionAccount
	}
	return ""
}

func (x *AddDepositOrderParam) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *AddDepositOrderParam) GetCollectionUsername() string {
	if x != nil {
		return x.CollectionUsername
	}
	return ""
}

func (x *AddDepositOrderParam) GetCollectionPhone() string {
	if x != nil {
		return x.CollectionPhone
	}
	return ""
}

func (x *AddDepositOrderParam) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *AddDepositOrderParam) GetTransferAmount() int64 {
	if x != nil {
		return x.TransferAmount
	}
	return 0
}

func (x *AddDepositOrderParam) GetTransferOrderNo() string {
	if x != nil {
		return x.TransferOrderNo
	}
	return ""
}

func (x *AddDepositOrderParam) GetExchangeRate() int64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *AddDepositOrderParam) GetActualAmount() int64 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *AddDepositOrderParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *AddDepositOrderParam) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AddDepositOrderParam) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *AddDepositOrderParam) GetDepositType() int64 {
	if x != nil {
		return x.DepositType
	}
	return 0
}

func (x *AddDepositOrderParam) GetTransferStatus() int64 {
	if x != nil {
		return x.TransferStatus
	}
	return 0
}

func (x *AddDepositOrderParam) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

type AuditParam struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuditStatus        uint64                 `protobuf:"varint,1,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	AuditRemark        string                 `protobuf:"bytes,2,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`
	Id                 uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Attachment         string                 `protobuf:"bytes,4,opt,name=attachment,proto3" json:"attachment,omitempty"`
	Rate               int64                  `protobuf:"varint,5,opt,name=rate,proto3" json:"rate,omitempty"`
	ActualAmount       int64                  `protobuf:"varint,6,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	AdjustAmount       int64                  `protobuf:"varint,7,opt,name=adjust_amount,json=adjustAmount,proto3" json:"adjust_amount,omitempty"`
	AdjustExchangeRate int64                  `protobuf:"varint,8,opt,name=adjust_exchange_rate,json=adjustExchangeRate,proto3" json:"adjust_exchange_rate,omitempty"`
	AdminRemark        string                 `protobuf:"bytes,9,opt,name=admin_remark,json=adminRemark,proto3" json:"admin_remark,omitempty"`
	HashAttachment     string                 `protobuf:"bytes,10,opt,name=hash_attachment,json=hashAttachment,proto3" json:"hash_attachment,omitempty"`
	Utr                string                 `protobuf:"bytes,11,opt,name=utr,proto3" json:"utr,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuditParam) Reset() {
	*x = AuditParam{}
	mi := &file_deposit_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditParam) ProtoMessage() {}

func (x *AuditParam) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditParam.ProtoReflect.Descriptor instead.
func (*AuditParam) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{5}
}

func (x *AuditParam) GetAuditStatus() uint64 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *AuditParam) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

func (x *AuditParam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditParam) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *AuditParam) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *AuditParam) GetActualAmount() int64 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *AuditParam) GetAdjustAmount() int64 {
	if x != nil {
		return x.AdjustAmount
	}
	return 0
}

func (x *AuditParam) GetAdjustExchangeRate() int64 {
	if x != nil {
		return x.AdjustExchangeRate
	}
	return 0
}

func (x *AuditParam) GetAdminRemark() string {
	if x != nil {
		return x.AdminRemark
	}
	return ""
}

func (x *AuditParam) GetHashAttachment() string {
	if x != nil {
		return x.HashAttachment
	}
	return ""
}

func (x *AuditParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

type MerchantAuditParam struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuditStatus        uint64                 `protobuf:"varint,1,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	AuditRemark        string                 `protobuf:"bytes,2,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`
	Id                 uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Attachment         string                 `protobuf:"bytes,4,opt,name=attachment,proto3" json:"attachment,omitempty"`
	RemittanceName     string                 `protobuf:"bytes,9,opt,name=remittance_name,json=remittanceName,proto3" json:"remittance_name,omitempty"`
	RemittanceAccount  string                 `protobuf:"bytes,10,opt,name=remittance_account,json=remittanceAccount,proto3" json:"remittance_account,omitempty"`
	RemittanceUsername string                 `protobuf:"bytes,11,opt,name=remittance_username,json=remittanceUsername,proto3" json:"remittance_username,omitempty"`
	RemittancePhone    string                 `protobuf:"bytes,12,opt,name=remittance_phone,json=remittancePhone,proto3" json:"remittance_phone,omitempty"`
	CollectionAccount  string                 `protobuf:"bytes,13,opt,name=collection_account,json=collectionAccount,proto3" json:"collection_account,omitempty"`
	CollectionName     string                 `protobuf:"bytes,14,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CollectionUsername string                 `protobuf:"bytes,15,opt,name=collection_username,json=collectionUsername,proto3" json:"collection_username,omitempty"`
	CollectionPhone    string                 `protobuf:"bytes,16,opt,name=collection_phone,json=collectionPhone,proto3" json:"collection_phone,omitempty"`
	TransferOrderNo    string                 `protobuf:"bytes,20,opt,name=transfer_order_no,json=transferOrderNo,proto3" json:"transfer_order_no,omitempty"`
	Utr                string                 `protobuf:"bytes,25,opt,name=utr,proto3" json:"utr,omitempty"`
	Remark             string                 `protobuf:"bytes,26,opt,name=remark,proto3" json:"remark,omitempty"`
	HashAttachment     string                 `protobuf:"bytes,27,opt,name=hash_attachment,json=hashAttachment,proto3" json:"hash_attachment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MerchantAuditParam) Reset() {
	*x = MerchantAuditParam{}
	mi := &file_deposit_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAuditParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAuditParam) ProtoMessage() {}

func (x *MerchantAuditParam) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAuditParam.ProtoReflect.Descriptor instead.
func (*MerchantAuditParam) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantAuditParam) GetAuditStatus() uint64 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *MerchantAuditParam) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

func (x *MerchantAuditParam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantAuditParam) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *MerchantAuditParam) GetRemittanceName() string {
	if x != nil {
		return x.RemittanceName
	}
	return ""
}

func (x *MerchantAuditParam) GetRemittanceAccount() string {
	if x != nil {
		return x.RemittanceAccount
	}
	return ""
}

func (x *MerchantAuditParam) GetRemittanceUsername() string {
	if x != nil {
		return x.RemittanceUsername
	}
	return ""
}

func (x *MerchantAuditParam) GetRemittancePhone() string {
	if x != nil {
		return x.RemittancePhone
	}
	return ""
}

func (x *MerchantAuditParam) GetCollectionAccount() string {
	if x != nil {
		return x.CollectionAccount
	}
	return ""
}

func (x *MerchantAuditParam) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *MerchantAuditParam) GetCollectionUsername() string {
	if x != nil {
		return x.CollectionUsername
	}
	return ""
}

func (x *MerchantAuditParam) GetCollectionPhone() string {
	if x != nil {
		return x.CollectionPhone
	}
	return ""
}

func (x *MerchantAuditParam) GetTransferOrderNo() string {
	if x != nil {
		return x.TransferOrderNo
	}
	return ""
}

func (x *MerchantAuditParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *MerchantAuditParam) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *MerchantAuditParam) GetHashAttachment() string {
	if x != nil {
		return x.HashAttachment
	}
	return ""
}

type GetDepositOrderAuditProcessNodeListQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     uint64                 `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DepositOrderId uint64                 `protobuf:"varint,2,opt,name=deposit_order_id,json=depositOrderId,proto3" json:"deposit_order_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDepositOrderAuditProcessNodeListQuery) Reset() {
	*x = GetDepositOrderAuditProcessNodeListQuery{}
	mi := &file_deposit_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositOrderAuditProcessNodeListQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositOrderAuditProcessNodeListQuery) ProtoMessage() {}

func (x *GetDepositOrderAuditProcessNodeListQuery) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositOrderAuditProcessNodeListQuery.ProtoReflect.Descriptor instead.
func (*GetDepositOrderAuditProcessNodeListQuery) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepositOrderAuditProcessNodeListQuery) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GetDepositOrderAuditProcessNodeListQuery) GetDepositOrderId() uint64 {
	if x != nil {
		return x.DepositOrderId
	}
	return 0
}

type GetAuditProcessNodeListResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	List          []*GetOrderAuditProcessNodeData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditProcessNodeListResponse) Reset() {
	*x = GetAuditProcessNodeListResponse{}
	mi := &file_deposit_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditProcessNodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditProcessNodeListResponse) ProtoMessage() {}

func (x *GetAuditProcessNodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditProcessNodeListResponse.ProtoReflect.Descriptor instead.
func (*GetAuditProcessNodeListResponse) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetAuditProcessNodeListResponse) GetList() []*GetOrderAuditProcessNodeData {
	if x != nil {
		return x.List
	}
	return nil
}

type GetOrderAuditProcessNodeData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuditStatus    uint64                 `protobuf:"varint,3,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	AuditRemark    string                 `protobuf:"bytes,4,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`
	DepositOrderId uint64                 `protobuf:"varint,5,opt,name=deposit_order_id,json=depositOrderId,proto3" json:"deposit_order_id,omitempty"`
	AuditTime      string                 `protobuf:"bytes,6,opt,name=audit_time,json=auditTime,proto3" json:"audit_time,omitempty"`
	Attachment     string                 `protobuf:"bytes,7,opt,name=attachment,proto3" json:"attachment,omitempty"`
	ProcessNode    uint64                 `protobuf:"varint,8,opt,name=process_node,json=processNode,proto3" json:"process_node,omitempty"`
	UserName       string                 `protobuf:"bytes,10,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	CreateTime     string                 `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderAuditProcessNodeData) Reset() {
	*x = GetOrderAuditProcessNodeData{}
	mi := &file_deposit_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderAuditProcessNodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderAuditProcessNodeData) ProtoMessage() {}

func (x *GetOrderAuditProcessNodeData) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderAuditProcessNodeData.ProtoReflect.Descriptor instead.
func (*GetOrderAuditProcessNodeData) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderAuditProcessNodeData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderAuditProcessNodeData) GetAuditStatus() uint64 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *GetOrderAuditProcessNodeData) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

func (x *GetOrderAuditProcessNodeData) GetDepositOrderId() uint64 {
	if x != nil {
		return x.DepositOrderId
	}
	return 0
}

func (x *GetOrderAuditProcessNodeData) GetAuditTime() string {
	if x != nil {
		return x.AuditTime
	}
	return ""
}

func (x *GetOrderAuditProcessNodeData) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *GetOrderAuditProcessNodeData) GetProcessNode() uint64 {
	if x != nil {
		return x.ProcessNode
	}
	return 0
}

func (x *GetOrderAuditProcessNodeData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetOrderAuditProcessNodeData) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type UpdateDepositOrderRateParam struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rate              int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	ActualAmount      int64                  `protobuf:"varint,3,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	RemittanceAccount string                 `protobuf:"bytes,4,opt,name=remittance_account,json=remittanceAccount,proto3" json:"remittance_account,omitempty"`
	CollectionAccount string                 `protobuf:"bytes,5,opt,name=collection_account,json=collectionAccount,proto3" json:"collection_account,omitempty"`
	TransferOrderNo   string                 `protobuf:"bytes,6,opt,name=transfer_order_no,json=transferOrderNo,proto3" json:"transfer_order_no,omitempty"`
	Utr               string                 `protobuf:"bytes,7,opt,name=utr,proto3" json:"utr,omitempty"`
	AdminRemark       string                 `protobuf:"bytes,8,opt,name=admin_remark,json=adminRemark,proto3" json:"admin_remark,omitempty"`
	Attachment        string                 `protobuf:"bytes,9,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDepositOrderRateParam) Reset() {
	*x = UpdateDepositOrderRateParam{}
	mi := &file_deposit_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepositOrderRateParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepositOrderRateParam) ProtoMessage() {}

func (x *UpdateDepositOrderRateParam) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepositOrderRateParam.ProtoReflect.Descriptor instead.
func (*UpdateDepositOrderRateParam) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDepositOrderRateParam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDepositOrderRateParam) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *UpdateDepositOrderRateParam) GetActualAmount() int64 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *UpdateDepositOrderRateParam) GetRemittanceAccount() string {
	if x != nil {
		return x.RemittanceAccount
	}
	return ""
}

func (x *UpdateDepositOrderRateParam) GetCollectionAccount() string {
	if x != nil {
		return x.CollectionAccount
	}
	return ""
}

func (x *UpdateDepositOrderRateParam) GetTransferOrderNo() string {
	if x != nil {
		return x.TransferOrderNo
	}
	return ""
}

func (x *UpdateDepositOrderRateParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *UpdateDepositOrderRateParam) GetAdminRemark() string {
	if x != nil {
		return x.AdminRemark
	}
	return ""
}

func (x *UpdateDepositOrderRateParam) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

type DepositOrderReversalParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositOrderReversalParam) Reset() {
	*x = DepositOrderReversalParam{}
	mi := &file_deposit_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositOrderReversalParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOrderReversalParam) ProtoMessage() {}

func (x *DepositOrderReversalParam) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOrderReversalParam.ProtoReflect.Descriptor instead.
func (*DepositOrderReversalParam) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{11}
}

func (x *DepositOrderReversalParam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DepositOrderSummaryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SuccessVolume  string                 `protobuf:"bytes,1,opt,name=success_volume,json=successVolume,proto3" json:"success_volume,omitempty"`
	SuccessAmt     string                 `protobuf:"bytes,2,opt,name=success_amt,json=successAmt,proto3" json:"success_amt,omitempty"`
	PendingVolume  string                 `protobuf:"bytes,3,opt,name=pending_volume,json=pendingVolume,proto3" json:"pending_volume,omitempty"`
	PendingAmt     string                 `protobuf:"bytes,4,opt,name=pending_amt,json=pendingAmt,proto3" json:"pending_amt,omitempty"`
	FailureVolume  string                 `protobuf:"bytes,5,opt,name=failure_volume,json=failureVolume,proto3" json:"failure_volume,omitempty"`
	FailureAmt     string                 `protobuf:"bytes,6,opt,name=failure_amt,json=failureAmt,proto3" json:"failure_amt,omitempty"`
	ReversalVolume string                 `protobuf:"bytes,7,opt,name=reversal_volume,json=reversalVolume,proto3" json:"reversal_volume,omitempty"`
	ReversalAmt    string                 `protobuf:"bytes,8,opt,name=reversal_amt,json=reversalAmt,proto3" json:"reversal_amt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepositOrderSummaryResponse) Reset() {
	*x = DepositOrderSummaryResponse{}
	mi := &file_deposit_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositOrderSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOrderSummaryResponse) ProtoMessage() {}

func (x *DepositOrderSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOrderSummaryResponse.ProtoReflect.Descriptor instead.
func (*DepositOrderSummaryResponse) Descriptor() ([]byte, []int) {
	return file_deposit_order_proto_rawDescGZIP(), []int{12}
}

func (x *DepositOrderSummaryResponse) GetSuccessVolume() string {
	if x != nil {
		return x.SuccessVolume
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetSuccessAmt() string {
	if x != nil {
		return x.SuccessAmt
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetPendingVolume() string {
	if x != nil {
		return x.PendingVolume
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetPendingAmt() string {
	if x != nil {
		return x.PendingAmt
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetFailureVolume() string {
	if x != nil {
		return x.FailureVolume
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetFailureAmt() string {
	if x != nil {
		return x.FailureAmt
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetReversalVolume() string {
	if x != nil {
		return x.ReversalVolume
	}
	return ""
}

func (x *DepositOrderSummaryResponse) GetReversalAmt() string {
	if x != nil {
		return x.ReversalAmt
	}
	return ""
}

var File_deposit_order_proto protoreflect.FileDescriptor

const file_deposit_order_proto_rawDesc = "" +
	"\n" +
	"\x13deposit_order.proto\x12\x02pb\"\x97\n" +
	"\n" +
	"\x11DepositOrderModel\x12\x1f\n" +
	"\vcreate_time\x18\x01 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vcreate_unix\x18\x02 \x01(\x03R\n" +
	"createUnix\x12\x1f\n" +
	"\vupdate_time\x18\x03 \x01(\tR\n" +
	"updateTime\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\x12%\n" +
	"\x0emerchant_appid\x18\x05 \x01(\tR\rmerchantAppid\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x04R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\a \x01(\tR\fmerchantName\x12\x19\n" +
	"\border_no\x18\b \x01(\tR\aorderNo\x12'\n" +
	"\x0fremittance_name\x18\t \x01(\tR\x0eremittanceName\x12-\n" +
	"\x12remittance_account\x18\n" +
	" \x01(\tR\x11remittanceAccount\x12/\n" +
	"\x13remittance_username\x18\v \x01(\tR\x12remittanceUsername\x12)\n" +
	"\x10remittance_phone\x18\f \x01(\tR\x0fremittancePhone\x12-\n" +
	"\x12collection_account\x18\r \x01(\tR\x11collectionAccount\x12'\n" +
	"\x0fcollection_name\x18\x0e \x01(\tR\x0ecollectionName\x12/\n" +
	"\x13collection_username\x18\x0f \x01(\tR\x12collectionUsername\x12)\n" +
	"\x10collection_phone\x18\x10 \x01(\tR\x0fcollectionPhone\x12\x1a\n" +
	"\bcurrency\x18\x11 \x01(\tR\bcurrency\x12'\n" +
	"\x0ftarget_currency\x18\x12 \x01(\tR\x0etargetCurrency\x12'\n" +
	"\x0ftransfer_amount\x18\x13 \x01(\x03R\x0etransferAmount\x12*\n" +
	"\x11transfer_order_no\x18\x14 \x01(\tR\x0ftransferOrderNo\x12#\n" +
	"\rexchange_rate\x18\x15 \x01(\x03R\fexchangeRate\x12#\n" +
	"\ractual_amount\x18\x17 \x01(\x03R\factualAmount\x12\x10\n" +
	"\x03utr\x18\x19 \x01(\tR\x03utr\x12\x16\n" +
	"\x06remark\x18\x1a \x01(\tR\x06remark\x12!\n" +
	"\forder_status\x18\x1b \x01(\x03R\vorderStatus\x12!\n" +
	"\fdeposit_type\x18\x1c \x01(\x03R\vdepositType\x12\x1d\n" +
	"\n" +
	"audit_time\x18\x1d \x01(\tR\tauditTime\x12'\n" +
	"\x0ftransfer_status\x18\x1e \x01(\x03R\x0etransferStatus\x12\x1f\n" +
	"\vnotify_time\x18\x1f \x01(\tR\n" +
	"notifyTime\x12#\n" +
	"\rcomplete_time\x18  \x01(\tR\fcompleteTime\x12#\n" +
	"\radjust_amount\x18! \x01(\x03R\fadjustAmount\x12#\n" +
	"\rreversal_time\x18\" \x01(\tR\freversalTime\x120\n" +
	"\x14adjust_exchange_rate\x18# \x01(\x03R\x12adjustExchangeRate\x12!\n" +
	"\fadmin_remark\x18$ \x01(\tR\vadminRemark\x12\x1e\n" +
	"\n" +
	"attachment\x18% \x01(\tR\n" +
	"attachment\"\xdd\x06\n" +
	"\x16QueryDepositOrderParam\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\x12&\n" +
	"\x0fmerchant_app_id\x18\x05 \x01(\tR\rmerchantAppId\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x04R\n" +
	"merchantId\x12\x10\n" +
	"\x03utr\x18\a \x01(\tR\x03utr\x12\x19\n" +
	"\border_no\x18\b \x01(\tR\aorderNo\x12-\n" +
	"\x12remittance_account\x18\n" +
	" \x01(\tR\x11remittanceAccount\x12'\n" +
	"\x0ftransfer_status\x18\v \x01(\x03R\x0etransferStatus\x12\x1a\n" +
	"\bcurrency\x18\f \x01(\tR\bcurrency\x12-\n" +
	"\x12collection_account\x18\r \x01(\tR\x11collectionAccount\x12-\n" +
	"\x12transaction_amount\x18\x0e \x01(\x03R\x11transactionAmount\x12#\n" +
	"\ractual_amount\x18\x0f \x01(\x03R\factualAmount\x12/\n" +
	"\x13collection_username\x18\x10 \x01(\tR\x12collectionUsername\x12*\n" +
	"\x11transfer_order_no\x18\x14 \x01(\tR\x0ftransferOrderNo\x12'\n" +
	"\x0ftarget_currency\x18\x15 \x01(\tR\x0etargetCurrency\x12!\n" +
	"\fdeposit_type\x18\x16 \x01(\x03R\vdepositType\x12#\n" +
	"\rmerchant_name\x18\x17 \x01(\tR\fmerchantName\x12'\n" +
	"\x0fremittance_name\x18\x18 \x01(\tR\x0eremittanceName\x12'\n" +
	"\x0fcollection_name\x18\x19 \x01(\tR\x0ecollectionName\x12!\n" +
	"\forder_status\x18\x1b \x01(\x03R\vorderStatus\x12\x1d\n" +
	"\n" +
	"start_time\x18\x1c \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x1d \x01(\tR\aendTime\x12\x1b\n" +
	"\ttime_type\x18\x1e \x01(\x03R\btimeType\x12\x16\n" +
	"\x06offset\x18\x1f \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18  \x01(\x03R\x05limit\"`\n" +
	"\x1dQueryDepositOrderListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.pb.DepositOrderModelR\x04list\"%\n" +
	"\x13AddOrUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\"\xff\x05\n" +
	"\x14AddDepositOrderParam\x12'\n" +
	"\x0fremittance_name\x18\t \x01(\tR\x0eremittanceName\x12-\n" +
	"\x12remittance_account\x18\n" +
	" \x01(\tR\x11remittanceAccount\x12/\n" +
	"\x13remittance_username\x18\v \x01(\tR\x12remittanceUsername\x12)\n" +
	"\x10remittance_phone\x18\f \x01(\tR\x0fremittancePhone\x12-\n" +
	"\x12collection_account\x18\r \x01(\tR\x11collectionAccount\x12'\n" +
	"\x0fcollection_name\x18\x0e \x01(\tR\x0ecollectionName\x12/\n" +
	"\x13collection_username\x18\x0f \x01(\tR\x12collectionUsername\x12)\n" +
	"\x10collection_phone\x18\x10 \x01(\tR\x0fcollectionPhone\x12'\n" +
	"\x0ftarget_currency\x18\x12 \x01(\tR\x0etargetCurrency\x12'\n" +
	"\x0ftransfer_amount\x18\x13 \x01(\x03R\x0etransferAmount\x12*\n" +
	"\x11transfer_order_no\x18\x14 \x01(\tR\x0ftransferOrderNo\x12#\n" +
	"\rexchange_rate\x18\x15 \x01(\x03R\fexchangeRate\x12#\n" +
	"\ractual_amount\x18\x17 \x01(\x03R\factualAmount\x12\x10\n" +
	"\x03utr\x18\x19 \x01(\tR\x03utr\x12\x16\n" +
	"\x06remark\x18\x1a \x01(\tR\x06remark\x12!\n" +
	"\forder_status\x18\x1b \x01(\x03R\vorderStatus\x12!\n" +
	"\fdeposit_type\x18\x1c \x01(\x03R\vdepositType\x12'\n" +
	"\x0ftransfer_status\x18\x1d \x01(\x03R\x0etransferStatus\x12\x1e\n" +
	"\n" +
	"attachment\x18\x1e \x01(\tR\n" +
	"attachment\"\xf0\x02\n" +
	"\n" +
	"AuditParam\x12!\n" +
	"\faudit_status\x18\x01 \x01(\x04R\vauditStatus\x12!\n" +
	"\faudit_remark\x18\x02 \x01(\tR\vauditRemark\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\x12\x1e\n" +
	"\n" +
	"attachment\x18\x04 \x01(\tR\n" +
	"attachment\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x03R\x04rate\x12#\n" +
	"\ractual_amount\x18\x06 \x01(\x03R\factualAmount\x12#\n" +
	"\radjust_amount\x18\a \x01(\x03R\fadjustAmount\x120\n" +
	"\x14adjust_exchange_rate\x18\b \x01(\x03R\x12adjustExchangeRate\x12!\n" +
	"\fadmin_remark\x18\t \x01(\tR\vadminRemark\x12'\n" +
	"\x0fhash_attachment\x18\n" +
	" \x01(\tR\x0ehashAttachment\x12\x10\n" +
	"\x03utr\x18\v \x01(\tR\x03utr\"\xf1\x04\n" +
	"\x12MerchantAuditParam\x12!\n" +
	"\faudit_status\x18\x01 \x01(\x04R\vauditStatus\x12!\n" +
	"\faudit_remark\x18\x02 \x01(\tR\vauditRemark\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\x12\x1e\n" +
	"\n" +
	"attachment\x18\x04 \x01(\tR\n" +
	"attachment\x12'\n" +
	"\x0fremittance_name\x18\t \x01(\tR\x0eremittanceName\x12-\n" +
	"\x12remittance_account\x18\n" +
	" \x01(\tR\x11remittanceAccount\x12/\n" +
	"\x13remittance_username\x18\v \x01(\tR\x12remittanceUsername\x12)\n" +
	"\x10remittance_phone\x18\f \x01(\tR\x0fremittancePhone\x12-\n" +
	"\x12collection_account\x18\r \x01(\tR\x11collectionAccount\x12'\n" +
	"\x0fcollection_name\x18\x0e \x01(\tR\x0ecollectionName\x12/\n" +
	"\x13collection_username\x18\x0f \x01(\tR\x12collectionUsername\x12)\n" +
	"\x10collection_phone\x18\x10 \x01(\tR\x0fcollectionPhone\x12*\n" +
	"\x11transfer_order_no\x18\x14 \x01(\tR\x0ftransferOrderNo\x12\x10\n" +
	"\x03utr\x18\x19 \x01(\tR\x03utr\x12\x16\n" +
	"\x06remark\x18\x1a \x01(\tR\x06remark\x12'\n" +
	"\x0fhash_attachment\x18\x1b \x01(\tR\x0ehashAttachment\"u\n" +
	"(GetDepositOrderAuditProcessNodeListQuery\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x04R\n" +
	"merchantId\x12(\n" +
	"\x10deposit_order_id\x18\x02 \x01(\x04R\x0edepositOrderId\"W\n" +
	"\x1fGetAuditProcessNodeListResponse\x124\n" +
	"\x04list\x18\x01 \x03(\v2 .pb.GetOrderAuditProcessNodeDataR\x04list\"\xbe\x02\n" +
	"\x1cGetOrderAuditProcessNodeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\faudit_status\x18\x03 \x01(\x04R\vauditStatus\x12!\n" +
	"\faudit_remark\x18\x04 \x01(\tR\vauditRemark\x12(\n" +
	"\x10deposit_order_id\x18\x05 \x01(\x04R\x0edepositOrderId\x12\x1d\n" +
	"\n" +
	"audit_time\x18\x06 \x01(\tR\tauditTime\x12\x1e\n" +
	"\n" +
	"attachment\x18\a \x01(\tR\n" +
	"attachment\x12!\n" +
	"\fprocess_node\x18\b \x01(\x04R\vprocessNode\x12\x1b\n" +
	"\tuser_name\x18\n" +
	" \x01(\tR\buserName\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\tR\n" +
	"createTime\"\xc5\x02\n" +
	"\x1bUpdateDepositOrderRateParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rate\x12#\n" +
	"\ractual_amount\x18\x03 \x01(\x03R\factualAmount\x12-\n" +
	"\x12remittance_account\x18\x04 \x01(\tR\x11remittanceAccount\x12-\n" +
	"\x12collection_account\x18\x05 \x01(\tR\x11collectionAccount\x12*\n" +
	"\x11transfer_order_no\x18\x06 \x01(\tR\x0ftransferOrderNo\x12\x10\n" +
	"\x03utr\x18\a \x01(\tR\x03utr\x12!\n" +
	"\fadmin_remark\x18\b \x01(\tR\vadminRemark\x12\x1e\n" +
	"\n" +
	"attachment\x18\t \x01(\tR\n" +
	"attachment\"+\n" +
	"\x19DepositOrderReversalParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xc1\x02\n" +
	"\x1bDepositOrderSummaryResponse\x12%\n" +
	"\x0esuccess_volume\x18\x01 \x01(\tR\rsuccessVolume\x12\x1f\n" +
	"\vsuccess_amt\x18\x02 \x01(\tR\n" +
	"successAmt\x12%\n" +
	"\x0epending_volume\x18\x03 \x01(\tR\rpendingVolume\x12\x1f\n" +
	"\vpending_amt\x18\x04 \x01(\tR\n" +
	"pendingAmt\x12%\n" +
	"\x0efailure_volume\x18\x05 \x01(\tR\rfailureVolume\x12\x1f\n" +
	"\vfailure_amt\x18\x06 \x01(\tR\n" +
	"failureAmt\x12'\n" +
	"\x0freversal_volume\x18\a \x01(\tR\x0ereversalVolume\x12!\n" +
	"\freversal_amt\x18\b \x01(\tR\vreversalAmt2\x90\x05\n" +
	"\fDepositOrder\x12D\n" +
	"\x0fAddDepositOrder\x12\x18.pb.AddDepositOrderParam\x1a\x17.pb.AddOrUpdateResponse\x12V\n" +
	"\x15QueryDepositOrderList\x12\x1a.pb.QueryDepositOrderParam\x1a!.pb.QueryDepositOrderListResponse\x12@\n" +
	"\rMerchantAudit\x12\x16.pb.MerchantAuditParam\x1a\x17.pb.AddOrUpdateResponse\x125\n" +
	"\n" +
	"AdminAudit\x12\x0e.pb.AuditParam\x1a\x17.pb.AddOrUpdateResponse\x12q\n" +
	"\x1cGetOrderAuditProcessNodeList\x12,.pb.GetDepositOrderAuditProcessNodeListQuery\x1a#.pb.GetAuditProcessNodeListResponse\x12R\n" +
	"\x16UpdateDepositOrderRate\x12\x1f.pb.UpdateDepositOrderRateParam\x1a\x17.pb.AddOrUpdateResponse\x12N\n" +
	"\x14DepositOrderReversal\x12\x1d.pb.DepositOrderReversalParam\x1a\x17.pb.AddOrUpdateResponse\x12R\n" +
	"\x13DepositOrderSummary\x12\x1a.pb.QueryDepositOrderParam\x1a\x1f.pb.DepositOrderSummaryResponseB%Z#base/rpc_api/admin/pb/deposit_orderb\x06proto3"

var (
	file_deposit_order_proto_rawDescOnce sync.Once
	file_deposit_order_proto_rawDescData []byte
)

func file_deposit_order_proto_rawDescGZIP() []byte {
	file_deposit_order_proto_rawDescOnce.Do(func() {
		file_deposit_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deposit_order_proto_rawDesc), len(file_deposit_order_proto_rawDesc)))
	})
	return file_deposit_order_proto_rawDescData
}

var file_deposit_order_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_deposit_order_proto_goTypes = []any{
	(*DepositOrderModel)(nil),                        // 0: pb.DepositOrderModel
	(*QueryDepositOrderParam)(nil),                   // 1: pb.QueryDepositOrderParam
	(*QueryDepositOrderListResponse)(nil),            // 2: pb.QueryDepositOrderListResponse
	(*AddOrUpdateResponse)(nil),                      // 3: pb.AddOrUpdateResponse
	(*AddDepositOrderParam)(nil),                     // 4: pb.AddDepositOrderParam
	(*AuditParam)(nil),                               // 5: pb.AuditParam
	(*MerchantAuditParam)(nil),                       // 6: pb.MerchantAuditParam
	(*GetDepositOrderAuditProcessNodeListQuery)(nil), // 7: pb.GetDepositOrderAuditProcessNodeListQuery
	(*GetAuditProcessNodeListResponse)(nil),          // 8: pb.GetAuditProcessNodeListResponse
	(*GetOrderAuditProcessNodeData)(nil),             // 9: pb.GetOrderAuditProcessNodeData
	(*UpdateDepositOrderRateParam)(nil),              // 10: pb.UpdateDepositOrderRateParam
	(*DepositOrderReversalParam)(nil),                // 11: pb.DepositOrderReversalParam
	(*DepositOrderSummaryResponse)(nil),              // 12: pb.DepositOrderSummaryResponse
}
var file_deposit_order_proto_depIdxs = []int32{
	0,  // 0: pb.QueryDepositOrderListResponse.list:type_name -> pb.DepositOrderModel
	9,  // 1: pb.GetAuditProcessNodeListResponse.list:type_name -> pb.GetOrderAuditProcessNodeData
	4,  // 2: pb.DepositOrder.AddDepositOrder:input_type -> pb.AddDepositOrderParam
	1,  // 3: pb.DepositOrder.QueryDepositOrderList:input_type -> pb.QueryDepositOrderParam
	6,  // 4: pb.DepositOrder.MerchantAudit:input_type -> pb.MerchantAuditParam
	5,  // 5: pb.DepositOrder.AdminAudit:input_type -> pb.AuditParam
	7,  // 6: pb.DepositOrder.GetOrderAuditProcessNodeList:input_type -> pb.GetDepositOrderAuditProcessNodeListQuery
	10, // 7: pb.DepositOrder.UpdateDepositOrderRate:input_type -> pb.UpdateDepositOrderRateParam
	11, // 8: pb.DepositOrder.DepositOrderReversal:input_type -> pb.DepositOrderReversalParam
	1,  // 9: pb.DepositOrder.DepositOrderSummary:input_type -> pb.QueryDepositOrderParam
	3,  // 10: pb.DepositOrder.AddDepositOrder:output_type -> pb.AddOrUpdateResponse
	2,  // 11: pb.DepositOrder.QueryDepositOrderList:output_type -> pb.QueryDepositOrderListResponse
	3,  // 12: pb.DepositOrder.MerchantAudit:output_type -> pb.AddOrUpdateResponse
	3,  // 13: pb.DepositOrder.AdminAudit:output_type -> pb.AddOrUpdateResponse
	8,  // 14: pb.DepositOrder.GetOrderAuditProcessNodeList:output_type -> pb.GetAuditProcessNodeListResponse
	3,  // 15: pb.DepositOrder.UpdateDepositOrderRate:output_type -> pb.AddOrUpdateResponse
	3,  // 16: pb.DepositOrder.DepositOrderReversal:output_type -> pb.AddOrUpdateResponse
	12, // 17: pb.DepositOrder.DepositOrderSummary:output_type -> pb.DepositOrderSummaryResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_deposit_order_proto_init() }
func file_deposit_order_proto_init() {
	if File_deposit_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deposit_order_proto_rawDesc), len(file_deposit_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deposit_order_proto_goTypes,
		DependencyIndexes: file_deposit_order_proto_depIdxs,
		MessageInfos:      file_deposit_order_proto_msgTypes,
	}.Build()
	File_deposit_order_proto = out.File
	file_deposit_order_proto_goTypes = nil
	file_deposit_order_proto_depIdxs = nil
}
