// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: notify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// merchant notify req
type MerchantNotifyReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order msg
	Msg string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	// 1:success，2:failed required
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// payment type required, 1:payin, 2:payout, 3:settlement
	PaymentType int32 `protobuf:"varint,7,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	// notify url required
	NotifyUrl      string `protobuf:"bytes,8,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Currency       string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionUtr string `protobuf:"bytes,10,opt,name=transaction_utr,json=transactionUtr,proto3" json:"transaction_utr,omitempty"`
	MerchantId     int64  `protobuf:"varint,11,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantAppid  string `protobuf:"bytes,12,opt,name=merchant_appid,json=merchantAppid,proto3" json:"merchant_appid,omitempty"`
	// Merchant Transaction ID (商户交易ID)
	MerchantTxnId string `protobuf:"bytes,16,opt,name=merchant_txn_id,json=merchantTxnId,proto3" json:"merchant_txn_id,omitempty"`
	// Platform Transaction ID (平台方ID)
	TxnId string `protobuf:"bytes,17,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	// Requested Amount (请求金额)
	RequestAmount int64 `protobuf:"varint,18,opt,name=request_amount,json=requestAmount,proto3" json:"request_amount,omitempty"`
	// Actual Transaction Amount (实际交易金额)
	PayAmount int64 `protobuf:"varint,19,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	// Fee Amount (费率)
	FeeAmount int64 `protobuf:"varint,20,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	// Bank Transaction ID (银行交易ID)
	BankTxnId string `protobuf:"bytes,21,opt,name=bank_txn_id,json=bankTxnId,proto3" json:"bank_txn_id,omitempty"`
	// Pay Type (支付类型)
	PayType int64 `protobuf:"varint,22,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	// Request Time (请求时间)
	RequestTime string `protobuf:"bytes,23,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	// Transaction Time (交易时间)
	PayTime string `protobuf:"bytes,24,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	// Passthrough Parameter (透传参数)
	ExtraData string `protobuf:"bytes,25,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	// Specific/Optional Fields
	// Account Type (账户类型)
	AccountType string `protobuf:"bytes,27,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	// Bank Name (银行名称) - Optional
	BankName string `protobuf:"bytes,28,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	// Bank Code (银行编码) - Optional
	BankCode string `protobuf:"bytes,29,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	// Account Holder Name (户主名字) - Optional
	HolderName string `protobuf:"bytes,30,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty"`
	// Account Holder Account (户主账户) - Optional
	HolderAccount string `protobuf:"bytes,31,opt,name=holder_account,json=holderAccount,proto3" json:"holder_account,omitempty"`
	// Account Holder Phone (户主手机) - Optional
	HolderPhone string `protobuf:"bytes,32,opt,name=holder_phone,json=holderPhone,proto3" json:"holder_phone,omitempty"`
	// Account Holder Email (户主邮箱) - Optional
	HolderEmail string `protobuf:"bytes,33,opt,name=holder_email,json=holderEmail,proto3" json:"holder_email,omitempty"`
	// Account Holder Token (户主通证) - Optional
	HolderToken   string `protobuf:"bytes,34,opt,name=holder_token,json=holderToken,proto3" json:"holder_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantNotifyReq) Reset() {
	*x = MerchantNotifyReq{}
	mi := &file_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantNotifyReq) ProtoMessage() {}

func (x *MerchantNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantNotifyReq.ProtoReflect.Descriptor instead.
func (*MerchantNotifyReq) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantNotifyReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MerchantNotifyReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MerchantNotifyReq) GetPaymentType() int32 {
	if x != nil {
		return x.PaymentType
	}
	return 0
}

func (x *MerchantNotifyReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *MerchantNotifyReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MerchantNotifyReq) GetTransactionUtr() string {
	if x != nil {
		return x.TransactionUtr
	}
	return ""
}

func (x *MerchantNotifyReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantNotifyReq) GetMerchantAppid() string {
	if x != nil {
		return x.MerchantAppid
	}
	return ""
}

func (x *MerchantNotifyReq) GetMerchantTxnId() string {
	if x != nil {
		return x.MerchantTxnId
	}
	return ""
}

func (x *MerchantNotifyReq) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *MerchantNotifyReq) GetRequestAmount() int64 {
	if x != nil {
		return x.RequestAmount
	}
	return 0
}

func (x *MerchantNotifyReq) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *MerchantNotifyReq) GetFeeAmount() int64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *MerchantNotifyReq) GetBankTxnId() string {
	if x != nil {
		return x.BankTxnId
	}
	return ""
}

func (x *MerchantNotifyReq) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *MerchantNotifyReq) GetRequestTime() string {
	if x != nil {
		return x.RequestTime
	}
	return ""
}

func (x *MerchantNotifyReq) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *MerchantNotifyReq) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *MerchantNotifyReq) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *MerchantNotifyReq) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *MerchantNotifyReq) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *MerchantNotifyReq) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}

func (x *MerchantNotifyReq) GetHolderAccount() string {
	if x != nil {
		return x.HolderAccount
	}
	return ""
}

func (x *MerchantNotifyReq) GetHolderPhone() string {
	if x != nil {
		return x.HolderPhone
	}
	return ""
}

func (x *MerchantNotifyReq) GetHolderEmail() string {
	if x != nil {
		return x.HolderEmail
	}
	return ""
}

func (x *MerchantNotifyReq) GetHolderToken() string {
	if x != nil {
		return x.HolderToken
	}
	return ""
}

type MerchantNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantNotifyResp) Reset() {
	*x = MerchantNotifyResp{}
	mi := &file_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantNotifyResp) ProtoMessage() {}

func (x *MerchantNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantNotifyResp.ProtoReflect.Descriptor instead.
func (*MerchantNotifyResp) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantNotifyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_notify_proto protoreflect.FileDescriptor

const file_notify_proto_rawDesc = "" +
	"\n" +
	"\fnotify.proto\x12\x02pb\"\xd6\x06\n" +
	"\x11MerchantNotifyReq\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12!\n" +
	"\fpayment_type\x18\a \x01(\x05R\vpaymentType\x12\x1d\n" +
	"\n" +
	"notify_url\x18\b \x01(\tR\tnotifyUrl\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12'\n" +
	"\x0ftransaction_utr\x18\n" +
	" \x01(\tR\x0etransactionUtr\x12\x1f\n" +
	"\vmerchant_id\x18\v \x01(\x03R\n" +
	"merchantId\x12%\n" +
	"\x0emerchant_appid\x18\f \x01(\tR\rmerchantAppid\x12&\n" +
	"\x0fmerchant_txn_id\x18\x10 \x01(\tR\rmerchantTxnId\x12\x15\n" +
	"\x06txn_id\x18\x11 \x01(\tR\x05txnId\x12%\n" +
	"\x0erequest_amount\x18\x12 \x01(\x03R\rrequestAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x13 \x01(\x03R\tpayAmount\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\x14 \x01(\x03R\tfeeAmount\x12\x1e\n" +
	"\vbank_txn_id\x18\x15 \x01(\tR\tbankTxnId\x12\x19\n" +
	"\bpay_type\x18\x16 \x01(\x03R\apayType\x12!\n" +
	"\frequest_time\x18\x17 \x01(\tR\vrequestTime\x12\x19\n" +
	"\bpay_time\x18\x18 \x01(\tR\apayTime\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x19 \x01(\tR\textraData\x12!\n" +
	"\faccount_type\x18\x1b \x01(\tR\vaccountType\x12\x1b\n" +
	"\tbank_name\x18\x1c \x01(\tR\bbankName\x12\x1b\n" +
	"\tbank_code\x18\x1d \x01(\tR\bbankCode\x12\x1f\n" +
	"\vholder_name\x18\x1e \x01(\tR\n" +
	"holderName\x12%\n" +
	"\x0eholder_account\x18\x1f \x01(\tR\rholderAccount\x12!\n" +
	"\fholder_phone\x18  \x01(\tR\vholderPhone\x12!\n" +
	"\fholder_email\x18! \x01(\tR\vholderEmail\x12!\n" +
	"\fholder_token\x18\" \x01(\tR\vholderToken\"&\n" +
	"\x12MerchantNotifyResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2I\n" +
	"\x06Notify\x12?\n" +
	"\x0eMerchantNotify\x12\x15.pb.MerchantNotifyReq\x1a\x16.pb.MerchantNotifyRespB\x18Z\x16base/rpc_api/notify/pbb\x06proto3"

var (
	file_notify_proto_rawDescOnce sync.Once
	file_notify_proto_rawDescData []byte
)

func file_notify_proto_rawDescGZIP() []byte {
	file_notify_proto_rawDescOnce.Do(func() {
		file_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_proto_rawDesc), len(file_notify_proto_rawDesc)))
	})
	return file_notify_proto_rawDescData
}

var file_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notify_proto_goTypes = []any{
	(*MerchantNotifyReq)(nil),  // 0: pb.MerchantNotifyReq
	(*MerchantNotifyResp)(nil), // 1: pb.MerchantNotifyResp
}
var file_notify_proto_depIdxs = []int32{
	0, // 0: pb.Notify.MerchantNotify:input_type -> pb.MerchantNotifyReq
	1, // 1: pb.Notify.MerchantNotify:output_type -> pb.MerchantNotifyResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_proto_init() }
func file_notify_proto_init() {
	if File_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_proto_rawDesc), len(file_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_proto_goTypes,
		DependencyIndexes: file_notify_proto_depIdxs,
		MessageInfos:      file_notify_proto_msgTypes,
	}.Build()
	File_notify_proto = out.File
	file_notify_proto_goTypes = nil
	file_notify_proto_depIdxs = nil
}
