// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: refund_order.proto

package refund_order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RefundOrder_QueryRefundOrderList_FullMethodName    = "/pb.RefundOrder/QueryRefundOrderList"
	RefundOrder_QueryRefundOrderSummary_FullMethodName = "/pb.RefundOrder/QueryRefundOrderSummary"
	RefundOrder_AddRefundOrder_FullMethodName          = "/pb.RefundOrder/AddRefundOrder"
)

// RefundOrderClient is the client API for RefundOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RefundOrderClient interface {
	QueryRefundOrderList(ctx context.Context, in *QueryRefundOrderListParam, opts ...grpc.CallOption) (*QueryRefundOrderListResponse, error)
	QueryRefundOrderSummary(ctx context.Context, in *QueryRefundOrderListParam, opts ...grpc.CallOption) (*QueryRefundOrderSummaryData, error)
	AddRefundOrder(ctx context.Context, in *AddRefundOrderParam, opts ...grpc.CallOption) (*AddRefundOrderResponse, error)
}

type refundOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewRefundOrderClient(cc grpc.ClientConnInterface) RefundOrderClient {
	return &refundOrderClient{cc}
}

func (c *refundOrderClient) QueryRefundOrderList(ctx context.Context, in *QueryRefundOrderListParam, opts ...grpc.CallOption) (*QueryRefundOrderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRefundOrderListResponse)
	err := c.cc.Invoke(ctx, RefundOrder_QueryRefundOrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundOrderClient) QueryRefundOrderSummary(ctx context.Context, in *QueryRefundOrderListParam, opts ...grpc.CallOption) (*QueryRefundOrderSummaryData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRefundOrderSummaryData)
	err := c.cc.Invoke(ctx, RefundOrder_QueryRefundOrderSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundOrderClient) AddRefundOrder(ctx context.Context, in *AddRefundOrderParam, opts ...grpc.CallOption) (*AddRefundOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRefundOrderResponse)
	err := c.cc.Invoke(ctx, RefundOrder_AddRefundOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundOrderServer is the server API for RefundOrder service.
// All implementations must embed UnimplementedRefundOrderServer
// for forward compatibility.
type RefundOrderServer interface {
	QueryRefundOrderList(context.Context, *QueryRefundOrderListParam) (*QueryRefundOrderListResponse, error)
	QueryRefundOrderSummary(context.Context, *QueryRefundOrderListParam) (*QueryRefundOrderSummaryData, error)
	AddRefundOrder(context.Context, *AddRefundOrderParam) (*AddRefundOrderResponse, error)
	mustEmbedUnimplementedRefundOrderServer()
}

// UnimplementedRefundOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefundOrderServer struct{}

func (UnimplementedRefundOrderServer) QueryRefundOrderList(context.Context, *QueryRefundOrderListParam) (*QueryRefundOrderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRefundOrderList not implemented")
}
func (UnimplementedRefundOrderServer) QueryRefundOrderSummary(context.Context, *QueryRefundOrderListParam) (*QueryRefundOrderSummaryData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRefundOrderSummary not implemented")
}
func (UnimplementedRefundOrderServer) AddRefundOrder(context.Context, *AddRefundOrderParam) (*AddRefundOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRefundOrder not implemented")
}
func (UnimplementedRefundOrderServer) mustEmbedUnimplementedRefundOrderServer() {}
func (UnimplementedRefundOrderServer) testEmbeddedByValue()                     {}

// UnsafeRefundOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefundOrderServer will
// result in compilation errors.
type UnsafeRefundOrderServer interface {
	mustEmbedUnimplementedRefundOrderServer()
}

func RegisterRefundOrderServer(s grpc.ServiceRegistrar, srv RefundOrderServer) {
	// If the following call pancis, it indicates UnimplementedRefundOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RefundOrder_ServiceDesc, srv)
}

func _RefundOrder_QueryRefundOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRefundOrderListParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundOrderServer).QueryRefundOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundOrder_QueryRefundOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundOrderServer).QueryRefundOrderList(ctx, req.(*QueryRefundOrderListParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundOrder_QueryRefundOrderSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRefundOrderListParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundOrderServer).QueryRefundOrderSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundOrder_QueryRefundOrderSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundOrderServer).QueryRefundOrderSummary(ctx, req.(*QueryRefundOrderListParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundOrder_AddRefundOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRefundOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundOrderServer).AddRefundOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundOrder_AddRefundOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundOrderServer).AddRefundOrder(ctx, req.(*AddRefundOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

// RefundOrder_ServiceDesc is the grpc.ServiceDesc for RefundOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RefundOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RefundOrder",
	HandlerType: (*RefundOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryRefundOrderList",
			Handler:    _RefundOrder_QueryRefundOrderList_Handler,
		},
		{
			MethodName: "QueryRefundOrderSummary",
			Handler:    _RefundOrder_QueryRefundOrderSummary_Handler,
		},
		{
			MethodName: "AddRefundOrder",
			Handler:    _RefundOrder_AddRefundOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "refund_order.proto",
}
