// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: refund_order.proto

package refund_order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefundOrderModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreateTime      string                 `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime      string                 `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Id              uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	MerchantAppid   string                 `protobuf:"bytes,4,opt,name=merchant_appid,json=merchantAppid,proto3" json:"merchant_appid,omitempty"`
	MerchantId      uint64                 `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName    string                 `protobuf:"bytes,6,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	BankId          uint64                 `protobuf:"varint,7,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	BankName        string                 `protobuf:"bytes,8,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankOrderNo     string                 `protobuf:"bytes,9,opt,name=bank_order_no,json=bankOrderNo,proto3" json:"bank_order_no,omitempty"`
	MerchantOrderNo string                 `protobuf:"bytes,10,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	OrderNo         string                 `protobuf:"bytes,11,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TradeType       int64                  `protobuf:"varint,12,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	Undertake       int64                  `protobuf:"varint,13,opt,name=undertake,proto3" json:"undertake,omitempty"`
	RefundType      int64                  `protobuf:"varint,14,opt,name=refund_type,json=refundType,proto3" json:"refund_type,omitempty"`
	Currency        string                 `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderAmount     int64                  `protobuf:"varint,16,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	SettleAmount    int64                  `protobuf:"varint,17,opt,name=settle_amount,json=settleAmount,proto3" json:"settle_amount,omitempty"`
	Rate            uint64                 `protobuf:"varint,18,opt,name=rate,proto3" json:"rate,omitempty"`
	FixedFee        uint64                 `protobuf:"varint,19,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	Fee             uint64                 `protobuf:"varint,20,opt,name=fee,proto3" json:"fee,omitempty"`
	Utr             string                 `protobuf:"bytes,21,opt,name=utr,proto3" json:"utr,omitempty"`
	Remark          string                 `protobuf:"bytes,22,opt,name=remark,proto3" json:"remark,omitempty"`
	LaunchUserId    uint64                 `protobuf:"varint,23,opt,name=launch_user_id,json=launchUserId,proto3" json:"launch_user_id,omitempty"`
	OrderCreateTime string                 `protobuf:"bytes,24,opt,name=order_create_time,json=orderCreateTime,proto3" json:"order_create_time,omitempty"`
	RefundAmount    uint64                 `protobuf:"varint,27,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundOrderModel) Reset() {
	*x = RefundOrderModel{}
	mi := &file_refund_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderModel) ProtoMessage() {}

func (x *RefundOrderModel) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderModel.ProtoReflect.Descriptor instead.
func (*RefundOrderModel) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{0}
}

func (x *RefundOrderModel) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *RefundOrderModel) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *RefundOrderModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RefundOrderModel) GetMerchantAppid() string {
	if x != nil {
		return x.MerchantAppid
	}
	return ""
}

func (x *RefundOrderModel) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *RefundOrderModel) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *RefundOrderModel) GetBankId() uint64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *RefundOrderModel) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *RefundOrderModel) GetBankOrderNo() string {
	if x != nil {
		return x.BankOrderNo
	}
	return ""
}

func (x *RefundOrderModel) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

func (x *RefundOrderModel) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RefundOrderModel) GetTradeType() int64 {
	if x != nil {
		return x.TradeType
	}
	return 0
}

func (x *RefundOrderModel) GetUndertake() int64 {
	if x != nil {
		return x.Undertake
	}
	return 0
}

func (x *RefundOrderModel) GetRefundType() int64 {
	if x != nil {
		return x.RefundType
	}
	return 0
}

func (x *RefundOrderModel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RefundOrderModel) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *RefundOrderModel) GetSettleAmount() int64 {
	if x != nil {
		return x.SettleAmount
	}
	return 0
}

func (x *RefundOrderModel) GetRate() uint64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RefundOrderModel) GetFixedFee() uint64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *RefundOrderModel) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *RefundOrderModel) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *RefundOrderModel) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RefundOrderModel) GetLaunchUserId() uint64 {
	if x != nil {
		return x.LaunchUserId
	}
	return 0
}

func (x *RefundOrderModel) GetOrderCreateTime() string {
	if x != nil {
		return x.OrderCreateTime
	}
	return ""
}

func (x *RefundOrderModel) GetRefundAmount() uint64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

type AddRefundOrderParam struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantAppid   string                 `protobuf:"bytes,4,opt,name=merchant_appid,json=merchantAppid,proto3" json:"merchant_appid,omitempty"`
	MerchantId      uint64                 `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	BankId          uint64                 `protobuf:"varint,7,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	BankOrderNo     string                 `protobuf:"bytes,9,opt,name=bank_order_no,json=bankOrderNo,proto3" json:"bank_order_no,omitempty"`
	MerchantOrderNo string                 `protobuf:"bytes,10,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	OrderNo         string                 `protobuf:"bytes,11,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TradeType       int64                  `protobuf:"varint,12,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	Undertake       int64                  `protobuf:"varint,13,opt,name=undertake,proto3" json:"undertake,omitempty"`
	RefundType      int64                  `protobuf:"varint,14,opt,name=refund_type,json=refundType,proto3" json:"refund_type,omitempty"`
	Currency        string                 `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderAmount     int64                  `protobuf:"varint,16,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	SettleAmount    int64                  `protobuf:"varint,17,opt,name=settle_amount,json=settleAmount,proto3" json:"settle_amount,omitempty"`
	Rate            uint64                 `protobuf:"varint,18,opt,name=rate,proto3" json:"rate,omitempty"`
	FixedFee        uint64                 `protobuf:"varint,19,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	Fee             uint64                 `protobuf:"varint,20,opt,name=fee,proto3" json:"fee,omitempty"`
	Utr             string                 `protobuf:"bytes,21,opt,name=utr,proto3" json:"utr,omitempty"`
	Remark          string                 `protobuf:"bytes,22,opt,name=remark,proto3" json:"remark,omitempty"`
	LaunchUserId    uint64                 `protobuf:"varint,23,opt,name=launch_user_id,json=launchUserId,proto3" json:"launch_user_id,omitempty"`
	BankAccount     int64                  `protobuf:"varint,24,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	OrderCreateTime string                 `protobuf:"bytes,25,opt,name=order_create_time,json=orderCreateTime,proto3" json:"order_create_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddRefundOrderParam) Reset() {
	*x = AddRefundOrderParam{}
	mi := &file_refund_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRefundOrderParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRefundOrderParam) ProtoMessage() {}

func (x *AddRefundOrderParam) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRefundOrderParam.ProtoReflect.Descriptor instead.
func (*AddRefundOrderParam) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{1}
}

func (x *AddRefundOrderParam) GetMerchantAppid() string {
	if x != nil {
		return x.MerchantAppid
	}
	return ""
}

func (x *AddRefundOrderParam) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *AddRefundOrderParam) GetBankId() uint64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *AddRefundOrderParam) GetBankOrderNo() string {
	if x != nil {
		return x.BankOrderNo
	}
	return ""
}

func (x *AddRefundOrderParam) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

func (x *AddRefundOrderParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *AddRefundOrderParam) GetTradeType() int64 {
	if x != nil {
		return x.TradeType
	}
	return 0
}

func (x *AddRefundOrderParam) GetUndertake() int64 {
	if x != nil {
		return x.Undertake
	}
	return 0
}

func (x *AddRefundOrderParam) GetRefundType() int64 {
	if x != nil {
		return x.RefundType
	}
	return 0
}

func (x *AddRefundOrderParam) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AddRefundOrderParam) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *AddRefundOrderParam) GetSettleAmount() int64 {
	if x != nil {
		return x.SettleAmount
	}
	return 0
}

func (x *AddRefundOrderParam) GetRate() uint64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *AddRefundOrderParam) GetFixedFee() uint64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *AddRefundOrderParam) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *AddRefundOrderParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *AddRefundOrderParam) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AddRefundOrderParam) GetLaunchUserId() uint64 {
	if x != nil {
		return x.LaunchUserId
	}
	return 0
}

func (x *AddRefundOrderParam) GetBankAccount() int64 {
	if x != nil {
		return x.BankAccount
	}
	return 0
}

func (x *AddRefundOrderParam) GetOrderCreateTime() string {
	if x != nil {
		return x.OrderCreateTime
	}
	return ""
}

type AddRefundOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRefundOrderResponse) Reset() {
	*x = AddRefundOrderResponse{}
	mi := &file_refund_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRefundOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRefundOrderResponse) ProtoMessage() {}

func (x *AddRefundOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRefundOrderResponse.ProtoReflect.Descriptor instead.
func (*AddRefundOrderResponse) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{2}
}

type QueryRefundOrderListParam struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Offset          int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit           int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	MerchantId      uint64                 `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName    string                 `protobuf:"bytes,6,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	BankId          uint64                 `protobuf:"varint,7,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	BankName        string                 `protobuf:"bytes,8,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankOrderNo     string                 `protobuf:"bytes,9,opt,name=bank_order_no,json=bankOrderNo,proto3" json:"bank_order_no,omitempty"`
	MerchantOrderNo string                 `protobuf:"bytes,10,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	OrderNo         string                 `protobuf:"bytes,11,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Undertake       int64                  `protobuf:"varint,13,opt,name=undertake,proto3" json:"undertake,omitempty"`
	Currency        string                 `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
	RefundType      int64                  `protobuf:"varint,14,opt,name=refund_type,json=refundType,proto3" json:"refund_type,omitempty"`
	TradeType       int64                  `protobuf:"varint,12,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	Utr             string                 `protobuf:"bytes,21,opt,name=utr,proto3" json:"utr,omitempty"`
	BankIds         []uint64               `protobuf:"varint,22,rep,packed,name=bank_ids,json=bankIds,proto3" json:"bank_ids,omitempty"`
	MerchantIds     []uint64               `protobuf:"varint,23,rep,packed,name=merchant_ids,json=merchantIds,proto3" json:"merchant_ids,omitempty"`
	TimeType        int64                  `protobuf:"varint,24,opt,name=time_type,json=timeType,proto3" json:"time_type,omitempty"`
	StartTime       string                 `protobuf:"bytes,25,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         string                 `protobuf:"bytes,26,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryRefundOrderListParam) Reset() {
	*x = QueryRefundOrderListParam{}
	mi := &file_refund_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRefundOrderListParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRefundOrderListParam) ProtoMessage() {}

func (x *QueryRefundOrderListParam) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRefundOrderListParam.ProtoReflect.Descriptor instead.
func (*QueryRefundOrderListParam) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRefundOrderListParam) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetBankId() uint64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetBankOrderNo() string {
	if x != nil {
		return x.BankOrderNo
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetUndertake() int64 {
	if x != nil {
		return x.Undertake
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetRefundType() int64 {
	if x != nil {
		return x.RefundType
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetTradeType() int64 {
	if x != nil {
		return x.TradeType
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetUtr() string {
	if x != nil {
		return x.Utr
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetBankIds() []uint64 {
	if x != nil {
		return x.BankIds
	}
	return nil
}

func (x *QueryRefundOrderListParam) GetMerchantIds() []uint64 {
	if x != nil {
		return x.MerchantIds
	}
	return nil
}

func (x *QueryRefundOrderListParam) GetTimeType() int64 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *QueryRefundOrderListParam) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryRefundOrderListParam) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type QueryRefundOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*RefundOrderModel    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRefundOrderListResponse) Reset() {
	*x = QueryRefundOrderListResponse{}
	mi := &file_refund_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRefundOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRefundOrderListResponse) ProtoMessage() {}

func (x *QueryRefundOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRefundOrderListResponse.ProtoReflect.Descriptor instead.
func (*QueryRefundOrderListResponse) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRefundOrderListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryRefundOrderListResponse) GetList() []*RefundOrderModel {
	if x != nil {
		return x.List
	}
	return nil
}

type QueryRefundOrderSummaryData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PayinRefundSummary     *Summary               `protobuf:"bytes,1,opt,name=payin_refund_summary,json=payinRefundSummary,proto3" json:"payin_refund_summary,omitempty"`
	PayinComplaintSummary  *Summary               `protobuf:"bytes,2,opt,name=payin_complaint_summary,json=payinComplaintSummary,proto3" json:"payin_complaint_summary,omitempty"`
	PayoutRefundSummary    *Summary               `protobuf:"bytes,3,opt,name=payout_refund_summary,json=payoutRefundSummary,proto3" json:"payout_refund_summary,omitempty"`
	PayoutComplaintSummary *Summary               `protobuf:"bytes,4,opt,name=payout_complaint_summary,json=payoutComplaintSummary,proto3" json:"payout_complaint_summary,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QueryRefundOrderSummaryData) Reset() {
	*x = QueryRefundOrderSummaryData{}
	mi := &file_refund_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRefundOrderSummaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRefundOrderSummaryData) ProtoMessage() {}

func (x *QueryRefundOrderSummaryData) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRefundOrderSummaryData.ProtoReflect.Descriptor instead.
func (*QueryRefundOrderSummaryData) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRefundOrderSummaryData) GetPayinRefundSummary() *Summary {
	if x != nil {
		return x.PayinRefundSummary
	}
	return nil
}

func (x *QueryRefundOrderSummaryData) GetPayinComplaintSummary() *Summary {
	if x != nil {
		return x.PayinComplaintSummary
	}
	return nil
}

func (x *QueryRefundOrderSummaryData) GetPayoutRefundSummary() *Summary {
	if x != nil {
		return x.PayoutRefundSummary
	}
	return nil
}

func (x *QueryRefundOrderSummaryData) GetPayoutComplaintSummary() *Summary {
	if x != nil {
		return x.PayoutComplaintSummary
	}
	return nil
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundAmount  int64                  `protobuf:"varint,1,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	OrderCount    int64                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Fee           int64                  `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_refund_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_refund_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_refund_order_proto_rawDescGZIP(), []int{6}
}

func (x *Summary) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *Summary) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Summary) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

var File_refund_order_proto protoreflect.FileDescriptor

const file_refund_order_proto_rawDesc = "" +
	"\n" +
	"\x12refund_order.proto\x12\x02pb\"\x98\x06\n" +
	"\x10RefundOrderModel\x12\x1f\n" +
	"\vcreate_time\x18\x01 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x02 \x01(\tR\n" +
	"updateTime\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\x12%\n" +
	"\x0emerchant_appid\x18\x04 \x01(\tR\rmerchantAppid\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x04R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x06 \x01(\tR\fmerchantName\x12\x17\n" +
	"\abank_id\x18\a \x01(\x04R\x06bankId\x12\x1b\n" +
	"\tbank_name\x18\b \x01(\tR\bbankName\x12\"\n" +
	"\rbank_order_no\x18\t \x01(\tR\vbankOrderNo\x12*\n" +
	"\x11merchant_order_no\x18\n" +
	" \x01(\tR\x0fmerchantOrderNo\x12\x19\n" +
	"\border_no\x18\v \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"trade_type\x18\f \x01(\x03R\ttradeType\x12\x1c\n" +
	"\tundertake\x18\r \x01(\x03R\tundertake\x12\x1f\n" +
	"\vrefund_type\x18\x0e \x01(\x03R\n" +
	"refundType\x12\x1a\n" +
	"\bcurrency\x18\x0f \x01(\tR\bcurrency\x12!\n" +
	"\forder_amount\x18\x10 \x01(\x03R\vorderAmount\x12#\n" +
	"\rsettle_amount\x18\x11 \x01(\x03R\fsettleAmount\x12\x12\n" +
	"\x04rate\x18\x12 \x01(\x04R\x04rate\x12\x1b\n" +
	"\tfixed_fee\x18\x13 \x01(\x04R\bfixedFee\x12\x10\n" +
	"\x03fee\x18\x14 \x01(\x04R\x03fee\x12\x10\n" +
	"\x03utr\x18\x15 \x01(\tR\x03utr\x12\x16\n" +
	"\x06remark\x18\x16 \x01(\tR\x06remark\x12$\n" +
	"\x0elaunch_user_id\x18\x17 \x01(\x04R\flaunchUserId\x12*\n" +
	"\x11order_create_time\x18\x18 \x01(\tR\x0forderCreateTime\x12#\n" +
	"\rrefund_amount\x18\x1b \x01(\x04R\frefundAmount\"\x85\x05\n" +
	"\x13AddRefundOrderParam\x12%\n" +
	"\x0emerchant_appid\x18\x04 \x01(\tR\rmerchantAppid\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x04R\n" +
	"merchantId\x12\x17\n" +
	"\abank_id\x18\a \x01(\x04R\x06bankId\x12\"\n" +
	"\rbank_order_no\x18\t \x01(\tR\vbankOrderNo\x12*\n" +
	"\x11merchant_order_no\x18\n" +
	" \x01(\tR\x0fmerchantOrderNo\x12\x19\n" +
	"\border_no\x18\v \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"trade_type\x18\f \x01(\x03R\ttradeType\x12\x1c\n" +
	"\tundertake\x18\r \x01(\x03R\tundertake\x12\x1f\n" +
	"\vrefund_type\x18\x0e \x01(\x03R\n" +
	"refundType\x12\x1a\n" +
	"\bcurrency\x18\x0f \x01(\tR\bcurrency\x12!\n" +
	"\forder_amount\x18\x10 \x01(\x03R\vorderAmount\x12#\n" +
	"\rsettle_amount\x18\x11 \x01(\x03R\fsettleAmount\x12\x12\n" +
	"\x04rate\x18\x12 \x01(\x04R\x04rate\x12\x1b\n" +
	"\tfixed_fee\x18\x13 \x01(\x04R\bfixedFee\x12\x10\n" +
	"\x03fee\x18\x14 \x01(\x04R\x03fee\x12\x10\n" +
	"\x03utr\x18\x15 \x01(\tR\x03utr\x12\x16\n" +
	"\x06remark\x18\x16 \x01(\tR\x06remark\x12$\n" +
	"\x0elaunch_user_id\x18\x17 \x01(\x04R\flaunchUserId\x12!\n" +
	"\fbank_account\x18\x18 \x01(\x03R\vbankAccount\x12*\n" +
	"\x11order_create_time\x18\x19 \x01(\tR\x0forderCreateTime\"\x18\n" +
	"\x16AddRefundOrderResponse\"\xd1\x04\n" +
	"\x19QueryRefundOrderListParam\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x04R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x06 \x01(\tR\fmerchantName\x12\x17\n" +
	"\abank_id\x18\a \x01(\x04R\x06bankId\x12\x1b\n" +
	"\tbank_name\x18\b \x01(\tR\bbankName\x12\"\n" +
	"\rbank_order_no\x18\t \x01(\tR\vbankOrderNo\x12*\n" +
	"\x11merchant_order_no\x18\n" +
	" \x01(\tR\x0fmerchantOrderNo\x12\x19\n" +
	"\border_no\x18\v \x01(\tR\aorderNo\x12\x1c\n" +
	"\tundertake\x18\r \x01(\x03R\tundertake\x12\x1a\n" +
	"\bcurrency\x18\x0f \x01(\tR\bcurrency\x12\x1f\n" +
	"\vrefund_type\x18\x0e \x01(\x03R\n" +
	"refundType\x12\x1d\n" +
	"\n" +
	"trade_type\x18\f \x01(\x03R\ttradeType\x12\x10\n" +
	"\x03utr\x18\x15 \x01(\tR\x03utr\x12\x19\n" +
	"\bbank_ids\x18\x16 \x03(\x04R\abankIds\x12!\n" +
	"\fmerchant_ids\x18\x17 \x03(\x04R\vmerchantIds\x12\x1b\n" +
	"\ttime_type\x18\x18 \x01(\x03R\btimeType\x12\x1d\n" +
	"\n" +
	"start_time\x18\x19 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x1a \x01(\tR\aendTime\"^\n" +
	"\x1cQueryRefundOrderListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.pb.RefundOrderModelR\x04list\"\xa9\x02\n" +
	"\x1bQueryRefundOrderSummaryData\x12=\n" +
	"\x14payin_refund_summary\x18\x01 \x01(\v2\v.pb.summaryR\x12payinRefundSummary\x12C\n" +
	"\x17payin_complaint_summary\x18\x02 \x01(\v2\v.pb.summaryR\x15payinComplaintSummary\x12?\n" +
	"\x15payout_refund_summary\x18\x03 \x01(\v2\v.pb.summaryR\x13payoutRefundSummary\x12E\n" +
	"\x18payout_complaint_summary\x18\x04 \x01(\v2\v.pb.summaryR\x16payoutComplaintSummary\"a\n" +
	"\asummary\x12#\n" +
	"\rrefund_amount\x18\x01 \x01(\x03R\frefundAmount\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x03R\n" +
	"orderCount\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\x03R\x03fee2\x88\x02\n" +
	"\vRefundOrder\x12W\n" +
	"\x14QueryRefundOrderList\x12\x1d.pb.QueryRefundOrderListParam\x1a .pb.QueryRefundOrderListResponse\x12Y\n" +
	"\x17QueryRefundOrderSummary\x12\x1d.pb.QueryRefundOrderListParam\x1a\x1f.pb.QueryRefundOrderSummaryData\x12E\n" +
	"\x0eAddRefundOrder\x12\x17.pb.AddRefundOrderParam\x1a\x1a.pb.AddRefundOrderResponseB$Z\"base/rpc_api/admin/pb/refund_orderb\x06proto3"

var (
	file_refund_order_proto_rawDescOnce sync.Once
	file_refund_order_proto_rawDescData []byte
)

func file_refund_order_proto_rawDescGZIP() []byte {
	file_refund_order_proto_rawDescOnce.Do(func() {
		file_refund_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_refund_order_proto_rawDesc), len(file_refund_order_proto_rawDesc)))
	})
	return file_refund_order_proto_rawDescData
}

var file_refund_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_refund_order_proto_goTypes = []any{
	(*RefundOrderModel)(nil),             // 0: pb.RefundOrderModel
	(*AddRefundOrderParam)(nil),          // 1: pb.AddRefundOrderParam
	(*AddRefundOrderResponse)(nil),       // 2: pb.AddRefundOrderResponse
	(*QueryRefundOrderListParam)(nil),    // 3: pb.QueryRefundOrderListParam
	(*QueryRefundOrderListResponse)(nil), // 4: pb.QueryRefundOrderListResponse
	(*QueryRefundOrderSummaryData)(nil),  // 5: pb.QueryRefundOrderSummaryData
	(*Summary)(nil),                      // 6: pb.summary
}
var file_refund_order_proto_depIdxs = []int32{
	0, // 0: pb.QueryRefundOrderListResponse.list:type_name -> pb.RefundOrderModel
	6, // 1: pb.QueryRefundOrderSummaryData.payin_refund_summary:type_name -> pb.summary
	6, // 2: pb.QueryRefundOrderSummaryData.payin_complaint_summary:type_name -> pb.summary
	6, // 3: pb.QueryRefundOrderSummaryData.payout_refund_summary:type_name -> pb.summary
	6, // 4: pb.QueryRefundOrderSummaryData.payout_complaint_summary:type_name -> pb.summary
	3, // 5: pb.RefundOrder.QueryRefundOrderList:input_type -> pb.QueryRefundOrderListParam
	3, // 6: pb.RefundOrder.QueryRefundOrderSummary:input_type -> pb.QueryRefundOrderListParam
	1, // 7: pb.RefundOrder.AddRefundOrder:input_type -> pb.AddRefundOrderParam
	4, // 8: pb.RefundOrder.QueryRefundOrderList:output_type -> pb.QueryRefundOrderListResponse
	5, // 9: pb.RefundOrder.QueryRefundOrderSummary:output_type -> pb.QueryRefundOrderSummaryData
	2, // 10: pb.RefundOrder.AddRefundOrder:output_type -> pb.AddRefundOrderResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_refund_order_proto_init() }
func file_refund_order_proto_init() {
	if File_refund_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_refund_order_proto_rawDesc), len(file_refund_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refund_order_proto_goTypes,
		DependencyIndexes: file_refund_order_proto_depIdxs,
		MessageInfos:      file_refund_order_proto_msgTypes,
	}.Build()
	File_refund_order_proto = out.File
	file_refund_order_proto_goTypes = nil
	file_refund_order_proto_depIdxs = nil
}
