// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: merchant_group/merchant_group.proto

package merchant_group

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantGroup_GetMerchantGroupList_FullMethodName = "/pb.MerchantGroup/GetMerchantGroupList"
	MerchantGroup_CreateMerchantGroup_FullMethodName  = "/pb.MerchantGroup/CreateMerchantGroup"
	MerchantGroup_UpdateeMerchantGroup_FullMethodName = "/pb.MerchantGroup/UpdateeMerchantGroup"
	MerchantGroup_DeleteMerchantGroup_FullMethodName  = "/pb.MerchantGroup/DeleteMerchantGroup"
	MerchantGroup_GetGroupMerchant_FullMethodName     = "/pb.MerchantGroup/GetGroupMerchant"
	MerchantGroup_SendMerchantMsg_FullMethodName      = "/pb.MerchantGroup/SendMerchantMsg"
)

// MerchantGroupClient is the client API for MerchantGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantGroupClient interface {
	GetMerchantGroupList(ctx context.Context, in *GetMerchantGroupReq, opts ...grpc.CallOption) (*GetMerchantGroupResp, error)
	CreateMerchantGroup(ctx context.Context, in *CreateMerchantGroupReq, opts ...grpc.CallOption) (*MerchantGroupCommResp, error)
	UpdateeMerchantGroup(ctx context.Context, in *UpdateMerchantGroupReq, opts ...grpc.CallOption) (*MerchantGroupCommResp, error)
	DeleteMerchantGroup(ctx context.Context, in *MerchantGroupInfo, opts ...grpc.CallOption) (*MerchantGroupCommResp, error)
	GetGroupMerchant(ctx context.Context, in *GetMerchantGroupReq, opts ...grpc.CallOption) (*GetMerchantGroupResp, error)
	SendMerchantMsg(ctx context.Context, in *SendMerchantMsgReq, opts ...grpc.CallOption) (*MerchantGroupCommResp, error)
}

type merchantGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantGroupClient(cc grpc.ClientConnInterface) MerchantGroupClient {
	return &merchantGroupClient{cc}
}

func (c *merchantGroupClient) GetMerchantGroupList(ctx context.Context, in *GetMerchantGroupReq, opts ...grpc.CallOption) (*GetMerchantGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantGroupResp)
	err := c.cc.Invoke(ctx, MerchantGroup_GetMerchantGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantGroupClient) CreateMerchantGroup(ctx context.Context, in *CreateMerchantGroupReq, opts ...grpc.CallOption) (*MerchantGroupCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantGroupCommResp)
	err := c.cc.Invoke(ctx, MerchantGroup_CreateMerchantGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantGroupClient) UpdateeMerchantGroup(ctx context.Context, in *UpdateMerchantGroupReq, opts ...grpc.CallOption) (*MerchantGroupCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantGroupCommResp)
	err := c.cc.Invoke(ctx, MerchantGroup_UpdateeMerchantGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantGroupClient) DeleteMerchantGroup(ctx context.Context, in *MerchantGroupInfo, opts ...grpc.CallOption) (*MerchantGroupCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantGroupCommResp)
	err := c.cc.Invoke(ctx, MerchantGroup_DeleteMerchantGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantGroupClient) GetGroupMerchant(ctx context.Context, in *GetMerchantGroupReq, opts ...grpc.CallOption) (*GetMerchantGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantGroupResp)
	err := c.cc.Invoke(ctx, MerchantGroup_GetGroupMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantGroupClient) SendMerchantMsg(ctx context.Context, in *SendMerchantMsgReq, opts ...grpc.CallOption) (*MerchantGroupCommResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantGroupCommResp)
	err := c.cc.Invoke(ctx, MerchantGroup_SendMerchantMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantGroupServer is the server API for MerchantGroup service.
// All implementations must embed UnimplementedMerchantGroupServer
// for forward compatibility.
type MerchantGroupServer interface {
	GetMerchantGroupList(context.Context, *GetMerchantGroupReq) (*GetMerchantGroupResp, error)
	CreateMerchantGroup(context.Context, *CreateMerchantGroupReq) (*MerchantGroupCommResp, error)
	UpdateeMerchantGroup(context.Context, *UpdateMerchantGroupReq) (*MerchantGroupCommResp, error)
	DeleteMerchantGroup(context.Context, *MerchantGroupInfo) (*MerchantGroupCommResp, error)
	GetGroupMerchant(context.Context, *GetMerchantGroupReq) (*GetMerchantGroupResp, error)
	SendMerchantMsg(context.Context, *SendMerchantMsgReq) (*MerchantGroupCommResp, error)
	mustEmbedUnimplementedMerchantGroupServer()
}

// UnimplementedMerchantGroupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantGroupServer struct{}

func (UnimplementedMerchantGroupServer) GetMerchantGroupList(context.Context, *GetMerchantGroupReq) (*GetMerchantGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantGroupList not implemented")
}
func (UnimplementedMerchantGroupServer) CreateMerchantGroup(context.Context, *CreateMerchantGroupReq) (*MerchantGroupCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMerchantGroup not implemented")
}
func (UnimplementedMerchantGroupServer) UpdateeMerchantGroup(context.Context, *UpdateMerchantGroupReq) (*MerchantGroupCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateeMerchantGroup not implemented")
}
func (UnimplementedMerchantGroupServer) DeleteMerchantGroup(context.Context, *MerchantGroupInfo) (*MerchantGroupCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMerchantGroup not implemented")
}
func (UnimplementedMerchantGroupServer) GetGroupMerchant(context.Context, *GetMerchantGroupReq) (*GetMerchantGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMerchant not implemented")
}
func (UnimplementedMerchantGroupServer) SendMerchantMsg(context.Context, *SendMerchantMsgReq) (*MerchantGroupCommResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMerchantMsg not implemented")
}
func (UnimplementedMerchantGroupServer) mustEmbedUnimplementedMerchantGroupServer() {}
func (UnimplementedMerchantGroupServer) testEmbeddedByValue()                       {}

// UnsafeMerchantGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantGroupServer will
// result in compilation errors.
type UnsafeMerchantGroupServer interface {
	mustEmbedUnimplementedMerchantGroupServer()
}

func RegisterMerchantGroupServer(s grpc.ServiceRegistrar, srv MerchantGroupServer) {
	// If the following call pancis, it indicates UnimplementedMerchantGroupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantGroup_ServiceDesc, srv)
}

func _MerchantGroup_GetMerchantGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantGroupServer).GetMerchantGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantGroup_GetMerchantGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantGroupServer).GetMerchantGroupList(ctx, req.(*GetMerchantGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantGroup_CreateMerchantGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantGroupServer).CreateMerchantGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantGroup_CreateMerchantGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantGroupServer).CreateMerchantGroup(ctx, req.(*CreateMerchantGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantGroup_UpdateeMerchantGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantGroupServer).UpdateeMerchantGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantGroup_UpdateeMerchantGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantGroupServer).UpdateeMerchantGroup(ctx, req.(*UpdateMerchantGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantGroup_DeleteMerchantGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantGroupInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantGroupServer).DeleteMerchantGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantGroup_DeleteMerchantGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantGroupServer).DeleteMerchantGroup(ctx, req.(*MerchantGroupInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantGroup_GetGroupMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantGroupServer).GetGroupMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantGroup_GetGroupMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantGroupServer).GetGroupMerchant(ctx, req.(*GetMerchantGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantGroup_SendMerchantMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMerchantMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantGroupServer).SendMerchantMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantGroup_SendMerchantMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantGroupServer).SendMerchantMsg(ctx, req.(*SendMerchantMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantGroup_ServiceDesc is the grpc.ServiceDesc for MerchantGroup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantGroup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MerchantGroup",
	HandlerType: (*MerchantGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMerchantGroupList",
			Handler:    _MerchantGroup_GetMerchantGroupList_Handler,
		},
		{
			MethodName: "CreateMerchantGroup",
			Handler:    _MerchantGroup_CreateMerchantGroup_Handler,
		},
		{
			MethodName: "UpdateeMerchantGroup",
			Handler:    _MerchantGroup_UpdateeMerchantGroup_Handler,
		},
		{
			MethodName: "DeleteMerchantGroup",
			Handler:    _MerchantGroup_DeleteMerchantGroup_Handler,
		},
		{
			MethodName: "GetGroupMerchant",
			Handler:    _MerchantGroup_GetGroupMerchant_Handler,
		},
		{
			MethodName: "SendMerchantMsg",
			Handler:    _MerchantGroup_SendMerchantMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_group/merchant_group.proto",
}
