// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: merchant_rbac.proto

package merchant_rbac

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantRbac_GetMenusByTree_FullMethodName = "/pb.MerchantRbac/GetMenusByTree"
	MerchantRbac_GetUserMenus_FullMethodName   = "/pb.MerchantRbac/GetUserMenus"
)

// MerchantRbacClient is the client API for MerchantRbac service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantRbacClient interface {
	GetMenusByTree(ctx context.Context, in *GetMenusByTreeReq, opts ...grpc.CallOption) (*GetMenusByTreeResp, error)
	GetUserMenus(ctx context.Context, in *GetUserMenusReq, opts ...grpc.CallOption) (*GetUserMenusResp, error)
}

type merchantRbacClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantRbacClient(cc grpc.ClientConnInterface) MerchantRbacClient {
	return &merchantRbacClient{cc}
}

func (c *merchantRbacClient) GetMenusByTree(ctx context.Context, in *GetMenusByTreeReq, opts ...grpc.CallOption) (*GetMenusByTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenusByTreeResp)
	err := c.cc.Invoke(ctx, MerchantRbac_GetMenusByTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantRbacClient) GetUserMenus(ctx context.Context, in *GetUserMenusReq, opts ...grpc.CallOption) (*GetUserMenusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMenusResp)
	err := c.cc.Invoke(ctx, MerchantRbac_GetUserMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantRbacServer is the server API for MerchantRbac service.
// All implementations must embed UnimplementedMerchantRbacServer
// for forward compatibility.
type MerchantRbacServer interface {
	GetMenusByTree(context.Context, *GetMenusByTreeReq) (*GetMenusByTreeResp, error)
	GetUserMenus(context.Context, *GetUserMenusReq) (*GetUserMenusResp, error)
	mustEmbedUnimplementedMerchantRbacServer()
}

// UnimplementedMerchantRbacServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantRbacServer struct{}

func (UnimplementedMerchantRbacServer) GetMenusByTree(context.Context, *GetMenusByTreeReq) (*GetMenusByTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenusByTree not implemented")
}
func (UnimplementedMerchantRbacServer) GetUserMenus(context.Context, *GetUserMenusReq) (*GetUserMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMenus not implemented")
}
func (UnimplementedMerchantRbacServer) mustEmbedUnimplementedMerchantRbacServer() {}
func (UnimplementedMerchantRbacServer) testEmbeddedByValue()                      {}

// UnsafeMerchantRbacServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantRbacServer will
// result in compilation errors.
type UnsafeMerchantRbacServer interface {
	mustEmbedUnimplementedMerchantRbacServer()
}

func RegisterMerchantRbacServer(s grpc.ServiceRegistrar, srv MerchantRbacServer) {
	// If the following call pancis, it indicates UnimplementedMerchantRbacServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantRbac_ServiceDesc, srv)
}

func _MerchantRbac_GetMenusByTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenusByTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantRbacServer).GetMenusByTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantRbac_GetMenusByTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantRbacServer).GetMenusByTree(ctx, req.(*GetMenusByTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantRbac_GetUserMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantRbacServer).GetUserMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantRbac_GetUserMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantRbacServer).GetUserMenus(ctx, req.(*GetUserMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantRbac_ServiceDesc is the grpc.ServiceDesc for MerchantRbac service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantRbac_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MerchantRbac",
	HandlerType: (*MerchantRbacServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenusByTree",
			Handler:    _MerchantRbac_GetMenusByTree_Handler,
		},
		{
			MethodName: "GetUserMenus",
			Handler:    _MerchantRbac_GetUserMenus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_rbac.proto",
}
