// goctl rpc protoc payin_order.proto --go_out=. --go-grpc_out=. --zrpc_out=.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: payin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payin_GetCashRegisterUrl_FullMethodName                 = "/pb.Payin/GetCashRegisterUrl"
	Payin_GetPayUrl_FullMethodName                          = "/pb.Payin/GetPayUrl"
	Payin_CallBack_FullMethodName                           = "/pb.Payin/CallBack"
	Payin_GetList_FullMethodName                            = "/pb.Payin/GetList"
	Payin_GetPayinOrderListCumulativeSummary_FullMethodName = "/pb.Payin/GetPayinOrderListCumulativeSummary"
	Payin_GetPayinOrderListSameDaySummary_FullMethodName    = "/pb.Payin/GetPayinOrderListSameDaySummary"
	Payin_AddCompensatePayinOrder_FullMethodName            = "/pb.Payin/AddCompensatePayinOrder"
	Payin_GetNotReleaseListWhitDate_FullMethodName          = "/pb.Payin/GetNotReleaseListWhitDate"
	Payin_BatchUpdateReleasePayinOrder_FullMethodName       = "/pb.Payin/BatchUpdateReleasePayinOrder"
	Payin_MerchantAuditPayinOrder_FullMethodName            = "/pb.Payin/MerchantAuditPayinOrder"
	Payin_AdminAuditPayinOrder_FullMethodName               = "/pb.Payin/AdminAuditPayinOrder"
	Payin_GetManualOrderAuditProcessNodeList_FullMethodName = "/pb.Payin/GetManualOrderAuditProcessNodeList"
	Payin_NotifySuccess_FullMethodName                      = "/pb.Payin/NotifySuccess"
	Payin_UpdateManualOrder_FullMethodName                  = "/pb.Payin/UpdateManualOrder"
	Payin_BatchUpdateRefundPayinOrder_FullMethodName        = "/pb.Payin/BatchUpdateRefundPayinOrder"
	Payin_GetPayinOrderWithCache_FullMethodName             = "/pb.Payin/GetPayinOrderWithCache"
	Payin_GetPayinOrderStatisticsData_FullMethodName        = "/pb.Payin/GetPayinOrderStatisticsData"
	Payin_QueryOrderLog_FullMethodName                      = "/pb.Payin/QueryOrderLog"
	Payin_SubmitPayin_FullMethodName                        = "/pb.Payin/SubmitPayin"
	Payin_GetPayinStatus_FullMethodName                     = "/pb.Payin/GetPayinStatus"
	Payin_GetPayinBalance_FullMethodName                    = "/pb.Payin/GetPayinBalance"
)

// PayinClient is the client API for Payin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayinClient interface {
	GetCashRegisterUrl(ctx context.Context, in *GetCashRegisterURLQuery, opts ...grpc.CallOption) (*GetCashRegisterURLResponse, error)
	GetPayUrl(ctx context.Context, in *GetPayUrlQuery, opts ...grpc.CallOption) (*GetPayUrlResponse, error)
	CallBack(ctx context.Context, in *CallBackParam, opts ...grpc.CallOption) (*CallBackResponse, error)
	GetList(ctx context.Context, in *PayinOrderRecordListQuery, opts ...grpc.CallOption) (*PayinOrderRecordListResponse, error)
	GetPayinOrderListCumulativeSummary(ctx context.Context, in *PayinOrderRecordListQuery, opts ...grpc.CallOption) (*PayinOrderListCumulativeSummaryResponse, error)
	GetPayinOrderListSameDaySummary(ctx context.Context, in *PayinOrderRecordListQuery, opts ...grpc.CallOption) (*PayinOrderListSameDaySummaryResponse, error)
	AddCompensatePayinOrder(ctx context.Context, in *AddCompensatePayinOrderParam, opts ...grpc.CallOption) (*AddCompensatePayinOrderResponse, error)
	GetNotReleaseListWhitDate(ctx context.Context, in *GetNotReleaseListWhitDateListQuery, opts ...grpc.CallOption) (*PayinOrderRecordListResponse, error)
	BatchUpdateReleasePayinOrder(ctx context.Context, in *BatchUpdateReleasePayinOrderParam, opts ...grpc.CallOption) (*BatchUpdateReleasePayinOrderResponse, error)
	MerchantAuditPayinOrder(ctx context.Context, in *AuditPayinOrderParam, opts ...grpc.CallOption) (*AuditPayinOrderResponse, error)
	AdminAuditPayinOrder(ctx context.Context, in *AuditPayinOrderParam, opts ...grpc.CallOption) (*AuditPayinOrderResponse, error)
	GetManualOrderAuditProcessNodeList(ctx context.Context, in *GetManualOrderAuditProcessNodeListQuery, opts ...grpc.CallOption) (*GetManualAuditProcessNodeListResponse, error)
	NotifySuccess(ctx context.Context, in *PayinNotifySuccessReq, opts ...grpc.CallOption) (*PayinNotifySuccessResponse, error)
	UpdateManualOrder(ctx context.Context, in *UpdateManualOrderParam, opts ...grpc.CallOption) (*UpdateManualOrderResponse, error)
	BatchUpdateRefundPayinOrder(ctx context.Context, in *BatchUpdateRefundPayinOrderParam, opts ...grpc.CallOption) (*BatchUpdatePayinOrderResponse, error)
	GetPayinOrderWithCache(ctx context.Context, in *PayinOrderRecordQuery, opts ...grpc.CallOption) (*PayinOrderRecordResponse, error)
	// get payin order statistics data
	GetPayinOrderStatisticsData(ctx context.Context, in *GetPayinOrderStatisticsDataReq, opts ...grpc.CallOption) (*GetPayinOrderStatisticsDataResp, error)
	QueryOrderLog(ctx context.Context, in *QueryPayinOrderLogReq, opts ...grpc.CallOption) (*QueryPayinOrderLogResp, error)
	// 新增：商户对外接口
	SubmitPayin(ctx context.Context, in *PayinSubmitRequest, opts ...grpc.CallOption) (*PayinSubmitResponse, error)
	GetPayinStatus(ctx context.Context, in *PayinStatusRequest, opts ...grpc.CallOption) (*PayinStatusResponse, error)
	GetPayinBalance(ctx context.Context, in *PayinBalanceRequest, opts ...grpc.CallOption) (*PayinBalanceResponse, error)
}

type payinClient struct {
	cc grpc.ClientConnInterface
}

func NewPayinClient(cc grpc.ClientConnInterface) PayinClient {
	return &payinClient{cc}
}

func (c *payinClient) GetCashRegisterUrl(ctx context.Context, in *GetCashRegisterURLQuery, opts ...grpc.CallOption) (*GetCashRegisterURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCashRegisterURLResponse)
	err := c.cc.Invoke(ctx, Payin_GetCashRegisterUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayUrl(ctx context.Context, in *GetPayUrlQuery, opts ...grpc.CallOption) (*GetPayUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayUrlResponse)
	err := c.cc.Invoke(ctx, Payin_GetPayUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) CallBack(ctx context.Context, in *CallBackParam, opts ...grpc.CallOption) (*CallBackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallBackResponse)
	err := c.cc.Invoke(ctx, Payin_CallBack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetList(ctx context.Context, in *PayinOrderRecordListQuery, opts ...grpc.CallOption) (*PayinOrderRecordListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinOrderRecordListResponse)
	err := c.cc.Invoke(ctx, Payin_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayinOrderListCumulativeSummary(ctx context.Context, in *PayinOrderRecordListQuery, opts ...grpc.CallOption) (*PayinOrderListCumulativeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinOrderListCumulativeSummaryResponse)
	err := c.cc.Invoke(ctx, Payin_GetPayinOrderListCumulativeSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayinOrderListSameDaySummary(ctx context.Context, in *PayinOrderRecordListQuery, opts ...grpc.CallOption) (*PayinOrderListSameDaySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinOrderListSameDaySummaryResponse)
	err := c.cc.Invoke(ctx, Payin_GetPayinOrderListSameDaySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) AddCompensatePayinOrder(ctx context.Context, in *AddCompensatePayinOrderParam, opts ...grpc.CallOption) (*AddCompensatePayinOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCompensatePayinOrderResponse)
	err := c.cc.Invoke(ctx, Payin_AddCompensatePayinOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetNotReleaseListWhitDate(ctx context.Context, in *GetNotReleaseListWhitDateListQuery, opts ...grpc.CallOption) (*PayinOrderRecordListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinOrderRecordListResponse)
	err := c.cc.Invoke(ctx, Payin_GetNotReleaseListWhitDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) BatchUpdateReleasePayinOrder(ctx context.Context, in *BatchUpdateReleasePayinOrderParam, opts ...grpc.CallOption) (*BatchUpdateReleasePayinOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateReleasePayinOrderResponse)
	err := c.cc.Invoke(ctx, Payin_BatchUpdateReleasePayinOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) MerchantAuditPayinOrder(ctx context.Context, in *AuditPayinOrderParam, opts ...grpc.CallOption) (*AuditPayinOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditPayinOrderResponse)
	err := c.cc.Invoke(ctx, Payin_MerchantAuditPayinOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) AdminAuditPayinOrder(ctx context.Context, in *AuditPayinOrderParam, opts ...grpc.CallOption) (*AuditPayinOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditPayinOrderResponse)
	err := c.cc.Invoke(ctx, Payin_AdminAuditPayinOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetManualOrderAuditProcessNodeList(ctx context.Context, in *GetManualOrderAuditProcessNodeListQuery, opts ...grpc.CallOption) (*GetManualAuditProcessNodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManualAuditProcessNodeListResponse)
	err := c.cc.Invoke(ctx, Payin_GetManualOrderAuditProcessNodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) NotifySuccess(ctx context.Context, in *PayinNotifySuccessReq, opts ...grpc.CallOption) (*PayinNotifySuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinNotifySuccessResponse)
	err := c.cc.Invoke(ctx, Payin_NotifySuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) UpdateManualOrder(ctx context.Context, in *UpdateManualOrderParam, opts ...grpc.CallOption) (*UpdateManualOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManualOrderResponse)
	err := c.cc.Invoke(ctx, Payin_UpdateManualOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) BatchUpdateRefundPayinOrder(ctx context.Context, in *BatchUpdateRefundPayinOrderParam, opts ...grpc.CallOption) (*BatchUpdatePayinOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdatePayinOrderResponse)
	err := c.cc.Invoke(ctx, Payin_BatchUpdateRefundPayinOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayinOrderWithCache(ctx context.Context, in *PayinOrderRecordQuery, opts ...grpc.CallOption) (*PayinOrderRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinOrderRecordResponse)
	err := c.cc.Invoke(ctx, Payin_GetPayinOrderWithCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayinOrderStatisticsData(ctx context.Context, in *GetPayinOrderStatisticsDataReq, opts ...grpc.CallOption) (*GetPayinOrderStatisticsDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayinOrderStatisticsDataResp)
	err := c.cc.Invoke(ctx, Payin_GetPayinOrderStatisticsData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) QueryOrderLog(ctx context.Context, in *QueryPayinOrderLogReq, opts ...grpc.CallOption) (*QueryPayinOrderLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPayinOrderLogResp)
	err := c.cc.Invoke(ctx, Payin_QueryOrderLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) SubmitPayin(ctx context.Context, in *PayinSubmitRequest, opts ...grpc.CallOption) (*PayinSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinSubmitResponse)
	err := c.cc.Invoke(ctx, Payin_SubmitPayin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayinStatus(ctx context.Context, in *PayinStatusRequest, opts ...grpc.CallOption) (*PayinStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinStatusResponse)
	err := c.cc.Invoke(ctx, Payin_GetPayinStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinClient) GetPayinBalance(ctx context.Context, in *PayinBalanceRequest, opts ...grpc.CallOption) (*PayinBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayinBalanceResponse)
	err := c.cc.Invoke(ctx, Payin_GetPayinBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayinServer is the server API for Payin service.
// All implementations must embed UnimplementedPayinServer
// for forward compatibility.
type PayinServer interface {
	GetCashRegisterUrl(context.Context, *GetCashRegisterURLQuery) (*GetCashRegisterURLResponse, error)
	GetPayUrl(context.Context, *GetPayUrlQuery) (*GetPayUrlResponse, error)
	CallBack(context.Context, *CallBackParam) (*CallBackResponse, error)
	GetList(context.Context, *PayinOrderRecordListQuery) (*PayinOrderRecordListResponse, error)
	GetPayinOrderListCumulativeSummary(context.Context, *PayinOrderRecordListQuery) (*PayinOrderListCumulativeSummaryResponse, error)
	GetPayinOrderListSameDaySummary(context.Context, *PayinOrderRecordListQuery) (*PayinOrderListSameDaySummaryResponse, error)
	AddCompensatePayinOrder(context.Context, *AddCompensatePayinOrderParam) (*AddCompensatePayinOrderResponse, error)
	GetNotReleaseListWhitDate(context.Context, *GetNotReleaseListWhitDateListQuery) (*PayinOrderRecordListResponse, error)
	BatchUpdateReleasePayinOrder(context.Context, *BatchUpdateReleasePayinOrderParam) (*BatchUpdateReleasePayinOrderResponse, error)
	MerchantAuditPayinOrder(context.Context, *AuditPayinOrderParam) (*AuditPayinOrderResponse, error)
	AdminAuditPayinOrder(context.Context, *AuditPayinOrderParam) (*AuditPayinOrderResponse, error)
	GetManualOrderAuditProcessNodeList(context.Context, *GetManualOrderAuditProcessNodeListQuery) (*GetManualAuditProcessNodeListResponse, error)
	NotifySuccess(context.Context, *PayinNotifySuccessReq) (*PayinNotifySuccessResponse, error)
	UpdateManualOrder(context.Context, *UpdateManualOrderParam) (*UpdateManualOrderResponse, error)
	BatchUpdateRefundPayinOrder(context.Context, *BatchUpdateRefundPayinOrderParam) (*BatchUpdatePayinOrderResponse, error)
	GetPayinOrderWithCache(context.Context, *PayinOrderRecordQuery) (*PayinOrderRecordResponse, error)
	// get payin order statistics data
	GetPayinOrderStatisticsData(context.Context, *GetPayinOrderStatisticsDataReq) (*GetPayinOrderStatisticsDataResp, error)
	QueryOrderLog(context.Context, *QueryPayinOrderLogReq) (*QueryPayinOrderLogResp, error)
	// 新增：商户对外接口
	SubmitPayin(context.Context, *PayinSubmitRequest) (*PayinSubmitResponse, error)
	GetPayinStatus(context.Context, *PayinStatusRequest) (*PayinStatusResponse, error)
	GetPayinBalance(context.Context, *PayinBalanceRequest) (*PayinBalanceResponse, error)
	mustEmbedUnimplementedPayinServer()
}

// UnimplementedPayinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayinServer struct{}

func (UnimplementedPayinServer) GetCashRegisterUrl(context.Context, *GetCashRegisterURLQuery) (*GetCashRegisterURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCashRegisterUrl not implemented")
}
func (UnimplementedPayinServer) GetPayUrl(context.Context, *GetPayUrlQuery) (*GetPayUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayUrl not implemented")
}
func (UnimplementedPayinServer) CallBack(context.Context, *CallBackParam) (*CallBackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallBack not implemented")
}
func (UnimplementedPayinServer) GetList(context.Context, *PayinOrderRecordListQuery) (*PayinOrderRecordListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedPayinServer) GetPayinOrderListCumulativeSummary(context.Context, *PayinOrderRecordListQuery) (*PayinOrderListCumulativeSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinOrderListCumulativeSummary not implemented")
}
func (UnimplementedPayinServer) GetPayinOrderListSameDaySummary(context.Context, *PayinOrderRecordListQuery) (*PayinOrderListSameDaySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinOrderListSameDaySummary not implemented")
}
func (UnimplementedPayinServer) AddCompensatePayinOrder(context.Context, *AddCompensatePayinOrderParam) (*AddCompensatePayinOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCompensatePayinOrder not implemented")
}
func (UnimplementedPayinServer) GetNotReleaseListWhitDate(context.Context, *GetNotReleaseListWhitDateListQuery) (*PayinOrderRecordListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotReleaseListWhitDate not implemented")
}
func (UnimplementedPayinServer) BatchUpdateReleasePayinOrder(context.Context, *BatchUpdateReleasePayinOrderParam) (*BatchUpdateReleasePayinOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateReleasePayinOrder not implemented")
}
func (UnimplementedPayinServer) MerchantAuditPayinOrder(context.Context, *AuditPayinOrderParam) (*AuditPayinOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantAuditPayinOrder not implemented")
}
func (UnimplementedPayinServer) AdminAuditPayinOrder(context.Context, *AuditPayinOrderParam) (*AuditPayinOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminAuditPayinOrder not implemented")
}
func (UnimplementedPayinServer) GetManualOrderAuditProcessNodeList(context.Context, *GetManualOrderAuditProcessNodeListQuery) (*GetManualAuditProcessNodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManualOrderAuditProcessNodeList not implemented")
}
func (UnimplementedPayinServer) NotifySuccess(context.Context, *PayinNotifySuccessReq) (*PayinNotifySuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifySuccess not implemented")
}
func (UnimplementedPayinServer) UpdateManualOrder(context.Context, *UpdateManualOrderParam) (*UpdateManualOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManualOrder not implemented")
}
func (UnimplementedPayinServer) BatchUpdateRefundPayinOrder(context.Context, *BatchUpdateRefundPayinOrderParam) (*BatchUpdatePayinOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateRefundPayinOrder not implemented")
}
func (UnimplementedPayinServer) GetPayinOrderWithCache(context.Context, *PayinOrderRecordQuery) (*PayinOrderRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinOrderWithCache not implemented")
}
func (UnimplementedPayinServer) GetPayinOrderStatisticsData(context.Context, *GetPayinOrderStatisticsDataReq) (*GetPayinOrderStatisticsDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinOrderStatisticsData not implemented")
}
func (UnimplementedPayinServer) QueryOrderLog(context.Context, *QueryPayinOrderLogReq) (*QueryPayinOrderLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrderLog not implemented")
}
func (UnimplementedPayinServer) SubmitPayin(context.Context, *PayinSubmitRequest) (*PayinSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPayin not implemented")
}
func (UnimplementedPayinServer) GetPayinStatus(context.Context, *PayinStatusRequest) (*PayinStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinStatus not implemented")
}
func (UnimplementedPayinServer) GetPayinBalance(context.Context, *PayinBalanceRequest) (*PayinBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinBalance not implemented")
}
func (UnimplementedPayinServer) mustEmbedUnimplementedPayinServer() {}
func (UnimplementedPayinServer) testEmbeddedByValue()               {}

// UnsafePayinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayinServer will
// result in compilation errors.
type UnsafePayinServer interface {
	mustEmbedUnimplementedPayinServer()
}

func RegisterPayinServer(s grpc.ServiceRegistrar, srv PayinServer) {
	// If the following call pancis, it indicates UnimplementedPayinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payin_ServiceDesc, srv)
}

func _Payin_GetCashRegisterUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCashRegisterURLQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetCashRegisterUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetCashRegisterUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetCashRegisterUrl(ctx, req.(*GetCashRegisterURLQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayUrlQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayUrl(ctx, req.(*GetPayUrlQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_CallBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallBackParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).CallBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_CallBack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).CallBack(ctx, req.(*CallBackParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinOrderRecordListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetList(ctx, req.(*PayinOrderRecordListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayinOrderListCumulativeSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinOrderRecordListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayinOrderListCumulativeSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayinOrderListCumulativeSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayinOrderListCumulativeSummary(ctx, req.(*PayinOrderRecordListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayinOrderListSameDaySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinOrderRecordListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayinOrderListSameDaySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayinOrderListSameDaySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayinOrderListSameDaySummary(ctx, req.(*PayinOrderRecordListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_AddCompensatePayinOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCompensatePayinOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).AddCompensatePayinOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_AddCompensatePayinOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).AddCompensatePayinOrder(ctx, req.(*AddCompensatePayinOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetNotReleaseListWhitDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotReleaseListWhitDateListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetNotReleaseListWhitDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetNotReleaseListWhitDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetNotReleaseListWhitDate(ctx, req.(*GetNotReleaseListWhitDateListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_BatchUpdateReleasePayinOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateReleasePayinOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).BatchUpdateReleasePayinOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_BatchUpdateReleasePayinOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).BatchUpdateReleasePayinOrder(ctx, req.(*BatchUpdateReleasePayinOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_MerchantAuditPayinOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditPayinOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).MerchantAuditPayinOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_MerchantAuditPayinOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).MerchantAuditPayinOrder(ctx, req.(*AuditPayinOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_AdminAuditPayinOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditPayinOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).AdminAuditPayinOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_AdminAuditPayinOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).AdminAuditPayinOrder(ctx, req.(*AuditPayinOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetManualOrderAuditProcessNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManualOrderAuditProcessNodeListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetManualOrderAuditProcessNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetManualOrderAuditProcessNodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetManualOrderAuditProcessNodeList(ctx, req.(*GetManualOrderAuditProcessNodeListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_NotifySuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinNotifySuccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).NotifySuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_NotifySuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).NotifySuccess(ctx, req.(*PayinNotifySuccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_UpdateManualOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManualOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).UpdateManualOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_UpdateManualOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).UpdateManualOrder(ctx, req.(*UpdateManualOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_BatchUpdateRefundPayinOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateRefundPayinOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).BatchUpdateRefundPayinOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_BatchUpdateRefundPayinOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).BatchUpdateRefundPayinOrder(ctx, req.(*BatchUpdateRefundPayinOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayinOrderWithCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinOrderRecordQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayinOrderWithCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayinOrderWithCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayinOrderWithCache(ctx, req.(*PayinOrderRecordQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayinOrderStatisticsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayinOrderStatisticsDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayinOrderStatisticsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayinOrderStatisticsData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayinOrderStatisticsData(ctx, req.(*GetPayinOrderStatisticsDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_QueryOrderLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPayinOrderLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).QueryOrderLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_QueryOrderLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).QueryOrderLog(ctx, req.(*QueryPayinOrderLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_SubmitPayin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).SubmitPayin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_SubmitPayin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).SubmitPayin(ctx, req.(*PayinSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayinStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayinStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayinStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayinStatus(ctx, req.(*PayinStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payin_GetPayinBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayinBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayinServer).GetPayinBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payin_GetPayinBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayinServer).GetPayinBalance(ctx, req.(*PayinBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payin_ServiceDesc is the grpc.ServiceDesc for Payin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Payin",
	HandlerType: (*PayinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCashRegisterUrl",
			Handler:    _Payin_GetCashRegisterUrl_Handler,
		},
		{
			MethodName: "GetPayUrl",
			Handler:    _Payin_GetPayUrl_Handler,
		},
		{
			MethodName: "CallBack",
			Handler:    _Payin_CallBack_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _Payin_GetList_Handler,
		},
		{
			MethodName: "GetPayinOrderListCumulativeSummary",
			Handler:    _Payin_GetPayinOrderListCumulativeSummary_Handler,
		},
		{
			MethodName: "GetPayinOrderListSameDaySummary",
			Handler:    _Payin_GetPayinOrderListSameDaySummary_Handler,
		},
		{
			MethodName: "AddCompensatePayinOrder",
			Handler:    _Payin_AddCompensatePayinOrder_Handler,
		},
		{
			MethodName: "GetNotReleaseListWhitDate",
			Handler:    _Payin_GetNotReleaseListWhitDate_Handler,
		},
		{
			MethodName: "BatchUpdateReleasePayinOrder",
			Handler:    _Payin_BatchUpdateReleasePayinOrder_Handler,
		},
		{
			MethodName: "MerchantAuditPayinOrder",
			Handler:    _Payin_MerchantAuditPayinOrder_Handler,
		},
		{
			MethodName: "AdminAuditPayinOrder",
			Handler:    _Payin_AdminAuditPayinOrder_Handler,
		},
		{
			MethodName: "GetManualOrderAuditProcessNodeList",
			Handler:    _Payin_GetManualOrderAuditProcessNodeList_Handler,
		},
		{
			MethodName: "NotifySuccess",
			Handler:    _Payin_NotifySuccess_Handler,
		},
		{
			MethodName: "UpdateManualOrder",
			Handler:    _Payin_UpdateManualOrder_Handler,
		},
		{
			MethodName: "BatchUpdateRefundPayinOrder",
			Handler:    _Payin_BatchUpdateRefundPayinOrder_Handler,
		},
		{
			MethodName: "GetPayinOrderWithCache",
			Handler:    _Payin_GetPayinOrderWithCache_Handler,
		},
		{
			MethodName: "GetPayinOrderStatisticsData",
			Handler:    _Payin_GetPayinOrderStatisticsData_Handler,
		},
		{
			MethodName: "QueryOrderLog",
			Handler:    _Payin_QueryOrderLog_Handler,
		},
		{
			MethodName: "SubmitPayin",
			Handler:    _Payin_SubmitPayin_Handler,
		},
		{
			MethodName: "GetPayinStatus",
			Handler:    _Payin_GetPayinStatus_Handler,
		},
		{
			MethodName: "GetPayinBalance",
			Handler:    _Payin_GetPayinBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payin.proto",
}
