// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: clearing.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clearing_GetOrderList_FullMethodName = "/pb.clearing/GetOrderList"
	Clearing_OrderAudit_FullMethodName   = "/pb.clearing/OrderAudit"
)

// ClearingClient is the client API for Clearing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClearingClient interface {
	// get clearing order list
	GetOrderList(ctx context.Context, in *GetOrderListReq, opts ...grpc.CallOption) (*GetOrderListResp, error)
	// clearing order audit
	OrderAudit(ctx context.Context, in *OrderAuditReq, opts ...grpc.CallOption) (*OrderAuditResp, error)
}

type clearingClient struct {
	cc grpc.ClientConnInterface
}

func NewClearingClient(cc grpc.ClientConnInterface) ClearingClient {
	return &clearingClient{cc}
}

func (c *clearingClient) GetOrderList(ctx context.Context, in *GetOrderListReq, opts ...grpc.CallOption) (*GetOrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderListResp)
	err := c.cc.Invoke(ctx, Clearing_GetOrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clearingClient) OrderAudit(ctx context.Context, in *OrderAuditReq, opts ...grpc.CallOption) (*OrderAuditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderAuditResp)
	err := c.cc.Invoke(ctx, Clearing_OrderAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClearingServer is the server API for Clearing service.
// All implementations must embed UnimplementedClearingServer
// for forward compatibility.
type ClearingServer interface {
	// get clearing order list
	GetOrderList(context.Context, *GetOrderListReq) (*GetOrderListResp, error)
	// clearing order audit
	OrderAudit(context.Context, *OrderAuditReq) (*OrderAuditResp, error)
	mustEmbedUnimplementedClearingServer()
}

// UnimplementedClearingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClearingServer struct{}

func (UnimplementedClearingServer) GetOrderList(context.Context, *GetOrderListReq) (*GetOrderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderList not implemented")
}
func (UnimplementedClearingServer) OrderAudit(context.Context, *OrderAuditReq) (*OrderAuditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderAudit not implemented")
}
func (UnimplementedClearingServer) mustEmbedUnimplementedClearingServer() {}
func (UnimplementedClearingServer) testEmbeddedByValue()                  {}

// UnsafeClearingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClearingServer will
// result in compilation errors.
type UnsafeClearingServer interface {
	mustEmbedUnimplementedClearingServer()
}

func RegisterClearingServer(s grpc.ServiceRegistrar, srv ClearingServer) {
	// If the following call pancis, it indicates UnimplementedClearingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clearing_ServiceDesc, srv)
}

func _Clearing_GetOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClearingServer).GetOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clearing_GetOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClearingServer).GetOrderList(ctx, req.(*GetOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clearing_OrderAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderAuditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClearingServer).OrderAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clearing_OrderAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClearingServer).OrderAudit(ctx, req.(*OrderAuditReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Clearing_ServiceDesc is the grpc.ServiceDesc for Clearing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clearing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.clearing",
	HandlerType: (*ClearingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderList",
			Handler:    _Clearing_GetOrderList_Handler,
		},
		{
			MethodName: "OrderAudit",
			Handler:    _Clearing_OrderAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clearing.proto",
}
