// Code generated by "stringer -type=ErrCode --linecomment"; DO NOT EDIT.

package err_code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeSuccess-100000]
	_ = x[ErrCodeRepeatOrder-400001]
	_ = x[ErrCodeNotifyUrlEMpty-400002]
	_ = x[ErrCodeMerchantNotFound-400003]
	_ = x[ErrCodeOrderNotFound-400004]
	_ = x[ErrCodeOrderRecordNotFound-400005]
	_ = x[ErrCodeResuestParamCheck-400006]
	_ = x[ErrCodeMerchantPayConfigNotFound-400007]
	_ = x[ErrCodeMerchantAppSecretCheck-400008]
	_ = x[ErrCodeMerchantCurrencyCheck-400009]
	_ = x[ErrCodeMerchantIpCheck-400010]
	_ = x[ErrCodeMerchantAmountCheck-400011]
	_ = x[ErrCodeMerchantDailyMaxTxCountCheck-400012]
	_ = x[ErrCodeMerchantStatusCheck-400013]
	_ = x[ErrCodeMerchantWorkloadCheck-400014]
	_ = x[ErrCodeMerchantBalanceCheck-400015]
	_ = x[ErrCodeMerchantBankNotFound-400016]
	_ = x[ErrCodeMerchantTradeMinCheck-400017]
	_ = x[ErrCodeMerchantTradeMaxCheck-400018]
	_ = x[ErrCodeMerchantOrderNoAlreadyExist-400019]
	_ = x[ErrCodeMerchantNotifyUrlIsNull-400020]
	_ = x[ErrCodeProtoMarshal-400021]
	_ = x[ErrCodeProtoUnmarshal-400022]
	_ = x[ErrCodePrePayIDNotExist-400023]
	_ = x[ErrCodeMerchantNotMatch-400024]
	_ = x[ErrCodeMerchantCurrencyIsNull-400025]
	_ = x[ErrCodeMerchantIPNotInWhiteList-400026]
	_ = x[ErrCodeMerchantSignatureVerificationFailed-400027]
	_ = x[ErrCodeMerchantSignValAssertionFailed-400028]
	_ = x[ErrCodeTimestampExpired-400029]
	_ = x[ErrCodeMerchantEDBaseDecode-400030]
	_ = x[ErrCodeMerchantWithdrawaSwitchDisabled-400031]
	_ = x[ErrCodeBankSwitchDisabled-400032]
	_ = x[ErrCodeBankDailyMaxTxCountCheck-400033]
	_ = x[ErrCodeBankWorkloadCheck-400034]
	_ = x[ErrCodeBankTradeMinCheck-400035]
	_ = x[ErrCodeBankTradeMaxCheck-400036]
	_ = x[ErrCodeMerchantRateNotEdit-400037]
	_ = x[ErrCodeBankIsDisabled-400038]
	_ = x[ErrCodeMerchantBankIsDisabled-400039]
	_ = x[ErrCodeMOrderAmountNotSupportDecimal-400040]
	_ = x[ErrCodeSystem-500001]
	_ = x[ErrCodeRedis-500002]
	_ = x[ErrCodeKafka-500003]
	_ = x[ErrCodeFormatPB-500004]
	_ = x[ErrCodeRpc-500005]
	_ = x[ErrCodeDataBase-500006]
	_ = x[ErrCodeBase-500007]
	_ = x[ErrCodeMerchantRPC-500008]
	_ = x[ErrCodeMerchantUnmarshal-500009]
	_ = x[ErrCodeMethodTypeNotAllowed-500010]
	_ = x[ErrBankServerIPEmpty-500011]
	_ = x[ErrBankServerRpc-500012]
	_ = x[ErrCodeMerchant-20000]
	_ = x[ErrCodeAdmin-30000]
}

const (
	_ErrCode_name_0 = "merchant err"
	_ErrCode_name_1 = "admin err"
	_ErrCode_name_2 = "success"
	_ErrCode_name_3 = "Duplicate order numberThe notification address of the merchant or order is emptymerchant does not existorder does not existorder record not foundrequest parameter verification failedmerchant pay config does not existmerchant AppSecret verification failedmerchant Currency verification failedmerchant Ip verification failedmerchant transaction amount lt 0Total amount has reached daily limit.merchant status is disabledThe volume per minute has reached the limit.merchant balance verification failed, don't have enough balancemerchant choose bank failTransaction amount is below the minimum limit. Please re-enter.Transaction amount exceeds the maximum limit. Please re-enter.the order no is duplicated for this merchantmerchant notify url is nullproto marshal failedproto unmarshal failedorder expiredmerchantAppid not matchmerchant currency is nullthis IP is not on the whitelistsignature verification failedsign val assertion failedTimestamp expired, please set a timestamp within 1 minutesMerchant public key base decoding failedMerchant withdrawal switch disabledThis bank switch disabledCheck:Total amount has reached daily limit.Check:The volume per minute has reached the limit.Check:Transaction amount is below the minimum limit. Please re-enter.Check:Transaction amount exceeds the maximum limit. Please re-enter.merchant choose group failCheck:merchant choose bank failmerchant choose bank failOrder Amount does not support decimals"
	_ErrCode_name_4 = "internal dependency errorinternal dependency errorinternal dependency errorinternal dependency errorinternal dependency errorinternal dependency errorinternal dependency errorinternal dependency errorinternal dependency errormethod type not allowedinternal dependency errorinternal dependency error"
)

var (
	_ErrCode_index_3 = [...]uint16{0, 22, 80, 103, 123, 145, 182, 216, 254, 291, 322, 354, 391, 418, 462, 525, 550, 613, 675, 719, 746, 766, 788, 801, 824, 849, 880, 909, 934, 992, 1032, 1067, 1092, 1135, 1185, 1254, 1322, 1348, 1379, 1404, 1442}
	_ErrCode_index_4 = [...]uint16{0, 25, 50, 75, 100, 125, 150, 175, 200, 225, 248, 273, 298}
)

func (i ErrCode) String() string {
	switch {
	case i == 20000:
		return _ErrCode_name_0
	case i == 30000:
		return _ErrCode_name_1
	case i == 100000:
		return _ErrCode_name_2
	case 400001 <= i && i <= 400040:
		i -= 400001
		return _ErrCode_name_3[_ErrCode_index_3[i]:_ErrCode_index_3[i+1]]
	case 500001 <= i && i <= 500012:
		i -= 500001
		return _ErrCode_name_4[_ErrCode_index_4[i]:_ErrCode_index_4[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
