// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: statistics/statistics.proto

package statistics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Statistics_GetStatisticsMerchantList_FullMethodName          = "/pb.Statistics/GetStatisticsMerchantList"
	Statistics_GetStatisticsMerchantTradeTypeList_FullMethodName = "/pb.Statistics/GetStatisticsMerchantTradeTypeList"
	Statistics_GetStatisticsBankList_FullMethodName              = "/pb.Statistics/GetStatisticsBankList"
	Statistics_GetStatisticsBankTradeTypeList_FullMethodName     = "/pb.Statistics/GetStatisticsBankTradeTypeList"
	Statistics_GetStatisticsTradeTypeList_FullMethodName         = "/pb.Statistics/GetStatisticsTradeTypeList"
)

// StatisticsClient is the client API for Statistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsClient interface {
	// get statistics merchant list info
	GetStatisticsMerchantList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsMerchantListResp, error)
	GetStatisticsMerchantTradeTypeList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsMerchantTradeTypeListResp, error)
	GetStatisticsBankList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsBankListResp, error)
	GetStatisticsBankTradeTypeList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsBankTradeTypeListResp, error)
	GetStatisticsTradeTypeList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsTradeTypeListResp, error)
}

type statisticsClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsClient(cc grpc.ClientConnInterface) StatisticsClient {
	return &statisticsClient{cc}
}

func (c *statisticsClient) GetStatisticsMerchantList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsMerchantListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsMerchantListResp)
	err := c.cc.Invoke(ctx, Statistics_GetStatisticsMerchantList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetStatisticsMerchantTradeTypeList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsMerchantTradeTypeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsMerchantTradeTypeListResp)
	err := c.cc.Invoke(ctx, Statistics_GetStatisticsMerchantTradeTypeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetStatisticsBankList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsBankListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsBankListResp)
	err := c.cc.Invoke(ctx, Statistics_GetStatisticsBankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetStatisticsBankTradeTypeList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsBankTradeTypeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsBankTradeTypeListResp)
	err := c.cc.Invoke(ctx, Statistics_GetStatisticsBankTradeTypeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetStatisticsTradeTypeList(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsTradeTypeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsTradeTypeListResp)
	err := c.cc.Invoke(ctx, Statistics_GetStatisticsTradeTypeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServer is the server API for Statistics service.
// All implementations must embed UnimplementedStatisticsServer
// for forward compatibility.
type StatisticsServer interface {
	// get statistics merchant list info
	GetStatisticsMerchantList(context.Context, *GetStatisticsReq) (*GetStatisticsMerchantListResp, error)
	GetStatisticsMerchantTradeTypeList(context.Context, *GetStatisticsReq) (*GetStatisticsMerchantTradeTypeListResp, error)
	GetStatisticsBankList(context.Context, *GetStatisticsReq) (*GetStatisticsBankListResp, error)
	GetStatisticsBankTradeTypeList(context.Context, *GetStatisticsReq) (*GetStatisticsBankTradeTypeListResp, error)
	GetStatisticsTradeTypeList(context.Context, *GetStatisticsReq) (*GetStatisticsTradeTypeListResp, error)
	mustEmbedUnimplementedStatisticsServer()
}

// UnimplementedStatisticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServer struct{}

func (UnimplementedStatisticsServer) GetStatisticsMerchantList(context.Context, *GetStatisticsReq) (*GetStatisticsMerchantListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsMerchantList not implemented")
}
func (UnimplementedStatisticsServer) GetStatisticsMerchantTradeTypeList(context.Context, *GetStatisticsReq) (*GetStatisticsMerchantTradeTypeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsMerchantTradeTypeList not implemented")
}
func (UnimplementedStatisticsServer) GetStatisticsBankList(context.Context, *GetStatisticsReq) (*GetStatisticsBankListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsBankList not implemented")
}
func (UnimplementedStatisticsServer) GetStatisticsBankTradeTypeList(context.Context, *GetStatisticsReq) (*GetStatisticsBankTradeTypeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsBankTradeTypeList not implemented")
}
func (UnimplementedStatisticsServer) GetStatisticsTradeTypeList(context.Context, *GetStatisticsReq) (*GetStatisticsTradeTypeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsTradeTypeList not implemented")
}
func (UnimplementedStatisticsServer) mustEmbedUnimplementedStatisticsServer() {}
func (UnimplementedStatisticsServer) testEmbeddedByValue()                    {}

// UnsafeStatisticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServer will
// result in compilation errors.
type UnsafeStatisticsServer interface {
	mustEmbedUnimplementedStatisticsServer()
}

func RegisterStatisticsServer(s grpc.ServiceRegistrar, srv StatisticsServer) {
	// If the following call pancis, it indicates UnimplementedStatisticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Statistics_ServiceDesc, srv)
}

func _Statistics_GetStatisticsMerchantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStatisticsMerchantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetStatisticsMerchantList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStatisticsMerchantList(ctx, req.(*GetStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetStatisticsMerchantTradeTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStatisticsMerchantTradeTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetStatisticsMerchantTradeTypeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStatisticsMerchantTradeTypeList(ctx, req.(*GetStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetStatisticsBankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStatisticsBankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetStatisticsBankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStatisticsBankList(ctx, req.(*GetStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetStatisticsBankTradeTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStatisticsBankTradeTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetStatisticsBankTradeTypeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStatisticsBankTradeTypeList(ctx, req.(*GetStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetStatisticsTradeTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStatisticsTradeTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetStatisticsTradeTypeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStatisticsTradeTypeList(ctx, req.(*GetStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Statistics_ServiceDesc is the grpc.ServiceDesc for Statistics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Statistics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Statistics",
	HandlerType: (*StatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatisticsMerchantList",
			Handler:    _Statistics_GetStatisticsMerchantList_Handler,
		},
		{
			MethodName: "GetStatisticsMerchantTradeTypeList",
			Handler:    _Statistics_GetStatisticsMerchantTradeTypeList_Handler,
		},
		{
			MethodName: "GetStatisticsBankList",
			Handler:    _Statistics_GetStatisticsBankList_Handler,
		},
		{
			MethodName: "GetStatisticsBankTradeTypeList",
			Handler:    _Statistics_GetStatisticsBankTradeTypeList_Handler,
		},
		{
			MethodName: "GetStatisticsTradeTypeList",
			Handler:    _Statistics_GetStatisticsTradeTypeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics/statistics.proto",
}
