// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: statistics/statistics.proto

package statistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatisticsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size           int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MerchantId     int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName   string                 `protobuf:"bytes,4,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	StartTime      string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BankName       string                 `protobuf:"bytes,7,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankIdentifier string                 `protobuf:"bytes,8,opt,name=bank_identifier,json=bankIdentifier,proto3" json:"bank_identifier,omitempty"`
	// day month week random
	LoadMode      string `protobuf:"bytes,9,opt,name=load_mode,json=loadMode,proto3" json:"load_mode,omitempty"`
	DataToken     string `protobuf:"bytes,10,opt,name=data_token,json=dataToken,proto3" json:"data_token,omitempty"`
	Currency      string `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderType     int32  `protobuf:"varint,12,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	BankId        int64  `protobuf:"varint,13,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsReq) Reset() {
	*x = GetStatisticsReq{}
	mi := &file_statistics_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsReq) ProtoMessage() {}

func (x *GetStatisticsReq) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsReq.ProtoReflect.Descriptor instead.
func (*GetStatisticsReq) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatisticsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetStatisticsReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetStatisticsReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GetStatisticsReq) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *GetStatisticsReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetStatisticsReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetStatisticsReq) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *GetStatisticsReq) GetBankIdentifier() string {
	if x != nil {
		return x.BankIdentifier
	}
	return ""
}

func (x *GetStatisticsReq) GetLoadMode() string {
	if x != nil {
		return x.LoadMode
	}
	return ""
}

func (x *GetStatisticsReq) GetDataToken() string {
	if x != nil {
		return x.DataToken
	}
	return ""
}

func (x *GetStatisticsReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetStatisticsReq) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *GetStatisticsReq) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

// get statistics merchant list resp
type GetStatisticsMerchantListResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         int64                     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	DataToken     string                    `protobuf:"bytes,2,opt,name=data_token,json=dataToken,proto3" json:"data_token,omitempty"`
	List          []*StatisticsMerchantInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsMerchantListResp) Reset() {
	*x = GetStatisticsMerchantListResp{}
	mi := &file_statistics_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsMerchantListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsMerchantListResp) ProtoMessage() {}

func (x *GetStatisticsMerchantListResp) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsMerchantListResp.ProtoReflect.Descriptor instead.
func (*GetStatisticsMerchantListResp) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatisticsMerchantListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetStatisticsMerchantListResp) GetDataToken() string {
	if x != nil {
		return x.DataToken
	}
	return ""
}

func (x *GetStatisticsMerchantListResp) GetList() []*StatisticsMerchantInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type StatisticsMerchantInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantName               string                 `protobuf:"bytes,2,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	MerchantId                 int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SuccessTotalCount          int64                  `protobuf:"varint,4,opt,name=success_total_count,json=successTotalCount,proto3" json:"success_total_count,omitempty"`
	OrderTotalCount            int64                  `protobuf:"varint,5,opt,name=order_total_count,json=orderTotalCount,proto3" json:"order_total_count,omitempty"`
	OrderTotalAmount           int64                  `protobuf:"varint,6,opt,name=order_total_amount,json=orderTotalAmount,proto3" json:"order_total_amount,omitempty"`
	SuccessTotalAmount         int64                  `protobuf:"varint,7,opt,name=success_total_amount,json=successTotalAmount,proto3" json:"success_total_amount,omitempty"`
	SuccessRate                float64                `protobuf:"fixed64,8,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	ProcessingOrderTotalCount  int64                  `protobuf:"varint,9,opt,name=processing_order_total_count,json=processingOrderTotalCount,proto3" json:"processing_order_total_count,omitempty"`
	ProcessingOrderTotalAmount int64                  `protobuf:"varint,10,opt,name=processing_order_total_amount,json=processingOrderTotalAmount,proto3" json:"processing_order_total_amount,omitempty"`
	FailedOrderTotalCount      int64                  `protobuf:"varint,11,opt,name=failed_order_total_count,json=failedOrderTotalCount,proto3" json:"failed_order_total_count,omitempty"`
	FailedOrderTotalAmount     int64                  `protobuf:"varint,12,opt,name=failed_order_total_amount,json=failedOrderTotalAmount,proto3" json:"failed_order_total_amount,omitempty"`
	RefundedOrderCount         int64                  `protobuf:"varint,13,opt,name=refunded_order_count,json=refundedOrderCount,proto3" json:"refunded_order_count,omitempty"`
	RefundedOrderTotalAmount   int64                  `protobuf:"varint,14,opt,name=refunded_order_total_amount,json=refundedOrderTotalAmount,proto3" json:"refunded_order_total_amount,omitempty"`
	RefundedOrderRate          float64                `protobuf:"fixed64,15,opt,name=refunded_order_rate,json=refundedOrderRate,proto3" json:"refunded_order_rate,omitempty"`
	UnsettledAmount            int64                  `protobuf:"varint,16,opt,name=unsettled_amount,json=unsettledAmount,proto3" json:"unsettled_amount,omitempty"`
	FrozenAmount               int64                  `protobuf:"varint,17,opt,name=frozen_amount,json=frozenAmount,proto3" json:"frozen_amount,omitempty"`
	DataDate                   string                 `protobuf:"bytes,18,opt,name=data_date,json=dataDate,proto3" json:"data_date,omitempty"` // unix timestamp
	Currency                   string                 `protobuf:"bytes,19,opt,name=currency,proto3" json:"currency,omitempty"`
	Week                       int32                  `protobuf:"varint,20,opt,name=week,proto3" json:"week,omitempty"`
	FailedRate                 float64                `protobuf:"fixed64,21,opt,name=failed_rate,json=failedRate,proto3" json:"failed_rate,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StatisticsMerchantInfo) Reset() {
	*x = StatisticsMerchantInfo{}
	mi := &file_statistics_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsMerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsMerchantInfo) ProtoMessage() {}

func (x *StatisticsMerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsMerchantInfo.ProtoReflect.Descriptor instead.
func (*StatisticsMerchantInfo) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *StatisticsMerchantInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *StatisticsMerchantInfo) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetSuccessTotalCount() int64 {
	if x != nil {
		return x.SuccessTotalCount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetOrderTotalCount() int64 {
	if x != nil {
		return x.OrderTotalCount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetOrderTotalAmount() int64 {
	if x != nil {
		return x.OrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetSuccessTotalAmount() int64 {
	if x != nil {
		return x.SuccessTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetFailedOrderTotalCount() int64 {
	if x != nil {
		return x.FailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.FailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetRefundedOrderCount() int64 {
	if x != nil {
		return x.RefundedOrderCount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.RefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetRefundedOrderRate() float64 {
	if x != nil {
		return x.RefundedOrderRate
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetUnsettledAmount() int64 {
	if x != nil {
		return x.UnsettledAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetFrozenAmount() int64 {
	if x != nil {
		return x.FrozenAmount
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetDataDate() string {
	if x != nil {
		return x.DataDate
	}
	return ""
}

func (x *StatisticsMerchantInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StatisticsMerchantInfo) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StatisticsMerchantInfo) GetFailedRate() float64 {
	if x != nil {
		return x.FailedRate
	}
	return 0
}

// get statistics merchant trade type list resp
type GetStatisticsMerchantTradeTypeListResp struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Total         int64                              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*StatisticsMerchantTradeTypeInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	DataToken     string                             `protobuf:"bytes,3,opt,name=data_token,json=dataToken,proto3" json:"data_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsMerchantTradeTypeListResp) Reset() {
	*x = GetStatisticsMerchantTradeTypeListResp{}
	mi := &file_statistics_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsMerchantTradeTypeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsMerchantTradeTypeListResp) ProtoMessage() {}

func (x *GetStatisticsMerchantTradeTypeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsMerchantTradeTypeListResp.ProtoReflect.Descriptor instead.
func (*GetStatisticsMerchantTradeTypeListResp) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatisticsMerchantTradeTypeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetStatisticsMerchantTradeTypeListResp) GetList() []*StatisticsMerchantTradeTypeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetStatisticsMerchantTradeTypeListResp) GetDataToken() string {
	if x != nil {
		return x.DataToken
	}
	return ""
}

type StatisticsMerchantTradeTypeInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantName               string                 `protobuf:"bytes,2,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	MerchantId                 int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency                   string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionInstructionType int32                  `protobuf:"varint,5,opt,name=transaction_instruction_type,json=transactionInstructionType,proto3" json:"transaction_instruction_type,omitempty"`
	OrderTotalCount            int64                  `protobuf:"varint,6,opt,name=order_total_count,json=orderTotalCount,proto3" json:"order_total_count,omitempty"`
	OrderTotalAmount           int64                  `protobuf:"varint,7,opt,name=order_total_amount,json=orderTotalAmount,proto3" json:"order_total_amount,omitempty"`
	SuccessTotalCount          int64                  `protobuf:"varint,8,opt,name=success_total_count,json=successTotalCount,proto3" json:"success_total_count,omitempty"`
	SuccessTotalAmount         int64                  `protobuf:"varint,9,opt,name=success_total_amount,json=successTotalAmount,proto3" json:"success_total_amount,omitempty"`
	SuccessRate                float64                `protobuf:"fixed64,10,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	ProcessingOrderTotalCount  int64                  `protobuf:"varint,11,opt,name=processing_order_total_count,json=processingOrderTotalCount,proto3" json:"processing_order_total_count,omitempty"`
	ProcessingOrderTotalAmount int64                  `protobuf:"varint,12,opt,name=processing_order_total_amount,json=processingOrderTotalAmount,proto3" json:"processing_order_total_amount,omitempty"`
	FailedOrderTotalCount      int64                  `protobuf:"varint,13,opt,name=failed_order_total_count,json=failedOrderTotalCount,proto3" json:"failed_order_total_count,omitempty"`
	FailedOrderTotalAmount     int64                  `protobuf:"varint,14,opt,name=failed_order_total_amount,json=failedOrderTotalAmount,proto3" json:"failed_order_total_amount,omitempty"`
	RefundedOrderCount         int64                  `protobuf:"varint,15,opt,name=refunded_order_count,json=refundedOrderCount,proto3" json:"refunded_order_count,omitempty"`
	RefundedOrderTotalAmount   int64                  `protobuf:"varint,16,opt,name=refunded_order_total_amount,json=refundedOrderTotalAmount,proto3" json:"refunded_order_total_amount,omitempty"`
	RefundedOrderRate          float64                `protobuf:"fixed64,17,opt,name=refunded_order_rate,json=refundedOrderRate,proto3" json:"refunded_order_rate,omitempty"`
	UnsettledAmount            int64                  `protobuf:"varint,18,opt,name=unsettled_amount,json=unsettledAmount,proto3" json:"unsettled_amount,omitempty"`
	FrozenAmount               int64                  `protobuf:"varint,19,opt,name=frozen_amount,json=frozenAmount,proto3" json:"frozen_amount,omitempty"`
	OrderType                  int32                  `protobuf:"varint,20,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	DataDate                   string                 `protobuf:"bytes,21,opt,name=data_date,json=dataDate,proto3" json:"data_date,omitempty"` // unix timestamp
	Week                       int32                  `protobuf:"varint,22,opt,name=week,proto3" json:"week,omitempty"`
	FailedRate                 float64                `protobuf:"fixed64,23,opt,name=failed_rate,json=failedRate,proto3" json:"failed_rate,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StatisticsMerchantTradeTypeInfo) Reset() {
	*x = StatisticsMerchantTradeTypeInfo{}
	mi := &file_statistics_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsMerchantTradeTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsMerchantTradeTypeInfo) ProtoMessage() {}

func (x *StatisticsMerchantTradeTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsMerchantTradeTypeInfo.ProtoReflect.Descriptor instead.
func (*StatisticsMerchantTradeTypeInfo) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *StatisticsMerchantTradeTypeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *StatisticsMerchantTradeTypeInfo) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StatisticsMerchantTradeTypeInfo) GetTransactionInstructionType() int32 {
	if x != nil {
		return x.TransactionInstructionType
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetOrderTotalCount() int64 {
	if x != nil {
		return x.OrderTotalCount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetOrderTotalAmount() int64 {
	if x != nil {
		return x.OrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetSuccessTotalCount() int64 {
	if x != nil {
		return x.SuccessTotalCount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetSuccessTotalAmount() int64 {
	if x != nil {
		return x.SuccessTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetFailedOrderTotalCount() int64 {
	if x != nil {
		return x.FailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.FailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetRefundedOrderCount() int64 {
	if x != nil {
		return x.RefundedOrderCount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.RefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetRefundedOrderRate() float64 {
	if x != nil {
		return x.RefundedOrderRate
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetUnsettledAmount() int64 {
	if x != nil {
		return x.UnsettledAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetFrozenAmount() int64 {
	if x != nil {
		return x.FrozenAmount
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetDataDate() string {
	if x != nil {
		return x.DataDate
	}
	return ""
}

func (x *StatisticsMerchantTradeTypeInfo) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StatisticsMerchantTradeTypeInfo) GetFailedRate() float64 {
	if x != nil {
		return x.FailedRate
	}
	return 0
}

// get statistics bank list resp
type GetStatisticsBankListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*StatisticsBankInfo  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	DataToken     string                 `protobuf:"bytes,3,opt,name=data_token,json=dataToken,proto3" json:"data_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsBankListResp) Reset() {
	*x = GetStatisticsBankListResp{}
	mi := &file_statistics_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsBankListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsBankListResp) ProtoMessage() {}

func (x *GetStatisticsBankListResp) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsBankListResp.ProtoReflect.Descriptor instead.
func (*GetStatisticsBankListResp) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatisticsBankListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetStatisticsBankListResp) GetList() []*StatisticsBankInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetStatisticsBankListResp) GetDataToken() string {
	if x != nil {
		return x.DataToken
	}
	return ""
}

type StatisticsBankInfo struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Id                             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BankId                         int64                  `protobuf:"varint,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	BankName                       string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankIdentifier                 string                 `protobuf:"bytes,4,opt,name=bank_identifier,json=bankIdentifier,proto3" json:"bank_identifier,omitempty"`
	Currency                       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderTotalAmount               int64                  `protobuf:"varint,6,opt,name=order_total_amount,json=orderTotalAmount,proto3" json:"order_total_amount,omitempty"`
	OrderTotalCount                int64                  `protobuf:"varint,7,opt,name=order_total_count,json=orderTotalCount,proto3" json:"order_total_count,omitempty"`
	SuccessTotalCount              int64                  `protobuf:"varint,8,opt,name=success_total_count,json=successTotalCount,proto3" json:"success_total_count,omitempty"`
	SuccessTotalAmount             int64                  `protobuf:"varint,9,opt,name=success_total_amount,json=successTotalAmount,proto3" json:"success_total_amount,omitempty"`
	SuccessRate                    float64                `protobuf:"fixed64,10,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	ProcessingOrderTotalCount      int64                  `protobuf:"varint,11,opt,name=processing_order_total_count,json=processingOrderTotalCount,proto3" json:"processing_order_total_count,omitempty"`
	ProcessingOrderTotalAmount     int64                  `protobuf:"varint,12,opt,name=processing_order_total_amount,json=processingOrderTotalAmount,proto3" json:"processing_order_total_amount,omitempty"`
	FailedOrderTotalCount          int64                  `protobuf:"varint,13,opt,name=failed_order_total_count,json=failedOrderTotalCount,proto3" json:"failed_order_total_count,omitempty"`
	FailedOrderTotalAmount         int64                  `protobuf:"varint,14,opt,name=failed_order_total_amount,json=failedOrderTotalAmount,proto3" json:"failed_order_total_amount,omitempty"`
	RefundedOrderCount             int64                  `protobuf:"varint,15,opt,name=refunded_order_count,json=refundedOrderCount,proto3" json:"refunded_order_count,omitempty"`
	RefundedOrderTotalAmount       int64                  `protobuf:"varint,16,opt,name=refunded_order_total_amount,json=refundedOrderTotalAmount,proto3" json:"refunded_order_total_amount,omitempty"`
	RefundedOrderRate              float64                `protobuf:"fixed64,17,opt,name=refunded_order_rate,json=refundedOrderRate,proto3" json:"refunded_order_rate,omitempty"`
	BankOrderTotalAmount           int64                  `protobuf:"varint,18,opt,name=bank_order_total_amount,json=bankOrderTotalAmount,proto3" json:"bank_order_total_amount,omitempty"`
	BankOrderTotalCount            int64                  `protobuf:"varint,19,opt,name=bank_order_total_count,json=bankOrderTotalCount,proto3" json:"bank_order_total_count,omitempty"`
	BankSuccessTotalCount          int64                  `protobuf:"varint,20,opt,name=bank_success_total_count,json=bankSuccessTotalCount,proto3" json:"bank_success_total_count,omitempty"`
	BankSuccessTotalAmount         int64                  `protobuf:"varint,21,opt,name=bank_success_total_amount,json=bankSuccessTotalAmount,proto3" json:"bank_success_total_amount,omitempty"`
	BankSuccessRate                float64                `protobuf:"fixed64,22,opt,name=bank_success_rate,json=bankSuccessRate,proto3" json:"bank_success_rate,omitempty"`
	BankProcessingOrderTotalCount  int64                  `protobuf:"varint,23,opt,name=bank_processing_order_total_count,json=bankProcessingOrderTotalCount,proto3" json:"bank_processing_order_total_count,omitempty"`
	BankProcessingOrderTotalAmount int64                  `protobuf:"varint,24,opt,name=bank_processing_order_total_amount,json=bankProcessingOrderTotalAmount,proto3" json:"bank_processing_order_total_amount,omitempty"`
	BankFailedOrderTotalCount      int64                  `protobuf:"varint,25,opt,name=bank_failed_order_total_count,json=bankFailedOrderTotalCount,proto3" json:"bank_failed_order_total_count,omitempty"`
	BankFailedOrderTotalAmount     int64                  `protobuf:"varint,26,opt,name=bank_failed_order_total_amount,json=bankFailedOrderTotalAmount,proto3" json:"bank_failed_order_total_amount,omitempty"`
	BankRefundedOrderCount         int64                  `protobuf:"varint,27,opt,name=bank_refunded_order_count,json=bankRefundedOrderCount,proto3" json:"bank_refunded_order_count,omitempty"`
	BankRefundedOrderTotalAmount   int64                  `protobuf:"varint,28,opt,name=bank_refunded_order_total_amount,json=bankRefundedOrderTotalAmount,proto3" json:"bank_refunded_order_total_amount,omitempty"`
	BankRefundedOrderRate          float64                `protobuf:"fixed64,29,opt,name=bank_refunded_order_rate,json=bankRefundedOrderRate,proto3" json:"bank_refunded_order_rate,omitempty"`
	OrderType                      int32                  `protobuf:"varint,30,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	DataDate                       string                 `protobuf:"bytes,31,opt,name=data_date,json=dataDate,proto3" json:"data_date,omitempty"` // unix timestamp
	BankUnknownOrderCount          int64                  `protobuf:"varint,32,opt,name=bank_unknown_order_count,json=bankUnknownOrderCount,proto3" json:"bank_unknown_order_count,omitempty"`
	BankUnknownOrderAmount         int64                  `protobuf:"varint,33,opt,name=bank_unknown_order_amount,json=bankUnknownOrderAmount,proto3" json:"bank_unknown_order_amount,omitempty"`
	Week                           int32                  `protobuf:"varint,34,opt,name=week,proto3" json:"week,omitempty"`
	FailedRate                     float64                `protobuf:"fixed64,35,opt,name=failed_rate,json=failedRate,proto3" json:"failed_rate,omitempty"`
	BankFailedRate                 float64                `protobuf:"fixed64,36,opt,name=bank_failed_rate,json=bankFailedRate,proto3" json:"bank_failed_rate,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *StatisticsBankInfo) Reset() {
	*x = StatisticsBankInfo{}
	mi := &file_statistics_statistics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsBankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsBankInfo) ProtoMessage() {}

func (x *StatisticsBankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsBankInfo.ProtoReflect.Descriptor instead.
func (*StatisticsBankInfo) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{6}
}

func (x *StatisticsBankInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *StatisticsBankInfo) GetBankIdentifier() string {
	if x != nil {
		return x.BankIdentifier
	}
	return ""
}

func (x *StatisticsBankInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StatisticsBankInfo) GetOrderTotalAmount() int64 {
	if x != nil {
		return x.OrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetOrderTotalCount() int64 {
	if x != nil {
		return x.OrderTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetSuccessTotalCount() int64 {
	if x != nil {
		return x.SuccessTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetSuccessTotalAmount() int64 {
	if x != nil {
		return x.SuccessTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *StatisticsBankInfo) GetProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetFailedOrderTotalCount() int64 {
	if x != nil {
		return x.FailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.FailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetRefundedOrderCount() int64 {
	if x != nil {
		return x.RefundedOrderCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.RefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetRefundedOrderRate() float64 {
	if x != nil {
		return x.RefundedOrderRate
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankOrderTotalAmount() int64 {
	if x != nil {
		return x.BankOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankOrderTotalCount() int64 {
	if x != nil {
		return x.BankOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankSuccessTotalCount() int64 {
	if x != nil {
		return x.BankSuccessTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankSuccessTotalAmount() int64 {
	if x != nil {
		return x.BankSuccessTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankSuccessRate() float64 {
	if x != nil {
		return x.BankSuccessRate
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.BankProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.BankProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankFailedOrderTotalCount() int64 {
	if x != nil {
		return x.BankFailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.BankFailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankRefundedOrderCount() int64 {
	if x != nil {
		return x.BankRefundedOrderCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.BankRefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankRefundedOrderRate() float64 {
	if x != nil {
		return x.BankRefundedOrderRate
	}
	return 0
}

func (x *StatisticsBankInfo) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *StatisticsBankInfo) GetDataDate() string {
	if x != nil {
		return x.DataDate
	}
	return ""
}

func (x *StatisticsBankInfo) GetBankUnknownOrderCount() int64 {
	if x != nil {
		return x.BankUnknownOrderCount
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankUnknownOrderAmount() int64 {
	if x != nil {
		return x.BankUnknownOrderAmount
	}
	return 0
}

func (x *StatisticsBankInfo) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StatisticsBankInfo) GetFailedRate() float64 {
	if x != nil {
		return x.FailedRate
	}
	return 0
}

func (x *StatisticsBankInfo) GetBankFailedRate() float64 {
	if x != nil {
		return x.BankFailedRate
	}
	return 0
}

// get statistics bank trade type list resp
type GetStatisticsBankTradeTypeListResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Total         int64                          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*StatisticsBankTradeTypeInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	DataToken     string                         `protobuf:"bytes,3,opt,name=data_token,json=dataToken,proto3" json:"data_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsBankTradeTypeListResp) Reset() {
	*x = GetStatisticsBankTradeTypeListResp{}
	mi := &file_statistics_statistics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsBankTradeTypeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsBankTradeTypeListResp) ProtoMessage() {}

func (x *GetStatisticsBankTradeTypeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsBankTradeTypeListResp.ProtoReflect.Descriptor instead.
func (*GetStatisticsBankTradeTypeListResp) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatisticsBankTradeTypeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetStatisticsBankTradeTypeListResp) GetList() []*StatisticsBankTradeTypeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetStatisticsBankTradeTypeListResp) GetDataToken() string {
	if x != nil {
		return x.DataToken
	}
	return ""
}

type StatisticsBankTradeTypeInfo struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Id                             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BankId                         int64                  `protobuf:"varint,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	BankName                       string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankIdentifier                 string                 `protobuf:"bytes,4,opt,name=bank_identifier,json=bankIdentifier,proto3" json:"bank_identifier,omitempty"`
	Currency                       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionInstructionType     int32                  `protobuf:"varint,6,opt,name=transaction_instruction_type,json=transactionInstructionType,proto3" json:"transaction_instruction_type,omitempty"`
	OrderTotalAmount               int64                  `protobuf:"varint,7,opt,name=order_total_amount,json=orderTotalAmount,proto3" json:"order_total_amount,omitempty"`
	OrderTotalCount                int64                  `protobuf:"varint,8,opt,name=order_total_count,json=orderTotalCount,proto3" json:"order_total_count,omitempty"`
	SuccessTotalCount              int64                  `protobuf:"varint,9,opt,name=success_total_count,json=successTotalCount,proto3" json:"success_total_count,omitempty"`
	SuccessTotalAmount             int64                  `protobuf:"varint,10,opt,name=success_total_amount,json=successTotalAmount,proto3" json:"success_total_amount,omitempty"`
	SuccessRate                    float64                `protobuf:"fixed64,11,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	ProcessingOrderTotalCount      int64                  `protobuf:"varint,12,opt,name=processing_order_total_count,json=processingOrderTotalCount,proto3" json:"processing_order_total_count,omitempty"`
	ProcessingOrderTotalAmount     int64                  `protobuf:"varint,13,opt,name=processing_order_total_amount,json=processingOrderTotalAmount,proto3" json:"processing_order_total_amount,omitempty"`
	FailedOrderTotalCount          int64                  `protobuf:"varint,14,opt,name=failed_order_total_count,json=failedOrderTotalCount,proto3" json:"failed_order_total_count,omitempty"`
	FailedOrderTotalAmount         int64                  `protobuf:"varint,15,opt,name=failed_order_total_amount,json=failedOrderTotalAmount,proto3" json:"failed_order_total_amount,omitempty"`
	RefundedOrderCount             int64                  `protobuf:"varint,16,opt,name=refunded_order_count,json=refundedOrderCount,proto3" json:"refunded_order_count,omitempty"`
	RefundedOrderTotalAmount       int64                  `protobuf:"varint,17,opt,name=refunded_order_total_amount,json=refundedOrderTotalAmount,proto3" json:"refunded_order_total_amount,omitempty"`
	RefundedOrderRate              float64                `protobuf:"fixed64,18,opt,name=refunded_order_rate,json=refundedOrderRate,proto3" json:"refunded_order_rate,omitempty"`
	BankOrderTotalAmount           int64                  `protobuf:"varint,19,opt,name=bank_order_total_amount,json=bankOrderTotalAmount,proto3" json:"bank_order_total_amount,omitempty"`
	BankOrderTotalCount            int64                  `protobuf:"varint,20,opt,name=bank_order_total_count,json=bankOrderTotalCount,proto3" json:"bank_order_total_count,omitempty"`
	BankSuccessTotalCount          int64                  `protobuf:"varint,21,opt,name=bank_success_total_count,json=bankSuccessTotalCount,proto3" json:"bank_success_total_count,omitempty"`
	BankSuccessTotalAmount         int64                  `protobuf:"varint,22,opt,name=bank_success_total_amount,json=bankSuccessTotalAmount,proto3" json:"bank_success_total_amount,omitempty"`
	BankSuccessRate                float64                `protobuf:"fixed64,23,opt,name=bank_success_rate,json=bankSuccessRate,proto3" json:"bank_success_rate,omitempty"`
	BankProcessingOrderTotalCount  int64                  `protobuf:"varint,24,opt,name=bank_processing_order_total_count,json=bankProcessingOrderTotalCount,proto3" json:"bank_processing_order_total_count,omitempty"`
	BankProcessingOrderTotalAmount int64                  `protobuf:"varint,25,opt,name=bank_processing_order_total_amount,json=bankProcessingOrderTotalAmount,proto3" json:"bank_processing_order_total_amount,omitempty"`
	BankFailedOrderTotalCount      int64                  `protobuf:"varint,26,opt,name=bank_failed_order_total_count,json=bankFailedOrderTotalCount,proto3" json:"bank_failed_order_total_count,omitempty"`
	BankFailedOrderTotalAmount     int64                  `protobuf:"varint,27,opt,name=bank_failed_order_total_amount,json=bankFailedOrderTotalAmount,proto3" json:"bank_failed_order_total_amount,omitempty"`
	BankRefundedOrderCount         int64                  `protobuf:"varint,28,opt,name=bank_refunded_order_count,json=bankRefundedOrderCount,proto3" json:"bank_refunded_order_count,omitempty"`
	BankRefundedOrderTotalAmount   int64                  `protobuf:"varint,29,opt,name=bank_refunded_order_total_amount,json=bankRefundedOrderTotalAmount,proto3" json:"bank_refunded_order_total_amount,omitempty"`
	BankRefundedOrderRate          float64                `protobuf:"fixed64,30,opt,name=bank_refunded_order_rate,json=bankRefundedOrderRate,proto3" json:"bank_refunded_order_rate,omitempty"`
	OrderType                      int32                  `protobuf:"varint,31,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	DataDate                       string                 `protobuf:"bytes,32,opt,name=data_date,json=dataDate,proto3" json:"data_date,omitempty"` // unix timestamp
	BankUnknownOrderCount          int64                  `protobuf:"varint,33,opt,name=bank_unknown_order_count,json=bankUnknownOrderCount,proto3" json:"bank_unknown_order_count,omitempty"`
	BankUnknownOrderAmount         int64                  `protobuf:"varint,34,opt,name=bank_unknown_order_amount,json=bankUnknownOrderAmount,proto3" json:"bank_unknown_order_amount,omitempty"`
	Week                           int32                  `protobuf:"varint,35,opt,name=week,proto3" json:"week,omitempty"`
	FailedRate                     float64                `protobuf:"fixed64,36,opt,name=failed_rate,json=failedRate,proto3" json:"failed_rate,omitempty"`
	BankFailedRate                 float64                `protobuf:"fixed64,37,opt,name=bank_failed_rate,json=bankFailedRate,proto3" json:"bank_failed_rate,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *StatisticsBankTradeTypeInfo) Reset() {
	*x = StatisticsBankTradeTypeInfo{}
	mi := &file_statistics_statistics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsBankTradeTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsBankTradeTypeInfo) ProtoMessage() {}

func (x *StatisticsBankTradeTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsBankTradeTypeInfo.ProtoReflect.Descriptor instead.
func (*StatisticsBankTradeTypeInfo) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{8}
}

func (x *StatisticsBankTradeTypeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *StatisticsBankTradeTypeInfo) GetBankIdentifier() string {
	if x != nil {
		return x.BankIdentifier
	}
	return ""
}

func (x *StatisticsBankTradeTypeInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StatisticsBankTradeTypeInfo) GetTransactionInstructionType() int32 {
	if x != nil {
		return x.TransactionInstructionType
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetOrderTotalAmount() int64 {
	if x != nil {
		return x.OrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetOrderTotalCount() int64 {
	if x != nil {
		return x.OrderTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetSuccessTotalCount() int64 {
	if x != nil {
		return x.SuccessTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetSuccessTotalAmount() int64 {
	if x != nil {
		return x.SuccessTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetFailedOrderTotalCount() int64 {
	if x != nil {
		return x.FailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.FailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetRefundedOrderCount() int64 {
	if x != nil {
		return x.RefundedOrderCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.RefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetRefundedOrderRate() float64 {
	if x != nil {
		return x.RefundedOrderRate
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankOrderTotalAmount() int64 {
	if x != nil {
		return x.BankOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankOrderTotalCount() int64 {
	if x != nil {
		return x.BankOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankSuccessTotalCount() int64 {
	if x != nil {
		return x.BankSuccessTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankSuccessTotalAmount() int64 {
	if x != nil {
		return x.BankSuccessTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankSuccessRate() float64 {
	if x != nil {
		return x.BankSuccessRate
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.BankProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.BankProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankFailedOrderTotalCount() int64 {
	if x != nil {
		return x.BankFailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.BankFailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankRefundedOrderCount() int64 {
	if x != nil {
		return x.BankRefundedOrderCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.BankRefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankRefundedOrderRate() float64 {
	if x != nil {
		return x.BankRefundedOrderRate
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetDataDate() string {
	if x != nil {
		return x.DataDate
	}
	return ""
}

func (x *StatisticsBankTradeTypeInfo) GetBankUnknownOrderCount() int64 {
	if x != nil {
		return x.BankUnknownOrderCount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankUnknownOrderAmount() int64 {
	if x != nil {
		return x.BankUnknownOrderAmount
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetFailedRate() float64 {
	if x != nil {
		return x.FailedRate
	}
	return 0
}

func (x *StatisticsBankTradeTypeInfo) GetBankFailedRate() float64 {
	if x != nil {
		return x.BankFailedRate
	}
	return 0
}

// get statistics trade type list resp
type GetStatisticsTradeTypeListResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Total         int64                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*StatisticsTradeTypeInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	DataToken     string                     `protobuf:"bytes,3,opt,name=data_token,json=dataToken,proto3" json:"data_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsTradeTypeListResp) Reset() {
	*x = GetStatisticsTradeTypeListResp{}
	mi := &file_statistics_statistics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsTradeTypeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsTradeTypeListResp) ProtoMessage() {}

func (x *GetStatisticsTradeTypeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsTradeTypeListResp.ProtoReflect.Descriptor instead.
func (*GetStatisticsTradeTypeListResp) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatisticsTradeTypeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetStatisticsTradeTypeListResp) GetList() []*StatisticsTradeTypeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetStatisticsTradeTypeListResp) GetDataToken() string {
	if x != nil {
		return x.DataToken
	}
	return ""
}

type StatisticsTradeTypeInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionInstructionType int32                  `protobuf:"varint,2,opt,name=transaction_instruction_type,json=transactionInstructionType,proto3" json:"transaction_instruction_type,omitempty"`
	Currency                   string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderTotalCount            int64                  `protobuf:"varint,4,opt,name=order_total_count,json=orderTotalCount,proto3" json:"order_total_count,omitempty"`
	OrderTotalAmount           int64                  `protobuf:"varint,5,opt,name=order_total_amount,json=orderTotalAmount,proto3" json:"order_total_amount,omitempty"`
	SuccessTotalCount          int64                  `protobuf:"varint,6,opt,name=success_total_count,json=successTotalCount,proto3" json:"success_total_count,omitempty"`
	SuccessTotalAmount         int64                  `protobuf:"varint,7,opt,name=success_total_amount,json=successTotalAmount,proto3" json:"success_total_amount,omitempty"`
	SuccessRate                float64                `protobuf:"fixed64,8,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	ProcessingOrderTotalCount  int64                  `protobuf:"varint,9,opt,name=processing_order_total_count,json=processingOrderTotalCount,proto3" json:"processing_order_total_count,omitempty"`
	ProcessingOrderTotalAmount int64                  `protobuf:"varint,10,opt,name=processing_order_total_amount,json=processingOrderTotalAmount,proto3" json:"processing_order_total_amount,omitempty"`
	FailedOrderTotalCount      int64                  `protobuf:"varint,11,opt,name=failed_order_total_count,json=failedOrderTotalCount,proto3" json:"failed_order_total_count,omitempty"`
	FailedOrderTotalAmount     int64                  `protobuf:"varint,12,opt,name=failed_order_total_amount,json=failedOrderTotalAmount,proto3" json:"failed_order_total_amount,omitempty"`
	RefundedOrderCount         int64                  `protobuf:"varint,13,opt,name=refunded_order_count,json=refundedOrderCount,proto3" json:"refunded_order_count,omitempty"`
	RefundedOrderTotalAmount   int64                  `protobuf:"varint,14,opt,name=refunded_order_total_amount,json=refundedOrderTotalAmount,proto3" json:"refunded_order_total_amount,omitempty"`
	RefundedOrderRate          float64                `protobuf:"fixed64,15,opt,name=refunded_order_rate,json=refundedOrderRate,proto3" json:"refunded_order_rate,omitempty"`
	UnsettledAmount            int64                  `protobuf:"varint,16,opt,name=unsettled_amount,json=unsettledAmount,proto3" json:"unsettled_amount,omitempty"`
	FrozenAmount               int64                  `protobuf:"varint,17,opt,name=frozen_amount,json=frozenAmount,proto3" json:"frozen_amount,omitempty"`
	OrderType                  int32                  `protobuf:"varint,18,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	DataDate                   string                 `protobuf:"bytes,19,opt,name=data_date,json=dataDate,proto3" json:"data_date,omitempty"` // unix timestamp
	Week                       int32                  `protobuf:"varint,20,opt,name=week,proto3" json:"week,omitempty"`
	FailedRate                 float64                `protobuf:"fixed64,21,opt,name=failed_rate,json=failedRate,proto3" json:"failed_rate,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StatisticsTradeTypeInfo) Reset() {
	*x = StatisticsTradeTypeInfo{}
	mi := &file_statistics_statistics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsTradeTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsTradeTypeInfo) ProtoMessage() {}

func (x *StatisticsTradeTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsTradeTypeInfo.ProtoReflect.Descriptor instead.
func (*StatisticsTradeTypeInfo) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{10}
}

func (x *StatisticsTradeTypeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetTransactionInstructionType() int32 {
	if x != nil {
		return x.TransactionInstructionType
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StatisticsTradeTypeInfo) GetOrderTotalCount() int64 {
	if x != nil {
		return x.OrderTotalCount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetOrderTotalAmount() int64 {
	if x != nil {
		return x.OrderTotalAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetSuccessTotalCount() int64 {
	if x != nil {
		return x.SuccessTotalCount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetSuccessTotalAmount() int64 {
	if x != nil {
		return x.SuccessTotalAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetProcessingOrderTotalCount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalCount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetProcessingOrderTotalAmount() int64 {
	if x != nil {
		return x.ProcessingOrderTotalAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetFailedOrderTotalCount() int64 {
	if x != nil {
		return x.FailedOrderTotalCount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetFailedOrderTotalAmount() int64 {
	if x != nil {
		return x.FailedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetRefundedOrderCount() int64 {
	if x != nil {
		return x.RefundedOrderCount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetRefundedOrderTotalAmount() int64 {
	if x != nil {
		return x.RefundedOrderTotalAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetRefundedOrderRate() float64 {
	if x != nil {
		return x.RefundedOrderRate
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetUnsettledAmount() int64 {
	if x != nil {
		return x.UnsettledAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetFrozenAmount() int64 {
	if x != nil {
		return x.FrozenAmount
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetDataDate() string {
	if x != nil {
		return x.DataDate
	}
	return ""
}

func (x *StatisticsTradeTypeInfo) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StatisticsTradeTypeInfo) GetFailedRate() float64 {
	if x != nil {
		return x.FailedRate
	}
	return 0
}

var File_statistics_statistics_proto protoreflect.FileDescriptor

const file_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"\x1bstatistics/statistics.proto\x12\x02pb\"\x90\x03\n" +
	"\x10GetStatisticsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x04 \x01(\tR\fmerchantName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1b\n" +
	"\tbank_name\x18\a \x01(\tR\bbankName\x12'\n" +
	"\x0fbank_identifier\x18\b \x01(\tR\x0ebankIdentifier\x12\x1b\n" +
	"\tload_mode\x18\t \x01(\tR\bloadMode\x12\x1d\n" +
	"\n" +
	"data_token\x18\n" +
	" \x01(\tR\tdataToken\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"order_type\x18\f \x01(\x05R\torderType\x12\x17\n" +
	"\abank_id\x18\r \x01(\x03R\x06bankId\"\x84\x01\n" +
	"\x1dGetStatisticsMerchantListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"data_token\x18\x02 \x01(\tR\tdataToken\x12.\n" +
	"\x04list\x18\x03 \x03(\v2\x1a.pb.StatisticsMerchantInfoR\x04list\"\xa4\a\n" +
	"\x16StatisticsMerchantInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rmerchant_name\x18\x02 \x01(\tR\fmerchantName\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12.\n" +
	"\x13success_total_count\x18\x04 \x01(\x03R\x11successTotalCount\x12*\n" +
	"\x11order_total_count\x18\x05 \x01(\x03R\x0forderTotalCount\x12,\n" +
	"\x12order_total_amount\x18\x06 \x01(\x03R\x10orderTotalAmount\x120\n" +
	"\x14success_total_amount\x18\a \x01(\x03R\x12successTotalAmount\x12!\n" +
	"\fsuccess_rate\x18\b \x01(\x01R\vsuccessRate\x12?\n" +
	"\x1cprocessing_order_total_count\x18\t \x01(\x03R\x19processingOrderTotalCount\x12A\n" +
	"\x1dprocessing_order_total_amount\x18\n" +
	" \x01(\x03R\x1aprocessingOrderTotalAmount\x127\n" +
	"\x18failed_order_total_count\x18\v \x01(\x03R\x15failedOrderTotalCount\x129\n" +
	"\x19failed_order_total_amount\x18\f \x01(\x03R\x16failedOrderTotalAmount\x120\n" +
	"\x14refunded_order_count\x18\r \x01(\x03R\x12refundedOrderCount\x12=\n" +
	"\x1brefunded_order_total_amount\x18\x0e \x01(\x03R\x18refundedOrderTotalAmount\x12.\n" +
	"\x13refunded_order_rate\x18\x0f \x01(\x01R\x11refundedOrderRate\x12)\n" +
	"\x10unsettled_amount\x18\x10 \x01(\x03R\x0funsettledAmount\x12#\n" +
	"\rfrozen_amount\x18\x11 \x01(\x03R\ffrozenAmount\x12\x1b\n" +
	"\tdata_date\x18\x12 \x01(\tR\bdataDate\x12\x1a\n" +
	"\bcurrency\x18\x13 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04week\x18\x14 \x01(\x05R\x04week\x12\x1f\n" +
	"\vfailed_rate\x18\x15 \x01(\x01R\n" +
	"failedRate\"\x96\x01\n" +
	"&GetStatisticsMerchantTradeTypeListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x127\n" +
	"\x04list\x18\x02 \x03(\v2#.pb.StatisticsMerchantTradeTypeInfoR\x04list\x12\x1d\n" +
	"\n" +
	"data_token\x18\x03 \x01(\tR\tdataToken\"\x8e\b\n" +
	"\x1fStatisticsMerchantTradeTypeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rmerchant_name\x18\x02 \x01(\tR\fmerchantName\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12@\n" +
	"\x1ctransaction_instruction_type\x18\x05 \x01(\x05R\x1atransactionInstructionType\x12*\n" +
	"\x11order_total_count\x18\x06 \x01(\x03R\x0forderTotalCount\x12,\n" +
	"\x12order_total_amount\x18\a \x01(\x03R\x10orderTotalAmount\x12.\n" +
	"\x13success_total_count\x18\b \x01(\x03R\x11successTotalCount\x120\n" +
	"\x14success_total_amount\x18\t \x01(\x03R\x12successTotalAmount\x12!\n" +
	"\fsuccess_rate\x18\n" +
	" \x01(\x01R\vsuccessRate\x12?\n" +
	"\x1cprocessing_order_total_count\x18\v \x01(\x03R\x19processingOrderTotalCount\x12A\n" +
	"\x1dprocessing_order_total_amount\x18\f \x01(\x03R\x1aprocessingOrderTotalAmount\x127\n" +
	"\x18failed_order_total_count\x18\r \x01(\x03R\x15failedOrderTotalCount\x129\n" +
	"\x19failed_order_total_amount\x18\x0e \x01(\x03R\x16failedOrderTotalAmount\x120\n" +
	"\x14refunded_order_count\x18\x0f \x01(\x03R\x12refundedOrderCount\x12=\n" +
	"\x1brefunded_order_total_amount\x18\x10 \x01(\x03R\x18refundedOrderTotalAmount\x12.\n" +
	"\x13refunded_order_rate\x18\x11 \x01(\x01R\x11refundedOrderRate\x12)\n" +
	"\x10unsettled_amount\x18\x12 \x01(\x03R\x0funsettledAmount\x12#\n" +
	"\rfrozen_amount\x18\x13 \x01(\x03R\ffrozenAmount\x12\x1d\n" +
	"\n" +
	"order_type\x18\x14 \x01(\x05R\torderType\x12\x1b\n" +
	"\tdata_date\x18\x15 \x01(\tR\bdataDate\x12\x12\n" +
	"\x04week\x18\x16 \x01(\x05R\x04week\x12\x1f\n" +
	"\vfailed_rate\x18\x17 \x01(\x01R\n" +
	"failedRate\"|\n" +
	"\x19GetStatisticsBankListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.pb.StatisticsBankInfoR\x04list\x12\x1d\n" +
	"\n" +
	"data_token\x18\x03 \x01(\tR\tdataToken\"\x8a\x0e\n" +
	"\x12StatisticsBankInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abank_id\x18\x02 \x01(\x03R\x06bankId\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12'\n" +
	"\x0fbank_identifier\x18\x04 \x01(\tR\x0ebankIdentifier\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12,\n" +
	"\x12order_total_amount\x18\x06 \x01(\x03R\x10orderTotalAmount\x12*\n" +
	"\x11order_total_count\x18\a \x01(\x03R\x0forderTotalCount\x12.\n" +
	"\x13success_total_count\x18\b \x01(\x03R\x11successTotalCount\x120\n" +
	"\x14success_total_amount\x18\t \x01(\x03R\x12successTotalAmount\x12!\n" +
	"\fsuccess_rate\x18\n" +
	" \x01(\x01R\vsuccessRate\x12?\n" +
	"\x1cprocessing_order_total_count\x18\v \x01(\x03R\x19processingOrderTotalCount\x12A\n" +
	"\x1dprocessing_order_total_amount\x18\f \x01(\x03R\x1aprocessingOrderTotalAmount\x127\n" +
	"\x18failed_order_total_count\x18\r \x01(\x03R\x15failedOrderTotalCount\x129\n" +
	"\x19failed_order_total_amount\x18\x0e \x01(\x03R\x16failedOrderTotalAmount\x120\n" +
	"\x14refunded_order_count\x18\x0f \x01(\x03R\x12refundedOrderCount\x12=\n" +
	"\x1brefunded_order_total_amount\x18\x10 \x01(\x03R\x18refundedOrderTotalAmount\x12.\n" +
	"\x13refunded_order_rate\x18\x11 \x01(\x01R\x11refundedOrderRate\x125\n" +
	"\x17bank_order_total_amount\x18\x12 \x01(\x03R\x14bankOrderTotalAmount\x123\n" +
	"\x16bank_order_total_count\x18\x13 \x01(\x03R\x13bankOrderTotalCount\x127\n" +
	"\x18bank_success_total_count\x18\x14 \x01(\x03R\x15bankSuccessTotalCount\x129\n" +
	"\x19bank_success_total_amount\x18\x15 \x01(\x03R\x16bankSuccessTotalAmount\x12*\n" +
	"\x11bank_success_rate\x18\x16 \x01(\x01R\x0fbankSuccessRate\x12H\n" +
	"!bank_processing_order_total_count\x18\x17 \x01(\x03R\x1dbankProcessingOrderTotalCount\x12J\n" +
	"\"bank_processing_order_total_amount\x18\x18 \x01(\x03R\x1ebankProcessingOrderTotalAmount\x12@\n" +
	"\x1dbank_failed_order_total_count\x18\x19 \x01(\x03R\x19bankFailedOrderTotalCount\x12B\n" +
	"\x1ebank_failed_order_total_amount\x18\x1a \x01(\x03R\x1abankFailedOrderTotalAmount\x129\n" +
	"\x19bank_refunded_order_count\x18\x1b \x01(\x03R\x16bankRefundedOrderCount\x12F\n" +
	" bank_refunded_order_total_amount\x18\x1c \x01(\x03R\x1cbankRefundedOrderTotalAmount\x127\n" +
	"\x18bank_refunded_order_rate\x18\x1d \x01(\x01R\x15bankRefundedOrderRate\x12\x1d\n" +
	"\n" +
	"order_type\x18\x1e \x01(\x05R\torderType\x12\x1b\n" +
	"\tdata_date\x18\x1f \x01(\tR\bdataDate\x127\n" +
	"\x18bank_unknown_order_count\x18  \x01(\x03R\x15bankUnknownOrderCount\x129\n" +
	"\x19bank_unknown_order_amount\x18! \x01(\x03R\x16bankUnknownOrderAmount\x12\x12\n" +
	"\x04week\x18\" \x01(\x05R\x04week\x12\x1f\n" +
	"\vfailed_rate\x18# \x01(\x01R\n" +
	"failedRate\x12(\n" +
	"\x10bank_failed_rate\x18$ \x01(\x01R\x0ebankFailedRate\"\x8e\x01\n" +
	"\"GetStatisticsBankTradeTypeListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x123\n" +
	"\x04list\x18\x02 \x03(\v2\x1f.pb.StatisticsBankTradeTypeInfoR\x04list\x12\x1d\n" +
	"\n" +
	"data_token\x18\x03 \x01(\tR\tdataToken\"\xd5\x0e\n" +
	"\x1bStatisticsBankTradeTypeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abank_id\x18\x02 \x01(\x03R\x06bankId\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12'\n" +
	"\x0fbank_identifier\x18\x04 \x01(\tR\x0ebankIdentifier\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12@\n" +
	"\x1ctransaction_instruction_type\x18\x06 \x01(\x05R\x1atransactionInstructionType\x12,\n" +
	"\x12order_total_amount\x18\a \x01(\x03R\x10orderTotalAmount\x12*\n" +
	"\x11order_total_count\x18\b \x01(\x03R\x0forderTotalCount\x12.\n" +
	"\x13success_total_count\x18\t \x01(\x03R\x11successTotalCount\x120\n" +
	"\x14success_total_amount\x18\n" +
	" \x01(\x03R\x12successTotalAmount\x12!\n" +
	"\fsuccess_rate\x18\v \x01(\x01R\vsuccessRate\x12?\n" +
	"\x1cprocessing_order_total_count\x18\f \x01(\x03R\x19processingOrderTotalCount\x12A\n" +
	"\x1dprocessing_order_total_amount\x18\r \x01(\x03R\x1aprocessingOrderTotalAmount\x127\n" +
	"\x18failed_order_total_count\x18\x0e \x01(\x03R\x15failedOrderTotalCount\x129\n" +
	"\x19failed_order_total_amount\x18\x0f \x01(\x03R\x16failedOrderTotalAmount\x120\n" +
	"\x14refunded_order_count\x18\x10 \x01(\x03R\x12refundedOrderCount\x12=\n" +
	"\x1brefunded_order_total_amount\x18\x11 \x01(\x03R\x18refundedOrderTotalAmount\x12.\n" +
	"\x13refunded_order_rate\x18\x12 \x01(\x01R\x11refundedOrderRate\x125\n" +
	"\x17bank_order_total_amount\x18\x13 \x01(\x03R\x14bankOrderTotalAmount\x123\n" +
	"\x16bank_order_total_count\x18\x14 \x01(\x03R\x13bankOrderTotalCount\x127\n" +
	"\x18bank_success_total_count\x18\x15 \x01(\x03R\x15bankSuccessTotalCount\x129\n" +
	"\x19bank_success_total_amount\x18\x16 \x01(\x03R\x16bankSuccessTotalAmount\x12*\n" +
	"\x11bank_success_rate\x18\x17 \x01(\x01R\x0fbankSuccessRate\x12H\n" +
	"!bank_processing_order_total_count\x18\x18 \x01(\x03R\x1dbankProcessingOrderTotalCount\x12J\n" +
	"\"bank_processing_order_total_amount\x18\x19 \x01(\x03R\x1ebankProcessingOrderTotalAmount\x12@\n" +
	"\x1dbank_failed_order_total_count\x18\x1a \x01(\x03R\x19bankFailedOrderTotalCount\x12B\n" +
	"\x1ebank_failed_order_total_amount\x18\x1b \x01(\x03R\x1abankFailedOrderTotalAmount\x129\n" +
	"\x19bank_refunded_order_count\x18\x1c \x01(\x03R\x16bankRefundedOrderCount\x12F\n" +
	" bank_refunded_order_total_amount\x18\x1d \x01(\x03R\x1cbankRefundedOrderTotalAmount\x127\n" +
	"\x18bank_refunded_order_rate\x18\x1e \x01(\x01R\x15bankRefundedOrderRate\x12\x1d\n" +
	"\n" +
	"order_type\x18\x1f \x01(\x05R\torderType\x12\x1b\n" +
	"\tdata_date\x18  \x01(\tR\bdataDate\x127\n" +
	"\x18bank_unknown_order_count\x18! \x01(\x03R\x15bankUnknownOrderCount\x129\n" +
	"\x19bank_unknown_order_amount\x18\" \x01(\x03R\x16bankUnknownOrderAmount\x12\x12\n" +
	"\x04week\x18# \x01(\x05R\x04week\x12\x1f\n" +
	"\vfailed_rate\x18$ \x01(\x01R\n" +
	"failedRate\x12(\n" +
	"\x10bank_failed_rate\x18% \x01(\x01R\x0ebankFailedRate\"\x86\x01\n" +
	"\x1eGetStatisticsTradeTypeListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.pb.StatisticsTradeTypeInfoR\x04list\x12\x1d\n" +
	"\n" +
	"data_token\x18\x03 \x01(\tR\tdataToken\"\xc0\a\n" +
	"\x17StatisticsTradeTypeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12@\n" +
	"\x1ctransaction_instruction_type\x18\x02 \x01(\x05R\x1atransactionInstructionType\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12*\n" +
	"\x11order_total_count\x18\x04 \x01(\x03R\x0forderTotalCount\x12,\n" +
	"\x12order_total_amount\x18\x05 \x01(\x03R\x10orderTotalAmount\x12.\n" +
	"\x13success_total_count\x18\x06 \x01(\x03R\x11successTotalCount\x120\n" +
	"\x14success_total_amount\x18\a \x01(\x03R\x12successTotalAmount\x12!\n" +
	"\fsuccess_rate\x18\b \x01(\x01R\vsuccessRate\x12?\n" +
	"\x1cprocessing_order_total_count\x18\t \x01(\x03R\x19processingOrderTotalCount\x12A\n" +
	"\x1dprocessing_order_total_amount\x18\n" +
	" \x01(\x03R\x1aprocessingOrderTotalAmount\x127\n" +
	"\x18failed_order_total_count\x18\v \x01(\x03R\x15failedOrderTotalCount\x129\n" +
	"\x19failed_order_total_amount\x18\f \x01(\x03R\x16failedOrderTotalAmount\x120\n" +
	"\x14refunded_order_count\x18\r \x01(\x03R\x12refundedOrderCount\x12=\n" +
	"\x1brefunded_order_total_amount\x18\x0e \x01(\x03R\x18refundedOrderTotalAmount\x12.\n" +
	"\x13refunded_order_rate\x18\x0f \x01(\x01R\x11refundedOrderRate\x12)\n" +
	"\x10unsettled_amount\x18\x10 \x01(\x03R\x0funsettledAmount\x12#\n" +
	"\rfrozen_amount\x18\x11 \x01(\x03R\ffrozenAmount\x12\x1d\n" +
	"\n" +
	"order_type\x18\x12 \x01(\x05R\torderType\x12\x1b\n" +
	"\tdata_date\x18\x13 \x01(\tR\bdataDate\x12\x12\n" +
	"\x04week\x18\x14 \x01(\x05R\x04week\x12\x1f\n" +
	"\vfailed_rate\x18\x15 \x01(\x01R\n" +
	"failedRate2\xd0\x03\n" +
	"\n" +
	"Statistics\x12T\n" +
	"\x19GetStatisticsMerchantList\x12\x14.pb.GetStatisticsReq\x1a!.pb.GetStatisticsMerchantListResp\x12f\n" +
	"\"GetStatisticsMerchantTradeTypeList\x12\x14.pb.GetStatisticsReq\x1a*.pb.GetStatisticsMerchantTradeTypeListResp\x12L\n" +
	"\x15GetStatisticsBankList\x12\x14.pb.GetStatisticsReq\x1a\x1d.pb.GetStatisticsBankListResp\x12^\n" +
	"\x1eGetStatisticsBankTradeTypeList\x12\x14.pb.GetStatisticsReq\x1a&.pb.GetStatisticsBankTradeTypeListResp\x12V\n" +
	"\x1aGetStatisticsTradeTypeList\x12\x14.pb.GetStatisticsReq\x1a\".pb.GetStatisticsTradeTypeListRespB\"Z base/rpc_api/admin/pb/statisticsb\x06proto3"

var (
	file_statistics_statistics_proto_rawDescOnce sync.Once
	file_statistics_statistics_proto_rawDescData []byte
)

func file_statistics_statistics_proto_rawDescGZIP() []byte {
	file_statistics_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)))
	})
	return file_statistics_statistics_proto_rawDescData
}

var file_statistics_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_statistics_statistics_proto_goTypes = []any{
	(*GetStatisticsReq)(nil),                       // 0: pb.GetStatisticsReq
	(*GetStatisticsMerchantListResp)(nil),          // 1: pb.GetStatisticsMerchantListResp
	(*StatisticsMerchantInfo)(nil),                 // 2: pb.StatisticsMerchantInfo
	(*GetStatisticsMerchantTradeTypeListResp)(nil), // 3: pb.GetStatisticsMerchantTradeTypeListResp
	(*StatisticsMerchantTradeTypeInfo)(nil),        // 4: pb.StatisticsMerchantTradeTypeInfo
	(*GetStatisticsBankListResp)(nil),              // 5: pb.GetStatisticsBankListResp
	(*StatisticsBankInfo)(nil),                     // 6: pb.StatisticsBankInfo
	(*GetStatisticsBankTradeTypeListResp)(nil),     // 7: pb.GetStatisticsBankTradeTypeListResp
	(*StatisticsBankTradeTypeInfo)(nil),            // 8: pb.StatisticsBankTradeTypeInfo
	(*GetStatisticsTradeTypeListResp)(nil),         // 9: pb.GetStatisticsTradeTypeListResp
	(*StatisticsTradeTypeInfo)(nil),                // 10: pb.StatisticsTradeTypeInfo
}
var file_statistics_statistics_proto_depIdxs = []int32{
	2,  // 0: pb.GetStatisticsMerchantListResp.list:type_name -> pb.StatisticsMerchantInfo
	4,  // 1: pb.GetStatisticsMerchantTradeTypeListResp.list:type_name -> pb.StatisticsMerchantTradeTypeInfo
	6,  // 2: pb.GetStatisticsBankListResp.list:type_name -> pb.StatisticsBankInfo
	8,  // 3: pb.GetStatisticsBankTradeTypeListResp.list:type_name -> pb.StatisticsBankTradeTypeInfo
	10, // 4: pb.GetStatisticsTradeTypeListResp.list:type_name -> pb.StatisticsTradeTypeInfo
	0,  // 5: pb.Statistics.GetStatisticsMerchantList:input_type -> pb.GetStatisticsReq
	0,  // 6: pb.Statistics.GetStatisticsMerchantTradeTypeList:input_type -> pb.GetStatisticsReq
	0,  // 7: pb.Statistics.GetStatisticsBankList:input_type -> pb.GetStatisticsReq
	0,  // 8: pb.Statistics.GetStatisticsBankTradeTypeList:input_type -> pb.GetStatisticsReq
	0,  // 9: pb.Statistics.GetStatisticsTradeTypeList:input_type -> pb.GetStatisticsReq
	1,  // 10: pb.Statistics.GetStatisticsMerchantList:output_type -> pb.GetStatisticsMerchantListResp
	3,  // 11: pb.Statistics.GetStatisticsMerchantTradeTypeList:output_type -> pb.GetStatisticsMerchantTradeTypeListResp
	5,  // 12: pb.Statistics.GetStatisticsBankList:output_type -> pb.GetStatisticsBankListResp
	7,  // 13: pb.Statistics.GetStatisticsBankTradeTypeList:output_type -> pb.GetStatisticsBankTradeTypeListResp
	9,  // 14: pb.Statistics.GetStatisticsTradeTypeList:output_type -> pb.GetStatisticsTradeTypeListResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_statistics_statistics_proto_init() }
func file_statistics_statistics_proto_init() {
	if File_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_statistics_proto_msgTypes,
	}.Build()
	File_statistics_statistics_proto = out.File
	file_statistics_statistics_proto_goTypes = nil
	file_statistics_statistics_proto_depIdxs = nil
}
