// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: balance_adj_application.proto

package balance_adj_application

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceAdjApplication_ApplyChangeBalance_FullMethodName     = "/pb.BalanceAdjApplication/ApplyChangeBalance"
	BalanceAdjApplication_AuditChangeBalance_FullMethodName     = "/pb.BalanceAdjApplication/AuditChangeBalance"
	BalanceAdjApplication_GetChangeBalanceInfo_FullMethodName   = "/pb.BalanceAdjApplication/GetChangeBalanceInfo"
	BalanceAdjApplication_GetChangeBalanceList_FullMethodName   = "/pb.BalanceAdjApplication/GetChangeBalanceList"
	BalanceAdjApplication_GetManualFreezeBalance_FullMethodName = "/pb.BalanceAdjApplication/GetManualFreezeBalance"
)

// BalanceAdjApplicationClient is the client API for BalanceAdjApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceAdjApplicationClient interface {
	ApplyChangeBalance(ctx context.Context, in *ApplyChangeBalanceRep, opts ...grpc.CallOption) (*ApplyChangeBalanceResp, error)
	AuditChangeBalance(ctx context.Context, in *AuditChangeBalanceRep, opts ...grpc.CallOption) (*AuditChangeBalanceResp, error)
	GetChangeBalanceInfo(ctx context.Context, in *GetChangeBalanceInfoRep, opts ...grpc.CallOption) (*GetChangeBalanceInfoResp, error)
	GetChangeBalanceList(ctx context.Context, in *GetChangeBalanceListRep, opts ...grpc.CallOption) (*GetChangeBalanceListResp, error)
	GetManualFreezeBalance(ctx context.Context, in *GetManualFreezeBalanceRep, opts ...grpc.CallOption) (*GetManualFreezeBalanceResp, error)
}

type balanceAdjApplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceAdjApplicationClient(cc grpc.ClientConnInterface) BalanceAdjApplicationClient {
	return &balanceAdjApplicationClient{cc}
}

func (c *balanceAdjApplicationClient) ApplyChangeBalance(ctx context.Context, in *ApplyChangeBalanceRep, opts ...grpc.CallOption) (*ApplyChangeBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyChangeBalanceResp)
	err := c.cc.Invoke(ctx, BalanceAdjApplication_ApplyChangeBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdjApplicationClient) AuditChangeBalance(ctx context.Context, in *AuditChangeBalanceRep, opts ...grpc.CallOption) (*AuditChangeBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditChangeBalanceResp)
	err := c.cc.Invoke(ctx, BalanceAdjApplication_AuditChangeBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdjApplicationClient) GetChangeBalanceInfo(ctx context.Context, in *GetChangeBalanceInfoRep, opts ...grpc.CallOption) (*GetChangeBalanceInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangeBalanceInfoResp)
	err := c.cc.Invoke(ctx, BalanceAdjApplication_GetChangeBalanceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdjApplicationClient) GetChangeBalanceList(ctx context.Context, in *GetChangeBalanceListRep, opts ...grpc.CallOption) (*GetChangeBalanceListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangeBalanceListResp)
	err := c.cc.Invoke(ctx, BalanceAdjApplication_GetChangeBalanceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdjApplicationClient) GetManualFreezeBalance(ctx context.Context, in *GetManualFreezeBalanceRep, opts ...grpc.CallOption) (*GetManualFreezeBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManualFreezeBalanceResp)
	err := c.cc.Invoke(ctx, BalanceAdjApplication_GetManualFreezeBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceAdjApplicationServer is the server API for BalanceAdjApplication service.
// All implementations must embed UnimplementedBalanceAdjApplicationServer
// for forward compatibility.
type BalanceAdjApplicationServer interface {
	ApplyChangeBalance(context.Context, *ApplyChangeBalanceRep) (*ApplyChangeBalanceResp, error)
	AuditChangeBalance(context.Context, *AuditChangeBalanceRep) (*AuditChangeBalanceResp, error)
	GetChangeBalanceInfo(context.Context, *GetChangeBalanceInfoRep) (*GetChangeBalanceInfoResp, error)
	GetChangeBalanceList(context.Context, *GetChangeBalanceListRep) (*GetChangeBalanceListResp, error)
	GetManualFreezeBalance(context.Context, *GetManualFreezeBalanceRep) (*GetManualFreezeBalanceResp, error)
	mustEmbedUnimplementedBalanceAdjApplicationServer()
}

// UnimplementedBalanceAdjApplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceAdjApplicationServer struct{}

func (UnimplementedBalanceAdjApplicationServer) ApplyChangeBalance(context.Context, *ApplyChangeBalanceRep) (*ApplyChangeBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyChangeBalance not implemented")
}
func (UnimplementedBalanceAdjApplicationServer) AuditChangeBalance(context.Context, *AuditChangeBalanceRep) (*AuditChangeBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditChangeBalance not implemented")
}
func (UnimplementedBalanceAdjApplicationServer) GetChangeBalanceInfo(context.Context, *GetChangeBalanceInfoRep) (*GetChangeBalanceInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChangeBalanceInfo not implemented")
}
func (UnimplementedBalanceAdjApplicationServer) GetChangeBalanceList(context.Context, *GetChangeBalanceListRep) (*GetChangeBalanceListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChangeBalanceList not implemented")
}
func (UnimplementedBalanceAdjApplicationServer) GetManualFreezeBalance(context.Context, *GetManualFreezeBalanceRep) (*GetManualFreezeBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManualFreezeBalance not implemented")
}
func (UnimplementedBalanceAdjApplicationServer) mustEmbedUnimplementedBalanceAdjApplicationServer() {}
func (UnimplementedBalanceAdjApplicationServer) testEmbeddedByValue()                               {}

// UnsafeBalanceAdjApplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceAdjApplicationServer will
// result in compilation errors.
type UnsafeBalanceAdjApplicationServer interface {
	mustEmbedUnimplementedBalanceAdjApplicationServer()
}

func RegisterBalanceAdjApplicationServer(s grpc.ServiceRegistrar, srv BalanceAdjApplicationServer) {
	// If the following call pancis, it indicates UnimplementedBalanceAdjApplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceAdjApplication_ServiceDesc, srv)
}

func _BalanceAdjApplication_ApplyChangeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyChangeBalanceRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdjApplicationServer).ApplyChangeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdjApplication_ApplyChangeBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdjApplicationServer).ApplyChangeBalance(ctx, req.(*ApplyChangeBalanceRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdjApplication_AuditChangeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditChangeBalanceRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdjApplicationServer).AuditChangeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdjApplication_AuditChangeBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdjApplicationServer).AuditChangeBalance(ctx, req.(*AuditChangeBalanceRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdjApplication_GetChangeBalanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangeBalanceInfoRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdjApplicationServer).GetChangeBalanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdjApplication_GetChangeBalanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdjApplicationServer).GetChangeBalanceInfo(ctx, req.(*GetChangeBalanceInfoRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdjApplication_GetChangeBalanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangeBalanceListRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdjApplicationServer).GetChangeBalanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdjApplication_GetChangeBalanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdjApplicationServer).GetChangeBalanceList(ctx, req.(*GetChangeBalanceListRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdjApplication_GetManualFreezeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManualFreezeBalanceRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdjApplicationServer).GetManualFreezeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdjApplication_GetManualFreezeBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdjApplicationServer).GetManualFreezeBalance(ctx, req.(*GetManualFreezeBalanceRep))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceAdjApplication_ServiceDesc is the grpc.ServiceDesc for BalanceAdjApplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceAdjApplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BalanceAdjApplication",
	HandlerType: (*BalanceAdjApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyChangeBalance",
			Handler:    _BalanceAdjApplication_ApplyChangeBalance_Handler,
		},
		{
			MethodName: "AuditChangeBalance",
			Handler:    _BalanceAdjApplication_AuditChangeBalance_Handler,
		},
		{
			MethodName: "GetChangeBalanceInfo",
			Handler:    _BalanceAdjApplication_GetChangeBalanceInfo_Handler,
		},
		{
			MethodName: "GetChangeBalanceList",
			Handler:    _BalanceAdjApplication_GetChangeBalanceList_Handler,
		},
		{
			MethodName: "GetManualFreezeBalance",
			Handler:    _BalanceAdjApplication_GetManualFreezeBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balance_adj_application.proto",
}
