// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: bank_server.proto

package bank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WithdrawalBank_CreateBankInfo_FullMethodName   = "/pb.WithdrawalBank/CreateBankInfo"
	WithdrawalBank_ModifyBankInfo_FullMethodName   = "/pb.WithdrawalBank/ModifyBankInfo"
	WithdrawalBank_DeleteBankInfo_FullMethodName   = "/pb.WithdrawalBank/DeleteBankInfo"
	WithdrawalBank_ModifyBankStatus_FullMethodName = "/pb.WithdrawalBank/ModifyBankStatus"
	WithdrawalBank_GetBankList_FullMethodName      = "/pb.WithdrawalBank/GetBankList"
	WithdrawalBank_GetBankDetail_FullMethodName    = "/pb.WithdrawalBank/GetBankDetail"
)

// WithdrawalBankClient is the client API for WithdrawalBank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithdrawalBankClient interface {
	// create withdrawal bank info
	CreateBankInfo(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error)
	// modify withdrawal bank info
	ModifyBankInfo(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error)
	// delete withdrawal bank info
	DeleteBankInfo(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error)
	// modify withdrawal bank status
	ModifyBankStatus(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error)
	// get withdrawal bank info
	GetBankList(ctx context.Context, in *GetBankInfoReq, opts ...grpc.CallOption) (*GetBankInfoResp, error)
	// get withdrawal bank detail
	GetBankDetail(ctx context.Context, in *GetGetBankDetailReq, opts ...grpc.CallOption) (*GetGetBankDetailResp, error)
}

type withdrawalBankClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawalBankClient(cc grpc.ClientConnInterface) WithdrawalBankClient {
	return &withdrawalBankClient{cc}
}

func (c *withdrawalBankClient) CreateBankInfo(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResp)
	err := c.cc.Invoke(ctx, WithdrawalBank_CreateBankInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawalBankClient) ModifyBankInfo(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResp)
	err := c.cc.Invoke(ctx, WithdrawalBank_ModifyBankInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawalBankClient) DeleteBankInfo(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResp)
	err := c.cc.Invoke(ctx, WithdrawalBank_DeleteBankInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawalBankClient) ModifyBankStatus(ctx context.Context, in *BankInfo, opts ...grpc.CallOption) (*OperateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResp)
	err := c.cc.Invoke(ctx, WithdrawalBank_ModifyBankStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawalBankClient) GetBankList(ctx context.Context, in *GetBankInfoReq, opts ...grpc.CallOption) (*GetBankInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankInfoResp)
	err := c.cc.Invoke(ctx, WithdrawalBank_GetBankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawalBankClient) GetBankDetail(ctx context.Context, in *GetGetBankDetailReq, opts ...grpc.CallOption) (*GetGetBankDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGetBankDetailResp)
	err := c.cc.Invoke(ctx, WithdrawalBank_GetBankDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawalBankServer is the server API for WithdrawalBank service.
// All implementations must embed UnimplementedWithdrawalBankServer
// for forward compatibility.
type WithdrawalBankServer interface {
	// create withdrawal bank info
	CreateBankInfo(context.Context, *BankInfo) (*OperateResp, error)
	// modify withdrawal bank info
	ModifyBankInfo(context.Context, *BankInfo) (*OperateResp, error)
	// delete withdrawal bank info
	DeleteBankInfo(context.Context, *BankInfo) (*OperateResp, error)
	// modify withdrawal bank status
	ModifyBankStatus(context.Context, *BankInfo) (*OperateResp, error)
	// get withdrawal bank info
	GetBankList(context.Context, *GetBankInfoReq) (*GetBankInfoResp, error)
	// get withdrawal bank detail
	GetBankDetail(context.Context, *GetGetBankDetailReq) (*GetGetBankDetailResp, error)
	mustEmbedUnimplementedWithdrawalBankServer()
}

// UnimplementedWithdrawalBankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWithdrawalBankServer struct{}

func (UnimplementedWithdrawalBankServer) CreateBankInfo(context.Context, *BankInfo) (*OperateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBankInfo not implemented")
}
func (UnimplementedWithdrawalBankServer) ModifyBankInfo(context.Context, *BankInfo) (*OperateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyBankInfo not implemented")
}
func (UnimplementedWithdrawalBankServer) DeleteBankInfo(context.Context, *BankInfo) (*OperateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBankInfo not implemented")
}
func (UnimplementedWithdrawalBankServer) ModifyBankStatus(context.Context, *BankInfo) (*OperateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyBankStatus not implemented")
}
func (UnimplementedWithdrawalBankServer) GetBankList(context.Context, *GetBankInfoReq) (*GetBankInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankList not implemented")
}
func (UnimplementedWithdrawalBankServer) GetBankDetail(context.Context, *GetGetBankDetailReq) (*GetGetBankDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankDetail not implemented")
}
func (UnimplementedWithdrawalBankServer) mustEmbedUnimplementedWithdrawalBankServer() {}
func (UnimplementedWithdrawalBankServer) testEmbeddedByValue()                        {}

// UnsafeWithdrawalBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithdrawalBankServer will
// result in compilation errors.
type UnsafeWithdrawalBankServer interface {
	mustEmbedUnimplementedWithdrawalBankServer()
}

func RegisterWithdrawalBankServer(s grpc.ServiceRegistrar, srv WithdrawalBankServer) {
	// If the following call pancis, it indicates UnimplementedWithdrawalBankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WithdrawalBank_ServiceDesc, srv)
}

func _WithdrawalBank_CreateBankInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalBankServer).CreateBankInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalBank_CreateBankInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalBankServer).CreateBankInfo(ctx, req.(*BankInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawalBank_ModifyBankInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalBankServer).ModifyBankInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalBank_ModifyBankInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalBankServer).ModifyBankInfo(ctx, req.(*BankInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawalBank_DeleteBankInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalBankServer).DeleteBankInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalBank_DeleteBankInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalBankServer).DeleteBankInfo(ctx, req.(*BankInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawalBank_ModifyBankStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalBankServer).ModifyBankStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalBank_ModifyBankStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalBankServer).ModifyBankStatus(ctx, req.(*BankInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawalBank_GetBankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalBankServer).GetBankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalBank_GetBankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalBankServer).GetBankList(ctx, req.(*GetBankInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawalBank_GetBankDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGetBankDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalBankServer).GetBankDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalBank_GetBankDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalBankServer).GetBankDetail(ctx, req.(*GetGetBankDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WithdrawalBank_ServiceDesc is the grpc.ServiceDesc for WithdrawalBank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WithdrawalBank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WithdrawalBank",
	HandlerType: (*WithdrawalBankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBankInfo",
			Handler:    _WithdrawalBank_CreateBankInfo_Handler,
		},
		{
			MethodName: "ModifyBankInfo",
			Handler:    _WithdrawalBank_ModifyBankInfo_Handler,
		},
		{
			MethodName: "DeleteBankInfo",
			Handler:    _WithdrawalBank_DeleteBankInfo_Handler,
		},
		{
			MethodName: "ModifyBankStatus",
			Handler:    _WithdrawalBank_ModifyBankStatus_Handler,
		},
		{
			MethodName: "GetBankList",
			Handler:    _WithdrawalBank_GetBankList_Handler,
		},
		{
			MethodName: "GetBankDetail",
			Handler:    _WithdrawalBank_GetBankDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank_server.proto",
}
