// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: release_manage.proto

package release_manage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReleaseManage_UpdateReleaseManage_FullMethodName    = "/pb.ReleaseManage/UpdateReleaseManage"
	ReleaseManage_ManualRelease_FullMethodName          = "/pb.ReleaseManage/ManualRelease"
	ReleaseManage_QueryReleaseManageList_FullMethodName = "/pb.ReleaseManage/QueryReleaseManageList"
	ReleaseManage_QueryReleaseLogList_FullMethodName    = "/pb.ReleaseManage/QueryReleaseLogList"
	ReleaseManage_CloseAllReleaseManage_FullMethodName  = "/pb.ReleaseManage/CloseAllReleaseManage"
)

// ReleaseManageClient is the client API for ReleaseManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReleaseManageClient interface {
	UpdateReleaseManage(ctx context.Context, in *UpdateReleaseManageParam, opts ...grpc.CallOption) (*ReleaseInterfaceResponse, error)
	ManualRelease(ctx context.Context, in *ManualReleaseParam, opts ...grpc.CallOption) (*ReleaseInterfaceResponse, error)
	QueryReleaseManageList(ctx context.Context, in *QueryReleaseManageListParam, opts ...grpc.CallOption) (*QueryReleaseManageListResponse, error)
	QueryReleaseLogList(ctx context.Context, in *QueryReleaseManageListParam, opts ...grpc.CallOption) (*QueryReleaseManageListResponse, error)
	CloseAllReleaseManage(ctx context.Context, in *CloseAllReleaseManageParam, opts ...grpc.CallOption) (*ReleaseInterfaceResponse, error)
}

type releaseManageClient struct {
	cc grpc.ClientConnInterface
}

func NewReleaseManageClient(cc grpc.ClientConnInterface) ReleaseManageClient {
	return &releaseManageClient{cc}
}

func (c *releaseManageClient) UpdateReleaseManage(ctx context.Context, in *UpdateReleaseManageParam, opts ...grpc.CallOption) (*ReleaseInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseInterfaceResponse)
	err := c.cc.Invoke(ctx, ReleaseManage_UpdateReleaseManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseManageClient) ManualRelease(ctx context.Context, in *ManualReleaseParam, opts ...grpc.CallOption) (*ReleaseInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseInterfaceResponse)
	err := c.cc.Invoke(ctx, ReleaseManage_ManualRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseManageClient) QueryReleaseManageList(ctx context.Context, in *QueryReleaseManageListParam, opts ...grpc.CallOption) (*QueryReleaseManageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReleaseManageListResponse)
	err := c.cc.Invoke(ctx, ReleaseManage_QueryReleaseManageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseManageClient) QueryReleaseLogList(ctx context.Context, in *QueryReleaseManageListParam, opts ...grpc.CallOption) (*QueryReleaseManageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReleaseManageListResponse)
	err := c.cc.Invoke(ctx, ReleaseManage_QueryReleaseLogList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseManageClient) CloseAllReleaseManage(ctx context.Context, in *CloseAllReleaseManageParam, opts ...grpc.CallOption) (*ReleaseInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseInterfaceResponse)
	err := c.cc.Invoke(ctx, ReleaseManage_CloseAllReleaseManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReleaseManageServer is the server API for ReleaseManage service.
// All implementations must embed UnimplementedReleaseManageServer
// for forward compatibility.
type ReleaseManageServer interface {
	UpdateReleaseManage(context.Context, *UpdateReleaseManageParam) (*ReleaseInterfaceResponse, error)
	ManualRelease(context.Context, *ManualReleaseParam) (*ReleaseInterfaceResponse, error)
	QueryReleaseManageList(context.Context, *QueryReleaseManageListParam) (*QueryReleaseManageListResponse, error)
	QueryReleaseLogList(context.Context, *QueryReleaseManageListParam) (*QueryReleaseManageListResponse, error)
	CloseAllReleaseManage(context.Context, *CloseAllReleaseManageParam) (*ReleaseInterfaceResponse, error)
	mustEmbedUnimplementedReleaseManageServer()
}

// UnimplementedReleaseManageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReleaseManageServer struct{}

func (UnimplementedReleaseManageServer) UpdateReleaseManage(context.Context, *UpdateReleaseManageParam) (*ReleaseInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReleaseManage not implemented")
}
func (UnimplementedReleaseManageServer) ManualRelease(context.Context, *ManualReleaseParam) (*ReleaseInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManualRelease not implemented")
}
func (UnimplementedReleaseManageServer) QueryReleaseManageList(context.Context, *QueryReleaseManageListParam) (*QueryReleaseManageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReleaseManageList not implemented")
}
func (UnimplementedReleaseManageServer) QueryReleaseLogList(context.Context, *QueryReleaseManageListParam) (*QueryReleaseManageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReleaseLogList not implemented")
}
func (UnimplementedReleaseManageServer) CloseAllReleaseManage(context.Context, *CloseAllReleaseManageParam) (*ReleaseInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseAllReleaseManage not implemented")
}
func (UnimplementedReleaseManageServer) mustEmbedUnimplementedReleaseManageServer() {}
func (UnimplementedReleaseManageServer) testEmbeddedByValue()                       {}

// UnsafeReleaseManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReleaseManageServer will
// result in compilation errors.
type UnsafeReleaseManageServer interface {
	mustEmbedUnimplementedReleaseManageServer()
}

func RegisterReleaseManageServer(s grpc.ServiceRegistrar, srv ReleaseManageServer) {
	// If the following call pancis, it indicates UnimplementedReleaseManageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReleaseManage_ServiceDesc, srv)
}

func _ReleaseManage_UpdateReleaseManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReleaseManageParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseManageServer).UpdateReleaseManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseManage_UpdateReleaseManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseManageServer).UpdateReleaseManage(ctx, req.(*UpdateReleaseManageParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseManage_ManualRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualReleaseParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseManageServer).ManualRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseManage_ManualRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseManageServer).ManualRelease(ctx, req.(*ManualReleaseParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseManage_QueryReleaseManageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReleaseManageListParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseManageServer).QueryReleaseManageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseManage_QueryReleaseManageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseManageServer).QueryReleaseManageList(ctx, req.(*QueryReleaseManageListParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseManage_QueryReleaseLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReleaseManageListParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseManageServer).QueryReleaseLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseManage_QueryReleaseLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseManageServer).QueryReleaseLogList(ctx, req.(*QueryReleaseManageListParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseManage_CloseAllReleaseManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAllReleaseManageParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseManageServer).CloseAllReleaseManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseManage_CloseAllReleaseManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseManageServer).CloseAllReleaseManage(ctx, req.(*CloseAllReleaseManageParam))
	}
	return interceptor(ctx, in, info, handler)
}

// ReleaseManage_ServiceDesc is the grpc.ServiceDesc for ReleaseManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReleaseManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ReleaseManage",
	HandlerType: (*ReleaseManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateReleaseManage",
			Handler:    _ReleaseManage_UpdateReleaseManage_Handler,
		},
		{
			MethodName: "ManualRelease",
			Handler:    _ReleaseManage_ManualRelease_Handler,
		},
		{
			MethodName: "QueryReleaseManageList",
			Handler:    _ReleaseManage_QueryReleaseManageList_Handler,
		},
		{
			MethodName: "QueryReleaseLogList",
			Handler:    _ReleaseManage_QueryReleaseLogList_Handler,
		},
		{
			MethodName: "CloseAllReleaseManage",
			Handler:    _ReleaseManage_CloseAllReleaseManage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "release_manage.proto",
}
