package consts

import "time"

const (
	NOTIFY_STATUS_SUCCESS = 1
	NOTIFY_STATUS_FAILED  = 2
	NOTIFY_STATUS_NOT     = 3
)

const (
	PAY_STATUS_SUCCESS    = 1
	PAY_STATUS_FAILDE     = 2
	PAY_STATUS_ABNORMAL   = 3
	PAY_STATUS_NOT        = 4
	PAY_STATUS_WAIT_AUDIT = 5
	PAY_STATUS_REJECT     = 6
	PAY_STATUS_REFUND     = 10
	PAY_STATUS_COMPLAIN   = 11
)

const (
	PAY_IN_TYPE_NATIVE   = 1
	PAY_IN_TYPE_QRCODE   = 2
	PAY_IN_TYPE_TRANSFER = 3
)

const (
	ORDER_TYPE_PAY_IN     = 1
	ORDER_TYPE_PAY_OUT    = 2
	ORDER_TYPE_SETTLEMENT = 3
)

const (
	TIME_TYPE_CREATE     = 1
	TIME_TYPE_UPDATE     = 2
	TIME_TYPE_NOTIFY     = 3
	TIME_TYPE_PAY        = 4
	TIME_TYPE_SETTLEMENT = 5
	TIME_TYPE_CALLBACK   = 6
	TIME_TYPE_AUDIT      = 7
	TIME_TYPE_COMPLETE   = 8
	TIME_TYPE_REFUND     = 9
)

// settlement get order list query time type
const (
	SETTLEMENT_TIME_TYPE_CREATE = 1
	SETTLEMENT_TIME_TYPE_NOTIFY = 2
	SETTLEMENT_TIME_TYPE_PASS   = 3
	SETTLEMENT_TIME_TYPE_FINISH = 4
)

// settlement audit status
const (
	SETTLEMENT_AUDIT_STATUS_SUCCESS    = 1
	SETTLEMENT_AUDIT_STATUS_REJECT     = 2
	SETTLEMENT_AUDIT_STATUS_PROCESSING = 3
)

// settlement order status
const (
	SETTLEMENT_ORDER_STATUS_SUCCESS    = 1
	SETTLEMENT_ORDER_STATUS_ERROR      = 2
	SETTLEMENT_ORDER_STATUS_PROCESSING = 3
	SETTLEMENT_ORDER_STATUS_FINISH     = 4
)

// settlement notify status
const (
	SETTLEMENT_notify_STATUS_SUCCESS    = 1
	SETTLEMENT_notify_STATUS_ERROR      = 2
	SETTLEMENT_notify_STATUS_NOT_NOTIFY = 3
)

// settlement order detail status
const (
	SETTLEMENT_ORDER_DETAILED_STATUS_CREATE                    = 1
	SETTLEMENT_ORDER_DETAILED_STATUS_MERCHANT_REJECT           = 5
	SETTLEMENT_ORDER_DETAILED_STATUS_MERCHANT_PASS             = 10
	SETTLEMENT_ORDER_DETAILED_STATUS_PLATFORM_LEVEL_ONE_REJECT = 15
	SETTLEMENT_ORDER_DETAILED_STATUS_PLATFORM_LEVEL_ONE_PASS   = 20
	SETTLEMENT_ORDER_DETAILED_STATUS_PLATFORM_LEVEL_TWO_REJECT = 25
	SETTLEMENT_ORDER_DETAILED_STATUS_PLATFORM_LEVEL_TWO_PASS   = 30
	SETTLEMENT_ORDER_DETAILED_STATUS_SUBMIN_BANK               = 35
	SETTLEMENT_ORDER_DETAILED_STATUS_BANK_FINISH               = 40
)

const (
	PAYOUT_TIME_TYPE_CREATE   = 1
	PAYOUT_TIME_TYPE_SUCCESS  = 2
	PAYOUT_TIME_TYPE_NOTICE   = 3
	PAYOUT_TIME_TYPE_DISPATCH = 4
)

// payout 订单的合规状态
const (
	PAYOUT_COMPLIANCE_STATUS_SUCCESS = 1
	PAYOUT_COMPLIANCE_STATUS_FAILED  = 2
	PAYOUT_COMPLIANCE_STATUS_PENDING = 3
)

const (
	PAYOUT_ALARM_STATUS_SUCCESS = 1
	PAYOUT_ALARM_STATUS_FAILED  = 2
	PAYOUT_ALARM_STATUS_PENDING = 3
)

const (
	BANK_ACCOUNT_TYPE_PAYIN_NATIVE   = 1
	BANK_ACCOUNT_TYPE_PAYIN_QRCODE   = 2
	BANK_ACCOUNT_TYPE_PAYIN_TRANSFER = 3
	BANK_ACCOUNT_TYPE_PAYOUT         = 4
	BANK_ACCOUNT_TYPE_SETTLEMENT     = 5
	BANK_ACCOUNT_TYPE_CHANGE         = 6
	BANK_ACCOUNT_TYPE_DEPOSIT        = 8
)

const (
	AMT_TYPE_REQUEST = 1
	AMT_TYPE_PAID    = 2
)

const (
	BANK_CALLBACK_ORDER_SECCESS    = 1
	BANK_CALLBACK_ORDER_FAILED     = 2
	BANK_CALLBACK_ORDER_PROCESSING = 3
)

const (
	RESPONSE_MSE_SUCCESS    = "success"
	RESPONSE_MSE_FAILED     = "failed"
	RESPONSE_MSE_PROCESSING = "processing"
	RESPONSE_MSE_PENDING    = "pending"
)

const (
	METADATA_KEY_MERCHANT_ID        = "merchant_id"
	METADATA_KEY_USER_ID            = "user_id"
	METADATA_KEY_USER_NAME          = "user_name"
	METADATA_KEY_ROLE_ID            = "role_id"
	METADATA_KEY_CURRENCY           = "currency"
	METADATA_KEY_MERCHANT_NAME      = "merchant_name"
	METADATA_KEY_APPID              = "merchant_appid"
	METADATA_KEY_MERCHANT_USER_INFO = "merchant_user_info"
)

const (
	STATUS_ENABLE  = 1
	STATUS_DISABLE = 2
)

// settlement process node
const (
	REVIEW_MERCHANT_SUBMIT      = 1
	REVIEW_MERCHANT_PRELIMINARY = 5
	REVIEW_PLATFORM_PRELIMINARY = 10
	REVIEW_PLATFORM_FINAL       = 15
	REVIEW_SUBMIT_BANK          = 20
)

// settlement process status
const (
	PROCESS_STATUS_PASS        = 1
	PROCESS_STATUS_REJECT      = 2
	PROCESS_STATUS_UNREVIEWED  = 3
	PROCESS_STATUS_SUBMIT_BANK = 4
)

// settlement submit bank status
const (
	SUBMIT_BANK_STATUS_SUCCESS  = 1
	SUBMIT_BANK_STATUS_ERROR    = 2
	SUBMIT_BANK_STATUS_UNSUBMIT = 3
)

// platform type
const (
	PLATFORM_TYPE_ADMIN    = 1
	PLATFORM_TYPE_MERCHANT = 2
)

const (
	PAYMETHOD_PAYIN_NATIVE   = 1
	PAYMETHOD_PAYIN_QRCODE   = 2
	PAYMETHOD_PAYIN_TRANSFER = 3
	PAYMETHOD_PAYOUT         = 4
)
const (
	PAYTYPE_INCRE = 1
	PAYTYPE_DECR  = 2
)
const (
	TRADETYPE_PAYOUT = 4
)

const (
	CHANGE_BALANCE_TYPE_INCR_BALANCE                                       = 1  //incr balance,incr withdraw_balance
	CHANGE_BALANCE_TYPE_DECR_BALANCE                                       = 2  // decr balance,decr withdraw_balance
	CHANGE_BALANCE_TYPE_INCR_SETTLEMENT_BALANCE                            = 3  //incr balance, incr unsettlement balance  payout pay success
	CHANGE_BALANCE_TYPE_DECR_SETTLEMENT_BALANCE                            = 4  //decr unsettlement balance,incr withdraw balance  payin success
	CHANGE_BALANCE_TYPE_INCR_FREEZE_BALANCE                                = 5  //incr  withdraw balance, decr freeze balance  payout failed
	CHANGE_BALANCE_TYPE_DECR_FREEZE_BALANCE                                = 6  //decr  freeze balance ,decr balance   payout success
	CHANGE_BALANCE_TYPE_ONLY_SYNC_MYSQL                                    = 7  //
	CHANGE_BALANCE_TYPE_DECR_BALANCE_UNSETTLEMENT                          = 8  // decr balance,decr unsettlement
	CHANGE_BALANCE_TYPE_INCR_FREEZE_DECR_WITHDRAW                          = 9  // incr freeze balance,decr withdraw balance
	CHANGE_BALANCE_TYPE_INCR_WITHDRAW_DECR_FREEZE_DECR_BALANCE_DECR_FREEZE = 10 // incr decr withdraw balance,freeze balance,decr freeze balance ,decr balance
	CHANGE_BALANCE_TYPE_DECR_WITHDRAW_INCR_FREEZE_DECR_BALANCE_DECR_FREEZE = 11 // decr  withdraw balance, incr freeze balance,decr freeze balance ,decr balance

)

const MERCHANT_ADMIN_ROLE_ADMINISTRATOR = 1

const (
	RateGradientTypeCondition = 1
	RateGradientTypeMix       = 2
	RateGradientTypeFixedAmt  = 3
	RateGradientTypeFixedRate = 4
)

const (
	PAYOUT_STATUS_SUCCESS  = 1
	PAYOUT_STATUS_FAILED   = 2
	PAYOUT_STATUS_PENDING  = 3
	PAYOUT_STATUS_REFUNDED = 4
	//PAYOUT_STATUS_NO_CREATE = 4
	//PAYOUT_STATUS_CREATE    = 5
	//PAYOUT_STATUS_ABNORMAL  = 2
)

const MERCHANT_BANK_DEFAULT_WEIGHT = 10

const (
	TIME_LAYOUT_FORMAT              = "2006-01-02 15:04:05"
	TIME_LAYOUT_FORMAT_YMD          = "2006-01-02"
	TIME_LAYOUT_FORMAT_YMDHMSS      = "2006-01-02 15:04:05.000"
	TIME_LAYOUT_FORMAT_YYMMDDHHMMSS = "060102150405"
)

const (
	CRON_TYPE_EVERY_DAY = 1
	CRON_TYPE_LOCK_DAY  = 2
	CRON_TYPE_PROMPTIY  = 3
)

const (
	IS_RELEASE_NO      = 1
	IS_RELEASE_YES     = 2
	IS_RELEASE_DISCARD = 3
)

const (
	BANK_ORDER_STATUS_SUCCESS  = "success"
	BANK_ORDER_STATUS__FAILED  = "failed"
	BANK_ORDER_STATUS__PENDING = "pending"
)

const (
	STATISTICS_LOAD_DAY    = "day"
	STATISTICS_LOAD_WEEK   = "week"
	STATISTICS_LOAD_MONTH  = "month"
	STATISTICS_LOAD_RANDOM = "random"
)

const (
	BALANCE_TRADE_COMMAND_SUCCESS          = 1
	BALANCE_TRADE_COMMAND_ADDITIONAL_ORDER = 2
	BALANCE_TRADE_COMMAND_COMPLAINT        = 3
	BALANCE_TRADE_COMMAND_REVERSAL         = 4
	BALANCE_TRADE_COMMAND_INCRE            = 5
	BALANCE_TRADE_COMMAND_DECR             = 6
)

const (
	BALANCE_FREEZE_TRADE_COMMAND_PAYOUT                        = 1
	BALANCE_FREEZE_TRADE_COMMAND_WITHDRAWAL                    = 2
	BALANCE_FREEZE_TRADE_COMMAND_MERCHANT_WITHDRAWAL_INITIATED = 3
	BALANCE_FREEZE_TRADE_COMMAND_MERCHANT_WITHDRAWAL_REJECTED  = 4
	BALANCE_FREEZE_TRADE_COMMAND_MERCHANT_WITHDRAWAL_SUCCESS   = 5
	BALANCE_FREEZE_TRADE_COMMAND_ADMIN_ADJUSTMENT              = 6
	BALANCE_FREEZE_TRADE_COMMAND_MERCHANT_CALLBACK_FAILD       = 7
	BALANCE_FREEZE_TRADE_COMMAND_MERCHANT_WITHDRAWAL_FEE       = 8
)

const (
	BALANCE_SETTLEMENT_TRADE_COMMAND_PAYIN       = 1
	BALANCE_SETTLEMENT_TRADE_COMMAND_TRANSACTION = 2
)

const (
	BALANCE_FREEZE_STATE   = 1
	BALANCE_UNFREEZE_STATE = 2
)

const (
	CREATE_TYPE_SYSTEM          = 1
	CREATE_TYPE_MANUAL          = 2
	CREATE_TYPE_MANUAL_CALLBACK = 3
)

const (
	VERIFY_TYPE_MODIFY_PASSWORD = iota + 1
	VERIFY_TYPE_MODIFY_EMAIL
	VERIFY_TYPE_MODIFY_MERCHANT_INFO
	VERIFY_TYPE_MODIFY_DEPOSIT
	VERIFY_TYPE_MODIFY_WITHDRAW
)

const (
	ORDER_TYPE_PAYIN_DEFAULT      = 1
	ORDER_TYPE_PAYOUT_DEFAULT     = 5
	ORDER_TYPE_SETTLEMENT_DEFAULT = 8
	ORDER_TYPE_DEPOSIT_DEFAULT    = 13
	ORDER_CHANGE_BALANCE_DEFAULT  = 9
)

var OrderMappingMark = map[int]int{
	ORDER_TYPE_PAYIN_DEFAULT:      0,
	ORDER_TYPE_PAYOUT_DEFAULT:     5,
	ORDER_TYPE_SETTLEMENT_DEFAULT: 8,
	ORDER_TYPE_DEPOSIT_DEFAULT:    13,
}

const (
	LAUNCH_TYPE_SERVER   = "server"
	LAUNCH_TYPE_LOCAL    = "local"
	LAUNCH_TYPE_ENV_PROD = "prod"
)

const (
	RESPONSE_CODE_SUCCESS = "SUCCESS"
	RESPONSE_CODE_FAILED  = "FAILED"
)

const (
	RESPONSE_TXN_STATUS_SUCCESS = "SUCCESS"
	RESPONSE_TXN_STATUS_PENDING = "PENDING"
	RESPONSE_TXN_STATUS_FAILED  = "FAILED"
	RESPONSE_TXN_STATUS_REFUND  = "REFUND"
)

const (
	PAY_IN_TYPE_NATIVE_TO_STRING   = "PAY_INTENT"
	PAY_IN_TYPE_QRCODE_TO_STRING   = "PAY_MQR"
	PAY_IN_TYPE_TRANSFER_TO_STRING = "PAY_TRANSFER"
)

const (
	ASYNC_TAKE_STATUS_WAIT   = 1
	ASYNC_TAKE_STATUS_ING    = 2
	ASYNC_TAKE_STATUS_CANCEL = 3
	ASYNC_TAKE_STATUS_FAIL   = 4
	ASYNC_TAKE_STATUS_OK     = 5
)

const (
	ASYNC_TAKE_TYPE_PAYIN_EXPORT               = 1
	ASYNC_TAKE_TYPE_PAYOUT_EXPORT              = 2
	ASYNC_TAKE_TYPE_BALANCE_LOG                = 3
	ASYNC_TAKE_TYPE_BALANCE_FREEZE_LOG         = 4
	ASYNC_TAKE_TYPE_BALANCE_SETTLEMENT_LOG     = 5
	ASYNC_TAKE_TYPE_MANUAL_PAYIN_EXPORT        = 6
	ASYNC_TAKE_TYPE_MERCHANT_LIST_EXPORT       = 7
	ASYNC_TAKE_TYPE_MERCHANT_TRANS_TYPE_EXPORT = 8
	ASYNC_TAKE_TYPE_BANK_LIST_EXPORT           = 9
	ASYNC_TAKE_TYPE_BANK_TRANS_TYPE_EXPORT     = 10
	ASYNC_TAKE_TYPE_TRANS_TYPE_EXPORT          = 11
	ASYNC_TAKE_TYPE_MERCHANT_BANK_EXPORT       = 12
	ASYNC_TAKE_TYPE_MERCHANT_CHANNEL_EXPORT    = 13
	ASYNC_TAKE_TYPE_DEPOSIT_EXPORT             = 14
	ASYNC_TAKE_TYPE_BANK_BALANCE_EXPORT        = 15
	ASYNC_TAKE_TYPE_REFUND_ORDER_EXPORT        = 16
	ASYNC_TAKE_TYPE_WITHDRAWAL_EXPORT          = 17
)

const (
	AUDIT_STATUS_WAIT_AUDIT       = 1
	AUDIT_STATUS_PASS             = 2
	AUDIT_STATUS_REJECT           = 3
	AUDIT_STATUS_ADMIN_WAIT_AUDIT = 4
	AUDIT_STATUS_ADMIN_REJECT     = 5
	AUDIT_STATUS_PASS_NOT_PAYMENT = 6
)

const (
	PROCESS_NODE_CREATE_ORDER       = 1
	PROCESS_NODE_MERCHANT_AUDIT     = 5
	PROCESS_NODE_ADMIN_AUDIT        = 10
	PROCESS_NODE_ADMIN_AUDIT_BORROW = 15
)

var RespOrderMappingMark = map[int64]string{
	PAYOUT_STATUS_SUCCESS:  RESPONSE_TXN_STATUS_SUCCESS,
	PAYOUT_STATUS_FAILED:   RESPONSE_TXN_STATUS_FAILED,
	PAYOUT_STATUS_PENDING:  RESPONSE_TXN_STATUS_PENDING,
	PAYOUT_STATUS_REFUNDED: RESPONSE_TXN_STATUS_REFUND,
}

var RespPayinOrderMappingMark = map[int64]string{
	PAY_STATUS_SUCCESS:    RESPONSE_TXN_STATUS_SUCCESS,
	PAY_STATUS_FAILDE:     RESPONSE_TXN_STATUS_FAILED,
	PAY_STATUS_REJECT:     RESPONSE_TXN_STATUS_FAILED,
	PAY_STATUS_NOT:        RESPONSE_TXN_STATUS_PENDING,
	PAY_STATUS_WAIT_AUDIT: RESPONSE_TXN_STATUS_PENDING,
	PAY_STATUS_REFUND:     RESPONSE_TXN_STATUS_REFUND,
	PAY_STATUS_COMPLAIN:   RESPONSE_TXN_STATUS_REFUND,
}

var RespPayinTypeMappingMark = map[int64]string{
	PAY_IN_TYPE_NATIVE:   PAY_IN_TYPE_NATIVE_TO_STRING,
	PAY_IN_TYPE_QRCODE:   PAY_IN_TYPE_QRCODE_TO_STRING,
	PAY_IN_TYPE_TRANSFER: PAY_IN_TYPE_TRANSFER_TO_STRING,
}

const (
	BALANCE_AMOUNT_CHANGE = 1
	BALANCE_FEE_CHANGE    = 2
)

const (
	WITHDRAWAL_ORDER_SUCCESS = 1
	WITHDRAWAL_ORDER_FAILED  = 2
	WITHDRAWAL_ORDER_PENDING = 3
)

const (
	WITHDRAWAL_ORDER_PROCESS_STATUS_SUBMIT                  = 1
	WITHDRAWAL_ORDER_PROCESS_STATUS_MERCHANT_REJECTED       = 3
	WITHDRAWAL_ORDER_PROCESS_STATUS_MERCHANT_PASS           = 5
	WITHDRAWAL_ORDER_PROCESS_STATUS_PLATFORM_REJECTED       = 7
	WITHDRAWAL_ORDER_PROCESS_STATUS_PLATFORM_PASS           = 9
	WITHDRAWAL_ORDER_PROCESS_STATUS_PLATFORM_FINAL_REJECTED = 11
	WITHDRAWAL_ORDER_PROCESS_STATUS_PLATFORM_FINAL_PASS     = 13
)

const (
	WITHDRAWAL_TIME_TYPE_CREATE = iota + 1
	WITHDRAWAL_TIME_TYPE_SUCCESS
	WITHDRAWAL_TIME_TYPE_NOTIFY
	WITHDRAWAL_TIME_TYPE_FINISH
	WITHDRAWAL_TIME_TYPE_CALLBACK
)

const (
	WITHDRAWAL_ORDER_TYPE_APP     = "app"
	WITHDRAWAL_ORDER_TYPE_CHANNEL = "channel"
)

const (
	BANK_SUBMIT_STATUS_NOT     = 1
	BANK_SUBMIT_STATUS_SUCCESS = 2
	BANK_SUBMIT_STATUS_FAILED  = 3
)

const (
	DEPOSIT_ORDER_TRANSFER_STATUS_PENDING  = 1
	DEPOSIT_ORDER_TRANSFER_STATUS_SUCCESS  = 2
	DEPOSIT_ORDER_TRANSFER_STATUS_FAILED   = 3
	DEPOSIT_ORDER_TRANSFER_STATUS_REVERSAL = 4
)

const (
	DEPOSIT_ORDER_TYPE_APP    = 1
	DEPOSIT_ORDER_TYPE_BANK   = 2
	DEPOSIT_ORDER_TYPE_BORROW = 3
)

const (
	SIGN_TYPE_ED25519 = iota + 1
	SIGN_TYPE_RSA2048
	SIGN_TYPE_SHA256
	SIGN_TYPE_MD5
)

const (
	BANK_FEE_CONTROL_FLAG_EDIT = 1
	BANK_FEE_CONTROL_FLAG_ALL  = 2
)

const (
	DELAY_EXECUTE_TIMEOUT = 2 * time.Second
	DELAY_DELETE_TIME     = 1 * time.Second
)

const (
	EXCHANGE_RATE_TYPE_DEPOSIT    = 1
	EXCHANGE_RATE_TYPE_WITHDRAWAL = 2
)

const (
	RELEASE_STATUS_NOT          = 1
	RELEASE_STATUS_NOT_COMPLETE = 2
	RELEASE_STATUS_SUCCESS      = 3
)

const (
	RELEASE_TYPE_MANUAL = 1
	RELEASE_TYPE_AUTO   = 2
)

const (
	CHANGE_BALANCE_STATUS_PENDING = 1
	CHANGE_BALANCE_STATUS_SUCCESS = 2
	CHANGE_BALANCE_STATUS_REJECT  = 3
)

const (
	REFUND_TYPE_REFUND   = 1
	REFUND_TYPE_COMPLAIN = 2
)

const (
	CHANGE_BALANCE_TRADE_TYPE_BALANCE = 1
	CHANGE_BALANCE_TRADE_TYPE_FREEZE  = 2
)

const (
	CHANGE_BALANCE_ADJUST_TYPE_BALANCE = 1
	CHANGE_BALANCE_ADJUST_TYPE_FREEZE  = 2
)

const (
	UNDERTAKE_PLATFORM = 1
	UNDERTAKE_MERCHANT = 2
	UNDERTAKE_BANK     = 3
)

const (
	// payin 1-5
	DATA_CONSUM_ORDER_TYPE_PAYIN_NATIVE   = 1
	DATA_CONSUM_ORDER_TYPE_PAYIN_QRCODE   = 2
	DATA_CONSUM_ORDER_TYPE_PAYIN_TRANSFER = 3
	// payout 6-10
	DATA_CONSUM_ORDER_TYPE_PAYOUT_NATIVE = 6

	// 11-15

	// 15-20
)

const (
	DATA_CONSUM_ORDER_STATUS_SUCCESS = 1
	DATA_CONSUM_ORDER_STATUS_FAILED  = 2
	DATA_CONSUM_ORDER_STATUS_PENDING = 3
	DATA_CONSUM_ORDER_STATUS_REFUND  = 4
)

const (
	TG_CMD_LOG_STATUS_COMPLETED = 1 // 完成
	TG_CMD_LOG_STATUS_SUSPENDED = 2 // 暂停
	TG_CMD_LOG_STATUS_PENDING   = 3 // 等待中
)

const (
	REQUEST_BANK_SECCESS = 1
	REQUEST_BANK_FAILED  = 2
)
