// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: settlement_bank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBankInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankInfoReq) Reset() {
	*x = GetBankInfoReq{}
	mi := &file_settlement_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankInfoReq) ProtoMessage() {}

func (x *GetBankInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankInfoReq.ProtoReflect.Descriptor instead.
func (*GetBankInfoReq) Descriptor() ([]byte, []int) {
	return file_settlement_bank_proto_rawDescGZIP(), []int{0}
}

func (x *GetBankInfoReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBankInfoReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBankInfosetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*BankInfoset         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankInfosetResp) Reset() {
	*x = GetBankInfosetResp{}
	mi := &file_settlement_bank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankInfosetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankInfosetResp) ProtoMessage() {}

func (x *GetBankInfosetResp) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_bank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankInfosetResp.ProtoReflect.Descriptor instead.
func (*GetBankInfosetResp) Descriptor() ([]byte, []int) {
	return file_settlement_bank_proto_rawDescGZIP(), []int{1}
}

func (x *GetBankInfosetResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetBankInfosetResp) GetList() []*BankInfoset {
	if x != nil {
		return x.List
	}
	return nil
}

type BankInfoset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BankAccount     string                 `protobuf:"bytes,2,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	BankName        string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankIdentifier  string                 `protobuf:"bytes,4,opt,name=bank_identifier,json=bankIdentifier,proto3" json:"bank_identifier,omitempty"`
	BankMobilePhone string                 `protobuf:"bytes,5,opt,name=bank_mobile_phone,json=bankMobilePhone,proto3" json:"bank_mobile_phone,omitempty"`
	BankStatus      int32                  `protobuf:"varint,6,opt,name=bank_status,json=bankStatus,proto3" json:"bank_status,omitempty"`
	Currency        string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Remark          string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime      int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BankInfoset) Reset() {
	*x = BankInfoset{}
	mi := &file_settlement_bank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankInfoset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankInfoset) ProtoMessage() {}

func (x *BankInfoset) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_bank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankInfoset.ProtoReflect.Descriptor instead.
func (*BankInfoset) Descriptor() ([]byte, []int) {
	return file_settlement_bank_proto_rawDescGZIP(), []int{2}
}

func (x *BankInfoset) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankInfoset) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *BankInfoset) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankInfoset) GetBankIdentifier() string {
	if x != nil {
		return x.BankIdentifier
	}
	return ""
}

func (x *BankInfoset) GetBankMobilePhone() string {
	if x != nil {
		return x.BankMobilePhone
	}
	return ""
}

func (x *BankInfoset) GetBankStatus() int32 {
	if x != nil {
		return x.BankStatus
	}
	return 0
}

func (x *BankInfoset) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BankInfoset) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BankInfoset) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type SettlementOperateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementOperateResp) Reset() {
	*x = SettlementOperateResp{}
	mi := &file_settlement_bank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementOperateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementOperateResp) ProtoMessage() {}

func (x *SettlementOperateResp) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_bank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementOperateResp.ProtoReflect.Descriptor instead.
func (*SettlementOperateResp) Descriptor() ([]byte, []int) {
	return file_settlement_bank_proto_rawDescGZIP(), []int{3}
}

func (x *SettlementOperateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_settlement_bank_proto protoreflect.FileDescriptor

const file_settlement_bank_proto_rawDesc = "" +
	"\n" +
	"\x15settlement_bank.proto\x12\x02pb\"8\n" +
	"\x0eGetBankInfoReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"O\n" +
	"\x12GetBankInfosetResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12#\n" +
	"\x04list\x18\x02 \x03(\v2\x0f.pb.BankInfosetR\x04list\"\xa8\x02\n" +
	"\vBankInfoset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fbank_account\x18\x02 \x01(\tR\vbankAccount\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12'\n" +
	"\x0fbank_identifier\x18\x04 \x01(\tR\x0ebankIdentifier\x12*\n" +
	"\x11bank_mobile_phone\x18\x05 \x01(\tR\x0fbankMobilePhone\x12\x1f\n" +
	"\vbank_status\x18\x06 \x01(\x05R\n" +
	"bankStatus\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\")\n" +
	"\x15SettlementOperateResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xc5\x02\n" +
	"\x0eSettlementBank\x12<\n" +
	"\x0eCreateBankInfo\x12\x0f.pb.BankInfoset\x1a\x19.pb.SettlementOperateResp\x12<\n" +
	"\x0eModifyBankInfo\x12\x0f.pb.BankInfoset\x1a\x19.pb.SettlementOperateResp\x12<\n" +
	"\x0eDeleteBankInfo\x12\x0f.pb.BankInfoset\x1a\x19.pb.SettlementOperateResp\x12>\n" +
	"\x10ModifyBankStatus\x12\x0f.pb.BankInfoset\x1a\x19.pb.SettlementOperateResp\x129\n" +
	"\vGetBankList\x12\x12.pb.GetBankInfoReq\x1a\x16.pb.GetBankInfosetRespB!Z\x1fbase/rpc_api/settlement_bank/pbb\x06proto3"

var (
	file_settlement_bank_proto_rawDescOnce sync.Once
	file_settlement_bank_proto_rawDescData []byte
)

func file_settlement_bank_proto_rawDescGZIP() []byte {
	file_settlement_bank_proto_rawDescOnce.Do(func() {
		file_settlement_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_bank_proto_rawDesc), len(file_settlement_bank_proto_rawDesc)))
	})
	return file_settlement_bank_proto_rawDescData
}

var file_settlement_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_settlement_bank_proto_goTypes = []any{
	(*GetBankInfoReq)(nil),        // 0: pb.GetBankInfoReq
	(*GetBankInfosetResp)(nil),    // 1: pb.GetBankInfosetResp
	(*BankInfoset)(nil),           // 2: pb.BankInfoset
	(*SettlementOperateResp)(nil), // 3: pb.SettlementOperateResp
}
var file_settlement_bank_proto_depIdxs = []int32{
	2, // 0: pb.GetBankInfosetResp.list:type_name -> pb.BankInfoset
	2, // 1: pb.SettlementBank.CreateBankInfo:input_type -> pb.BankInfoset
	2, // 2: pb.SettlementBank.ModifyBankInfo:input_type -> pb.BankInfoset
	2, // 3: pb.SettlementBank.DeleteBankInfo:input_type -> pb.BankInfoset
	2, // 4: pb.SettlementBank.ModifyBankStatus:input_type -> pb.BankInfoset
	0, // 5: pb.SettlementBank.GetBankList:input_type -> pb.GetBankInfoReq
	3, // 6: pb.SettlementBank.CreateBankInfo:output_type -> pb.SettlementOperateResp
	3, // 7: pb.SettlementBank.ModifyBankInfo:output_type -> pb.SettlementOperateResp
	3, // 8: pb.SettlementBank.DeleteBankInfo:output_type -> pb.SettlementOperateResp
	3, // 9: pb.SettlementBank.ModifyBankStatus:output_type -> pb.SettlementOperateResp
	1, // 10: pb.SettlementBank.GetBankList:output_type -> pb.GetBankInfosetResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settlement_bank_proto_init() }
func file_settlement_bank_proto_init() {
	if File_settlement_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_bank_proto_rawDesc), len(file_settlement_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_bank_proto_goTypes,
		DependencyIndexes: file_settlement_bank_proto_depIdxs,
		MessageInfos:      file_settlement_bank_proto_msgTypes,
	}.Build()
	File_settlement_bank_proto = out.File
	file_settlement_bank_proto_goTypes = nil
	file_settlement_bank_proto_depIdxs = nil
}
