// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: summary/summary.proto

package summary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Summary_BankSummary_FullMethodName                   = "/pb.Summary/BankSummary"
	Summary_MerchantSummary_FullMethodName               = "/pb.Summary/MerchantSummary"
	Summary_MonitorBankStats_FullMethodName              = "/pb.Summary/MonitorBankStats"
	Summary_MonitorBankDetailOverview_FullMethodName     = "/pb.Summary/MonitorBankDetailOverview"
	Summary_MonitorBankDetailCurve_FullMethodName        = "/pb.Summary/MonitorBankDetailCurve"
	Summary_MonitorBankDetailList_FullMethodName         = "/pb.Summary/MonitorBankDetailList"
	Summary_MonitorMerchantStats_FullMethodName          = "/pb.Summary/MonitorMerchantStats"
	Summary_MonitorMerchantDetailOverview_FullMethodName = "/pb.Summary/MonitorMerchantDetailOverview"
	Summary_MonitorMerchantDetailCurve_FullMethodName    = "/pb.Summary/MonitorMerchantDetailCurve"
	Summary_MonitorMerchantDetailList_FullMethodName     = "/pb.Summary/MonitorMerchantDetailList"
)

// SummaryClient is the client API for Summary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummaryClient interface {
	BankSummary(ctx context.Context, in *BankSummaryReq, opts ...grpc.CallOption) (*BankSummaryResp, error)
	MerchantSummary(ctx context.Context, in *MerchantSummaryReq, opts ...grpc.CallOption) (*MerchantSummaryResp, error)
	MonitorBankStats(ctx context.Context, in *MonitorStatsReq, opts ...grpc.CallOption) (*MonitorStatsResp, error)
	MonitorBankDetailOverview(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailOverviewResp, error)
	MonitorBankDetailCurve(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailCurveResp, error)
	MonitorBankDetailList(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailListResp, error)
	MonitorMerchantStats(ctx context.Context, in *MonitorStatsReq, opts ...grpc.CallOption) (*MonitorStatsResp, error)
	MonitorMerchantDetailOverview(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailOverviewResp, error)
	MonitorMerchantDetailCurve(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailCurveResp, error)
	MonitorMerchantDetailList(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailListResp, error)
}

type summaryClient struct {
	cc grpc.ClientConnInterface
}

func NewSummaryClient(cc grpc.ClientConnInterface) SummaryClient {
	return &summaryClient{cc}
}

func (c *summaryClient) BankSummary(ctx context.Context, in *BankSummaryReq, opts ...grpc.CallOption) (*BankSummaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankSummaryResp)
	err := c.cc.Invoke(ctx, Summary_BankSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MerchantSummary(ctx context.Context, in *MerchantSummaryReq, opts ...grpc.CallOption) (*MerchantSummaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantSummaryResp)
	err := c.cc.Invoke(ctx, Summary_MerchantSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorBankStats(ctx context.Context, in *MonitorStatsReq, opts ...grpc.CallOption) (*MonitorStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorStatsResp)
	err := c.cc.Invoke(ctx, Summary_MonitorBankStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorBankDetailOverview(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailOverviewResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDetailOverviewResp)
	err := c.cc.Invoke(ctx, Summary_MonitorBankDetailOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorBankDetailCurve(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailCurveResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDetailCurveResp)
	err := c.cc.Invoke(ctx, Summary_MonitorBankDetailCurve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorBankDetailList(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDetailListResp)
	err := c.cc.Invoke(ctx, Summary_MonitorBankDetailList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorMerchantStats(ctx context.Context, in *MonitorStatsReq, opts ...grpc.CallOption) (*MonitorStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorStatsResp)
	err := c.cc.Invoke(ctx, Summary_MonitorMerchantStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorMerchantDetailOverview(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailOverviewResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDetailOverviewResp)
	err := c.cc.Invoke(ctx, Summary_MonitorMerchantDetailOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorMerchantDetailCurve(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailCurveResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDetailCurveResp)
	err := c.cc.Invoke(ctx, Summary_MonitorMerchantDetailCurve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) MonitorMerchantDetailList(ctx context.Context, in *MonitorDetailStatsReq, opts ...grpc.CallOption) (*MonitorDetailListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDetailListResp)
	err := c.cc.Invoke(ctx, Summary_MonitorMerchantDetailList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummaryServer is the server API for Summary service.
// All implementations must embed UnimplementedSummaryServer
// for forward compatibility.
type SummaryServer interface {
	BankSummary(context.Context, *BankSummaryReq) (*BankSummaryResp, error)
	MerchantSummary(context.Context, *MerchantSummaryReq) (*MerchantSummaryResp, error)
	MonitorBankStats(context.Context, *MonitorStatsReq) (*MonitorStatsResp, error)
	MonitorBankDetailOverview(context.Context, *MonitorDetailStatsReq) (*MonitorDetailOverviewResp, error)
	MonitorBankDetailCurve(context.Context, *MonitorDetailStatsReq) (*MonitorDetailCurveResp, error)
	MonitorBankDetailList(context.Context, *MonitorDetailStatsReq) (*MonitorDetailListResp, error)
	MonitorMerchantStats(context.Context, *MonitorStatsReq) (*MonitorStatsResp, error)
	MonitorMerchantDetailOverview(context.Context, *MonitorDetailStatsReq) (*MonitorDetailOverviewResp, error)
	MonitorMerchantDetailCurve(context.Context, *MonitorDetailStatsReq) (*MonitorDetailCurveResp, error)
	MonitorMerchantDetailList(context.Context, *MonitorDetailStatsReq) (*MonitorDetailListResp, error)
	mustEmbedUnimplementedSummaryServer()
}

// UnimplementedSummaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummaryServer struct{}

func (UnimplementedSummaryServer) BankSummary(context.Context, *BankSummaryReq) (*BankSummaryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BankSummary not implemented")
}
func (UnimplementedSummaryServer) MerchantSummary(context.Context, *MerchantSummaryReq) (*MerchantSummaryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantSummary not implemented")
}
func (UnimplementedSummaryServer) MonitorBankStats(context.Context, *MonitorStatsReq) (*MonitorStatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorBankStats not implemented")
}
func (UnimplementedSummaryServer) MonitorBankDetailOverview(context.Context, *MonitorDetailStatsReq) (*MonitorDetailOverviewResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorBankDetailOverview not implemented")
}
func (UnimplementedSummaryServer) MonitorBankDetailCurve(context.Context, *MonitorDetailStatsReq) (*MonitorDetailCurveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorBankDetailCurve not implemented")
}
func (UnimplementedSummaryServer) MonitorBankDetailList(context.Context, *MonitorDetailStatsReq) (*MonitorDetailListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorBankDetailList not implemented")
}
func (UnimplementedSummaryServer) MonitorMerchantStats(context.Context, *MonitorStatsReq) (*MonitorStatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorMerchantStats not implemented")
}
func (UnimplementedSummaryServer) MonitorMerchantDetailOverview(context.Context, *MonitorDetailStatsReq) (*MonitorDetailOverviewResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorMerchantDetailOverview not implemented")
}
func (UnimplementedSummaryServer) MonitorMerchantDetailCurve(context.Context, *MonitorDetailStatsReq) (*MonitorDetailCurveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorMerchantDetailCurve not implemented")
}
func (UnimplementedSummaryServer) MonitorMerchantDetailList(context.Context, *MonitorDetailStatsReq) (*MonitorDetailListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorMerchantDetailList not implemented")
}
func (UnimplementedSummaryServer) mustEmbedUnimplementedSummaryServer() {}
func (UnimplementedSummaryServer) testEmbeddedByValue()                 {}

// UnsafeSummaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummaryServer will
// result in compilation errors.
type UnsafeSummaryServer interface {
	mustEmbedUnimplementedSummaryServer()
}

func RegisterSummaryServer(s grpc.ServiceRegistrar, srv SummaryServer) {
	// If the following call pancis, it indicates UnimplementedSummaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Summary_ServiceDesc, srv)
}

func _Summary_BankSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).BankSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_BankSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).BankSummary(ctx, req.(*BankSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MerchantSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MerchantSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MerchantSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MerchantSummary(ctx, req.(*MerchantSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorBankStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorBankStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorBankStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorBankStats(ctx, req.(*MonitorStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorBankDetailOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDetailStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorBankDetailOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorBankDetailOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorBankDetailOverview(ctx, req.(*MonitorDetailStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorBankDetailCurve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDetailStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorBankDetailCurve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorBankDetailCurve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorBankDetailCurve(ctx, req.(*MonitorDetailStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorBankDetailList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDetailStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorBankDetailList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorBankDetailList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorBankDetailList(ctx, req.(*MonitorDetailStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorMerchantStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorMerchantStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorMerchantStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorMerchantStats(ctx, req.(*MonitorStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorMerchantDetailOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDetailStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorMerchantDetailOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorMerchantDetailOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorMerchantDetailOverview(ctx, req.(*MonitorDetailStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorMerchantDetailCurve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDetailStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorMerchantDetailCurve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorMerchantDetailCurve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorMerchantDetailCurve(ctx, req.(*MonitorDetailStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_MonitorMerchantDetailList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDetailStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).MonitorMerchantDetailList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summary_MonitorMerchantDetailList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).MonitorMerchantDetailList(ctx, req.(*MonitorDetailStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Summary_ServiceDesc is the grpc.ServiceDesc for Summary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Summary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Summary",
	HandlerType: (*SummaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BankSummary",
			Handler:    _Summary_BankSummary_Handler,
		},
		{
			MethodName: "MerchantSummary",
			Handler:    _Summary_MerchantSummary_Handler,
		},
		{
			MethodName: "MonitorBankStats",
			Handler:    _Summary_MonitorBankStats_Handler,
		},
		{
			MethodName: "MonitorBankDetailOverview",
			Handler:    _Summary_MonitorBankDetailOverview_Handler,
		},
		{
			MethodName: "MonitorBankDetailCurve",
			Handler:    _Summary_MonitorBankDetailCurve_Handler,
		},
		{
			MethodName: "MonitorBankDetailList",
			Handler:    _Summary_MonitorBankDetailList_Handler,
		},
		{
			MethodName: "MonitorMerchantStats",
			Handler:    _Summary_MonitorMerchantStats_Handler,
		},
		{
			MethodName: "MonitorMerchantDetailOverview",
			Handler:    _Summary_MonitorMerchantDetailOverview_Handler,
		},
		{
			MethodName: "MonitorMerchantDetailCurve",
			Handler:    _Summary_MonitorMerchantDetailCurve_Handler,
		},
		{
			MethodName: "MonitorMerchantDetailList",
			Handler:    _Summary_MonitorMerchantDetailList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summary/summary.proto",
}
