// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: bank_data/bank_data.proto

package bank_data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankData_GetBankList_FullMethodName                 = "/pb.BankData/GetBankList"
	BankData_GetBankStatisticsList_FullMethodName       = "/pb.BankData/GetBankStatisticsList"
	BankData_GetBankBalanceDetail_FullMethodName        = "/pb.BankData/GetBankBalanceDetail"
	BankData_GetBankBalanceDetailSummary_FullMethodName = "/pb.BankData/GetBankBalanceDetailSummary"
)

// BankDataClient is the client API for BankData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== func
type BankDataClient interface {
	GetBankList(ctx context.Context, in *BankDataInfoReq, opts ...grpc.CallOption) (*BankDataRateItem, error)
	GetBankStatisticsList(ctx context.Context, in *GetBankStatisticsListRep, opts ...grpc.CallOption) (*GetBankStatisticsListResp, error)
	GetBankBalanceDetail(ctx context.Context, in *GetBankBalanceDetailRep, opts ...grpc.CallOption) (*GetBankBalanceDetailResp, error)
	GetBankBalanceDetailSummary(ctx context.Context, in *GetBankBalanceDetailRep, opts ...grpc.CallOption) (*GetBankBalanceDetailSummaryResp, error)
}

type bankDataClient struct {
	cc grpc.ClientConnInterface
}

func NewBankDataClient(cc grpc.ClientConnInterface) BankDataClient {
	return &bankDataClient{cc}
}

func (c *bankDataClient) GetBankList(ctx context.Context, in *BankDataInfoReq, opts ...grpc.CallOption) (*BankDataRateItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankDataRateItem)
	err := c.cc.Invoke(ctx, BankData_GetBankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) GetBankStatisticsList(ctx context.Context, in *GetBankStatisticsListRep, opts ...grpc.CallOption) (*GetBankStatisticsListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankStatisticsListResp)
	err := c.cc.Invoke(ctx, BankData_GetBankStatisticsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) GetBankBalanceDetail(ctx context.Context, in *GetBankBalanceDetailRep, opts ...grpc.CallOption) (*GetBankBalanceDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankBalanceDetailResp)
	err := c.cc.Invoke(ctx, BankData_GetBankBalanceDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) GetBankBalanceDetailSummary(ctx context.Context, in *GetBankBalanceDetailRep, opts ...grpc.CallOption) (*GetBankBalanceDetailSummaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankBalanceDetailSummaryResp)
	err := c.cc.Invoke(ctx, BankData_GetBankBalanceDetailSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankDataServer is the server API for BankData service.
// All implementations must embed UnimplementedBankDataServer
// for forward compatibility.
//
// ==================== func
type BankDataServer interface {
	GetBankList(context.Context, *BankDataInfoReq) (*BankDataRateItem, error)
	GetBankStatisticsList(context.Context, *GetBankStatisticsListRep) (*GetBankStatisticsListResp, error)
	GetBankBalanceDetail(context.Context, *GetBankBalanceDetailRep) (*GetBankBalanceDetailResp, error)
	GetBankBalanceDetailSummary(context.Context, *GetBankBalanceDetailRep) (*GetBankBalanceDetailSummaryResp, error)
	mustEmbedUnimplementedBankDataServer()
}

// UnimplementedBankDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankDataServer struct{}

func (UnimplementedBankDataServer) GetBankList(context.Context, *BankDataInfoReq) (*BankDataRateItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankList not implemented")
}
func (UnimplementedBankDataServer) GetBankStatisticsList(context.Context, *GetBankStatisticsListRep) (*GetBankStatisticsListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankStatisticsList not implemented")
}
func (UnimplementedBankDataServer) GetBankBalanceDetail(context.Context, *GetBankBalanceDetailRep) (*GetBankBalanceDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankBalanceDetail not implemented")
}
func (UnimplementedBankDataServer) GetBankBalanceDetailSummary(context.Context, *GetBankBalanceDetailRep) (*GetBankBalanceDetailSummaryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankBalanceDetailSummary not implemented")
}
func (UnimplementedBankDataServer) mustEmbedUnimplementedBankDataServer() {}
func (UnimplementedBankDataServer) testEmbeddedByValue()                  {}

// UnsafeBankDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankDataServer will
// result in compilation errors.
type UnsafeBankDataServer interface {
	mustEmbedUnimplementedBankDataServer()
}

func RegisterBankDataServer(s grpc.ServiceRegistrar, srv BankDataServer) {
	// If the following call pancis, it indicates UnimplementedBankDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankData_ServiceDesc, srv)
}

func _BankData_GetBankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankDataInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).GetBankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_GetBankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).GetBankList(ctx, req.(*BankDataInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_GetBankStatisticsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankStatisticsListRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).GetBankStatisticsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_GetBankStatisticsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).GetBankStatisticsList(ctx, req.(*GetBankStatisticsListRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_GetBankBalanceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankBalanceDetailRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).GetBankBalanceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_GetBankBalanceDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).GetBankBalanceDetail(ctx, req.(*GetBankBalanceDetailRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_GetBankBalanceDetailSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankBalanceDetailRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).GetBankBalanceDetailSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_GetBankBalanceDetailSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).GetBankBalanceDetailSummary(ctx, req.(*GetBankBalanceDetailRep))
	}
	return interceptor(ctx, in, info, handler)
}

// BankData_ServiceDesc is the grpc.ServiceDesc for BankData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BankData",
	HandlerType: (*BankDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBankList",
			Handler:    _BankData_GetBankList_Handler,
		},
		{
			MethodName: "GetBankStatisticsList",
			Handler:    _BankData_GetBankStatisticsList_Handler,
		},
		{
			MethodName: "GetBankBalanceDetail",
			Handler:    _BankData_GetBankBalanceDetail_Handler,
		},
		{
			MethodName: "GetBankBalanceDetailSummary",
			Handler:    _BankData_GetBankBalanceDetailSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank_data/bank_data.proto",
}
